### ISSUE TITLE
Persisted breadcrumbs should be cleared when app starts

### ISSUE THREAD

**Issue by timfish** [getsentry/sentry-electron#10]
Breadcrumbs are persisted to disk so that they are available on next run in case of native crash in main process. 

Currently, all events posted to Sentry contain breadcrumbs from multiple previous app sessions.

**Comment by timfish** [comment]
There is no way to know if the app has exited cleanly. Much better to clear breadcrumbs after startup.

**Comment by skandaswamygit** [comment]
it makes sense to clear the breadcrumbs from previous session, however, when there was a native crash, we upload the crash dump on next app launch. if breadcrumbs are cleared on startup all the time, then developers would lose all the breadcrumbs that happened at the time of crash.
