### ISSUE TITLE
Support adding screenshots to feedback

### ISSUE THREAD

**Issue by timfish** [getsentry/sentry-electron#1001]
### Problem Statement

The Electron SDk should support adding screenshots to feedback.

![Image](https://github.com/user-attachments/assets/5d6dd818-f521-466f-85b0-fcc9f5cc9e71)

### Solution Brainstorm

Why does this not work?

**Comment by dereklance** [comment]
for some more context, when clicking the add screenshot button, i see a quick "flicker" of content where the bug reporting module takes up the full screen (presumbaly to show the screenshotting tool). then it quickly closes and i see the red error message "not supported"

**Comment by timfish** [comment]
The widget screenshot capture uses `navigator.mediaDevices.getDisplayMedia` to capture the window but Electron disables this by default.

You can enable a window capturing itself by calling this in the main process after the `app` `ready` event:

```ts
  session.defaultSession.setDisplayMediaRequestHandler((request, callback) => {
    callback({ video: request.frame })
  });
```

**Comment by timfish** [comment]
Adding this detail to the docs 
- https://github.com/getsentry/sentry-docs/pull/11694

**Comment by timfish** [comment]
Do re-open this if this doesn't fix your issue!
