### ISSUE TITLE
Support of showReportDialog()

### ISSUE THREAD

**Issue by alxmiron** [getsentry/sentry-electron#101]
Does `@sentry/electron` provides/will provide a support of user feedback functionality, described in [your blog post](https://blog.sentry.io/2016/04/21/introducing-user-feedback.html)?

**Comment by jan-auer** [comment]
Given that Electron apps all have a different design, I think we will leave it up to the user to show a user report dialog in the `afterSend` hook. However, we should definitely add an API method to submit user feedback for a given event ID.

**Comment by alxmiron** [comment]
in `afterSend(data)` I tried to open feedback form with;
```
Raven.showReportDialog({
  eventId: data.event_id,
  dsn: ...
});
```

but this mix of `Sentry` and `Raven` doesn't work - `data.event_id` is different from event id in sentry dashboard (somehow), so feedback is not displayed for particular issue 😢

**Comment by HazAT** [comment]
@alxmiron This will work in the next release :)
https://github.com/getsentry/sentry-electron/pull/119
