### ISSUE TITLE
Wrong stack frame file path for macOS universal app

### ISSUE THREAD

**Issue by michalzaq12** [getsentry/sentry-electron#1010]
### Is there an existing issue for this?

- [x] I have checked for existing issues https://github.com/getsentry/sentry-javascript/issues
- [x] I have reviewed the documentation https://docs.sentry.io/
- [x] I am using the latest SDK release https://github.com/getsentry/sentry-javascript/releases

### How do you use Sentry?

Sentry Saas (sentry.io)

### Electron SDK Version

4.17.0

### Electron Version

30

### What platform are you using?

MacOS

### Steps to Reproduce

For errors coming from a macOS universal app, I get the full path in a stack trace: 
![Image](https://github.com/user-attachments/assets/c47c5384-d080-49d8-b6fe-2b4eec8da4df)

Correct path from non-universal app:
![Image](https://github.com/user-attachments/assets/ca6701ae-a378-4d5a-a59d-e8978760e68b)

`app.getAppPath()` returns the path to `app.asar`, but the files are located in `app-arm64.asar` or `app-x64.asar`, depending on the device architecture.

To build a universal app, I use `@electron/universal` with `mergeASARs: false` option. 

### Expected Result

...

### Actual Result

...

**Comment by timfish** [comment]
Reading through this again, it sounds like `app.getAppPath()` is returning the incorrect path?

**Comment by timfish** [comment]
- https://github.com/electron/universal/issues/113

**Comment by michalzaq12** [comment]
**Update**
`app.getAppPath()` works fine. There is a simple js file in `app.asar` that imports the required files (located in `app-arm64.asar` or `app-x64.asar`, depending on the device architecture).

Here is a problem: https://github.com/getsentry/sentry-electron/blob/master/src/main/normalize.ts#L17, filename is not normalized. 

**Demo**
```ts

// https://github.com/getsentry/sentry-javascript/blob/master/packages/utils/src/normalize.ts#L285
function normalizeUrlToBase(url: string, basePath: string): string {
    const escapedBase = basePath
      // Backslash to forward
      .replace(/\\/g, '/')
      // Escape RegExp special characters
      .replace(/[|\\{}()[\]^$+*?.]/g, '\\$&');
  
    let newUrl = url;
    try {
      newUrl = decodeURI(url);
    } catch (_Oo) {
      // Sometime this breaks
    }
    return (
      newUrl
        .replace(/\\/g, '/')
        .replace(/webpack:\/?/g, '') // Remove intermediate base path
        // eslint-disable-next-line @sentry-internal/sdk/no-regexp-constructor
        .replace(new RegExp(`(file://)?/*${escapedBase}/*`, 'ig'), 'app:///')
    );
  }


const APP_PATH = 'D:\\sentry_test_app\\app.asar' // app.getAppPath()

// 1. Non-universal app => path normalized
console.log(normalizeUrlToBase('D:\\sentry_test_app\\app.asar\\dist\\main\\index.js', APP_PATH))
// app:///dist/main/index.js

// 2. Universal app => path is not normalized
console.log(normalizeUrlToBase('D:\\sentry_test_app\\app-arm64.asar\\dist\\main\\index.js', APP_PATH))
// D:/sentry_test_app/app-arm64.asar/dist/main/index.js

```

**Comment by timfish** [comment]
The normalisation code relies on `app.getAppPath()` returning the correct app root path. The issue is that `@electron/universal` uses a stub app that routes to arch specific apps but this means that `app.getAppPath()` does not return the correct path.

**Comment by michalzaq12** [comment]
This has already been fixed in the latest `@electron/universal`. Sorry, my mistake.
