### ISSUE TITLE
Fetch API cannot load sentry-ipc://sentry-electron.scope/sentry_key. URL scheme "sentry-ipc" is not supported.

### ISSUE THREAD

**Issue by DanishMehmood-bit** [getsentry/sentry-electron#1013]
### Is there an existing issue for this?

- [x] I have checked for existing issues https://github.com/getsentry/sentry-javascript/issues
- [x] I have reviewed the documentation https://docs.sentry.io/
- [x] I am using the latest SDK release https://github.com/getsentry/sentry-javascript/releases

### How do you use Sentry?

Sentry Saas (sentry.io)

### Electron SDK Version

5.7.0

### Electron Version

33.0.2

### What platform are you using?

Windows

### Steps to Reproduce

Hi. I'm trying to setup session replay in our electron project. I'm following the documentation and added it like this:
![Image](https://github.com/user-attachments/assets/a278c1c8-073c-4028-b457-8d5d3f263ea6)

Since we do have csp in place and docs said to add worker-src directive to the csp, so I did like this:
worker-src 'self' blob:

Now whenever I run the app, I get these errors in the console:
![Image](https://github.com/user-attachments/assets/47db09bd-3876-4492-976c-560e89923dc3)

I'm using sentry on protocol mode and it is registered in sentry itself.

### Expected Result

Sentry should send the requests as mentioned in the docs unless some step is missing in the docs itself.

### Actual Result

Getting this error in console
![Image](https://github.com/user-attachments/assets/3d716d6a-d67d-4449-9538-24da80557aa3)

**Comment by timfish** [comment]
It's hard to know exactly what's going on without a full example.

Are you starting Sentry in the main process? Are you starting it before the `app` `ready` event? Is it only Replay events that are not working or are all events not making it to the main process?

**Comment by DanishMehmood-bit** [comment]
> It's hard to know exactly what's going on without a full example.
> 
> Are you starting Sentry in the main process? Are you starting it before the `app` `ready` event? Is it only Replay events that are not working or are all events not making it through the main process?

Yes sentry is initialized in the main process this way:
![Image](https://github.com/user-attachments/assets/a83800b4-c1e5-43d4-8f5c-dcd98a68f077)

and yes we initialize sentry before app is ready.

Sentry is reporting errors, its just session replay which is throwing the error

**Comment by timfish** [comment]
If you disable CSP, does Replay start working?

**Comment by DanishMehmood-bit** [comment]
@timfish yes if I disable csp entirely then replay start working. Sorry for the delay in response

**Comment by timfish** [comment]
Ah perfect. Can you share your full CSP that blocks Replay?

**Comment by DanishMehmood-bit** [comment]
Hi @timfish, sorry for the delay but idk after disabling and enabling the csp again everything is working from our end. Now the replays are shown along with errors. I'll do a bit of more testing in coming days and then close this issue if everything is working fine.

**Comment by bukacdan** [comment]
@timfish I came across the same issue. When I turn on debug in Sentry initialisation, I'm getting
`Refused to connect to 'sentry-ipc://sentry-electron.renderer-start/sentry_key' because it violates the following Content Security Policy directive: "connect-src 'self' * 'unsafe-eval'". Note that '*' matches only URLs with network schemes ('http', 'https', 'ws', 'wss'), or URLs whose scheme matches `self`'s scheme. The scheme 'sentry-ipc:' must be added explicitly.`

I tried adding custom header to my `window.html`, but didn't help.
`<meta http-equiv="Content-Security-Policy" content="connect-src 'self' * 'unsafe-eval' sentry-ipc:;">`

Errors from main are correctly reported to Sentry, errors from renderer are not. I tried multiple times to catch errors in renderer and one time it came through to Sentry, also reporting all the previous attempts. But it was completely random, the only thing coming to mind is that one of the reported events contained Session Replay. But removing the replay integration didn't help either

This is raised in renderer sentry intialisation, like so:
```javascript
import * as SentryRenderer from "@sentry/electron/renderer";
import { init as reactInit } from "@sentry/react";

const initSentryRenderer = () => {
    // Initialize the Sentry SDK
    // This should be called as early as possible in the renderer process
    // if (process.env.NODE_ENV !== 'production') return;
    SentryRenderer.init({
        dsn: process.env.SENTRY_DSN,
        debug: true,
        integrations: [
            SentryRenderer.browserTracingIntegration(),
            SentryRenderer.replayIntegration(),
        ],
        
        // Set tracesSampleRate to 1.0 to capture 100%
        tracesSampleRate: 1.0,
        
        // Capture Replay for 10% of all sessions,
        // plus for 100% of sessions with an error
        replaysSessionSampleRate: 0.1,
        replaysOnErrorSampleRate: 1.0,
    }, reactInit);  // Add platform-specific SDKs
}
```

Sentry init in main, as a first line, before app is ready using this function:
import * as SentryMain from "@sentry/electron/main";

```javascript
const initSentryMain = () => {
    // Initialize the Sentry SDK
    // This should be called as early as possible in the main process
    if (process.env.NODE_ENV !== 'production') return;
    SentryMain.init({
        dsn: process.env.SENTRY_DSN,
        tracesSampleRate: 1.0,
        ipcMode: SentryMain.IPCMode.Classic,
    });
}
```

**Comment by timfish** [comment]
If you select to use `IPCMode.Classic` that means the browser SDK will communicate with the main process via electrons IPC and that requires that the correct code is run in a preload script. We do attempt to inject preload scripts but this can fail for a variety of reasons including bundling. The docs detail how to do this manually.

The fact that your renderer processes are trying to communicate via the `sentry-ipc` protocol suggests that your preload script is not configured and was not availabile.

If you share a repository reproducing your issue I can advise further!
