### ISSUE TITLE
Is the Anr detection open by default?

### ISSUE THREAD

**Issue by CurryYangxx** [getsentry/sentry-electron#1015]
### Is there an existing issue for this?

- [x] I have checked for existing issues https://github.com/getsentry/sentry-javascript/issues
- [x] I have reviewed the documentation https://docs.sentry.io/
- [x] I am using the latest SDK release https://github.com/getsentry/sentry-javascript/releases

### How do you use Sentry?

Sentry Saas (sentry.io)

### Electron SDK Version

5.4.0

### Electron Version

31.4.0

### What platform are you using?

MacOS

### Steps to Reproduce

According to the doc (https://docs.sentry.io/platforms/javascript/guides/electron/configuration/integrations/anr/), it seems the ANR is open by default. But I can not find any ANR event on the sentry platform, though we got some app not responding feedback from the user.

Should we need to open ANR manually? Even if I do not want to captureStackTrace.

### Expected Result

ANR open by default.

### Actual Result

--

**Comment by smeubank** [comment]
with the docs fix, this issue can be closed, re-open if i am wrong
