### ISSUE TITLE
Update Debug Information Files Documentation

### ISSUE THREAD

**Issue by tsekiguchi** [getsentry/sentry-electron#1019]
Currently, there's a lot of in depth documentation about uploading our own debug files. However, as mentioned over in `sentry-cli`, [this issue has been mostly resolved by adding electron to the debug frameworks.](https://github.com/getsentry/sentry-cli/issues/509#issuecomment-538627864)

This is a great solution - however, this is not mentioned anywhere in the current Electron docs, which led me on a long quest to find and unsuccessfully upload dSYM files to Sentry.

For future users, can we please update the documentation to include information about this very important option?

And even better, is there a way to have this auto-enabled for all electron projects? :)

**Comment by tsekiguchi** [comment]
Ah, I didn't see it there! Apologies on my end for missing that.

I was looking in this section here:
https://docs.sentry.io/platforms/javascript/guides/electron/data-management/debug-files/

When I searched for 'debug' in the docs, this section was pulled up, and actually I don't see the section you're linking to anywhere in the top results.

![Image](https://github.com/user-attachments/assets/12d85b00-8aaa-431c-aa2b-cb15ea21dbca)

Also, in the section you referenced, I don't want to be too elementary, but it helped to have the screenshot to help give some extra emphasis to it. It would be easy to miss as it is. :)

**Comment by timfish** [comment]
I think there might have also been some discussions over whether we can have these debug repositories automatically enabled when users select Electron as a project type.

**Comment by andreiborza** [comment]
@tsekiguchi cool, thanks!

For images, you can create an `img` folder relative to the mdx file and use markdown image syntax. For example: https://github.com/getsentry/sentry-docs/blob/1715fe49162cc3b55a2ddafb8f3f251a524afa35/docs/product/codecov/how-it-works.mdx

Let me know if you need any help.

**Comment by timfish** [comment]
> I think there might have also been some discussions over whether we can have these debug repositories automatically enabled when users select Electron as a project type.

The new Sentry project setup should now automatically enable these repositories by default if you select Electron.
