### ISSUE TITLE
Sentry.configureScope is not a function

### ISSUE THREAD

**Issue by gliss** [getsentry/sentry-electron#102]
In my electron app I'm trying to update user information for sentry but keep getting `TypeError: Sentry.configureScope is not a function`, I'm trying to pass user data via ipc.

Main.js
```javascript
ipcMain.on("update-sentry-user-scope", function(event, arg) {
	if (arg.email) {
		Sentry.configureScope(scope => {
			scope.setUser({
				email: arg.email
			});
		});
	}
	if (arg.store) {
		Sentry.configureScope(scope => {
			scope.setUser({
				store: arg.store
			});
		});
	}
	if (arg.lane) {
		Sentry.configureScope(scope => {
			scope.setUser({
				lane: arg.lane
			});
		});
	}
});
```

loginService.js

`ipc.send("update-sentry-user-scope", { email: user.email });`

Any thoughts on how I should be doing this if not via ipc.

**Comment by timfish** [comment]
Since the latest release (0.8.0) you can call `configureScope` from either process and it will be combined in the main process automatically via IPC.

How are you importing `Sentry`?

**Comment by gliss** [comment]
Importing via require
`const Sentry = require("@sentry/electron");`

then calling 
`Sentry.init({})`

So I could call in my angularjs code
```Javascript
const Sentry = window.nodeRequire("@sentry/electron");
Sentry.init({...})
Sentry.configureScope(scope => {
	scope.setUser({
	      email: localStorage.getItem('email')
	});
});
```
and it will be sent one error for both processes?

**Comment by timfish** [comment]
Yep, this should work. 

`@sentry/electron` sends all events and scope to the main process. This means that you get combined data from multiple renderers and if the renderer process crashes from a native exception, nothing is lost. 

Let me know if the above works as you would expect.

**Comment by gliss** [comment]
If `Sentry.configureScope()` is called multiple times does it get overwritten each time?

**Comment by HazAT** [comment]
@gliss Depending on what you call.
`setExtra` and `setTag` work similar like `setState` in react, they add stuff.
`setUser` on the other hand is a single object which will be overwritten everytime you call it.

**Comment by gliss** [comment]
@HazAT thanks makes sense.

@timfish thanks for your help
