### ISSUE TITLE
Sync global scope from render process to main process

### ISSUE THREAD

**Issue by zation** [getsentry/sentry-electron#1022]
### Problem Statement

It seems only current scope and isolated scope are synced to main process. Why not to sync global scope to main process?
[https://github.com/getsentry/sentry-electron/blob/master/src/common/scope.ts](url)

### Solution Brainstorm

Can we add `getGlobalScope().addScopeListener`? Or is there any problem to do so?

**Comment by timfish** [comment]
Is there any reason you're using the global scope rather than the current scope?
