### ISSUE TITLE
Breakpoint not work when enable ANR detection.

### ISSUE THREAD

**Issue by CurryYangxx** [getsentry/sentry-electron#1029]
### Is there an existing issue for this?

- [x] I have checked for existing issues https://github.com/getsentry/sentry-javascript/issues
- [x] I have reviewed the documentation https://docs.sentry.io/
- [x] I am using the latest SDK release https://github.com/getsentry/sentry-javascript/releases

### How do you use Sentry?

Sentry Saas (sentry.io)

### Electron SDK Version

5.4.0

### Electron Version

31.4.0

### What platform are you using?

MacOS

### Steps to Reproduce

1. open anr when init
```
  // main
  Sentry.init({
    ...SENTRY_OPTIONS,
    transportOptions: {
      /**
       * Called before we attempt to send an envelope to Sentry.
       *
       * If this function returns false, `shouldStore` will be called to determine if the envelope should be stored.
       *
       * Default: () => true
       *
       * @param envelope The envelope that will be sent.
       * @returns Whether we should attempt to send the envelope
       */
      shouldSend: () => enabled,
    },
    integrations: [
      Sentry.anrIntegration({ captureStackTrace: true }),
    ],
  });

  // renderer
  Sentry.init({
    ...SENTRY_OPTIONS,
    // enable sentry tracing
    integrations: [Sentry.browserTracingIntegration()],
    // set 0.1 sample rate for traces, only send 10% of traces, and check whether the limit is exceeded
    // https://konghq.sentry.io/settings/billing/overview/?category=transactions
    tracesSampleRate: 0.1,
    anrDetection: {
      captureStackTrace: true,
    },
  });
```

2. add `debugger` in jscode in renderer process
3. open devtool and can not hit breakpoint
4. after close anr option, if can stop at breakpoint

### Expected Result

stop at breakpoint

### Actual Result

can not stop at breakpoint

**Comment by s1gr1d** [comment]
Hello, just to make sure I understood the issue correctly: 
- You have a `debugger` statement in your code
- When the `anrIntegration` is added to Sentry, the devtools don't stop at the breakpoint
- When you remove the `anrIntegration` (but Sentry is still enabled), the devtools stop at the breakpoint

Is this what is happening?

**Comment by timfish** [comment]
In many ways, this is related to https://github.com/getsentry/sentry-javascript/issues/13414.

Both local variables and ANR use the debugger and we should probably not enable them and log a warning when users pass debugger cli args?

**Comment by CurryYangxx** [comment]
> Hello, just to make sure I understood the issue correctly:
> 
> * You have a `debugger` statement in your code
> * When the `anrIntegration` is added to Sentry, the devtools don't stop at the breakpoint
> * When you remove the `anrIntegration` (but Sentry is still enabled), the devtools stop at the breakpoint
> 
> Is this what is happening?

@s1gr1d yes

**Comment by s1gr1d** [comment]
> Both local variables and ANR use the debugger and we should probably not enable them and log a warning when users pass debugger cli args?

Yes, logging a warning sounds reasonable

**Comment by timfish** [comment]
Reopened since this has not been merged into the Electron SDK yet...
