### ISSUE TITLE
Error: Object has been destroyed

### ISSUE THREAD

**Issue by steverandy** [getsentry/sentry-electron#104]
Sometimes getting the following error.

```
Error: Object has been destroyed
  File "app:///node_modules/@sentry/electron/dist/main/backend.js", line 257, col 68, in Immediate.setImmediate [as _onImmediate]
    this.instrumentBreadcrumbs(`WebContents[${contents.id}]`, contents, ['dom-ready', 'load-url', 'destroyed']);
  File "timers.js", line 789, col 20, in runCallback
  File "timers.js", line 751, col 5, in tryOnImmediate
  File "timers.js", line 722, col 5, in processImmediate [as _immediateCallback]
```

**Comment by HazAT** [comment]
Can you please update to the latest version and report if this still happens?

**Comment by ipy** [comment]
<img width="1056" alt="图片" src="https://user-images.githubusercontent.com/2088040/63664485-4a5e7800-c7f9-11e9-8e16-5debec318c5a.png">

Reproduced on the latest version. I'd suggest checking `isDestroyed()` before instrumentBreadcrumbs

**Comment by timfish** [comment]
@ipy have you got some code that reproduces this?

The only way I can see this happening is if the webContents/window is destroyed immediately.

**Comment by HaNdTriX** [comment]
I am having the same error.

**Comment by timfish** [comment]
Looks like this was [fixed a while ago](https://github.com/getsentry/sentry-electron/blob/e09ba8e7101096d9db1cc596d83b12bb186c0caa/src/main/integrations/electron.ts#L40-L42)!
