### ISSUE TITLE
Catching download exception causes app crash

### ISSUE THREAD

**Issue by alxmiron** [getsentry/sentry-electron#107]
I use [electron-builder](https://github.com/electron-userland/electron-builder) to build and autoupdate my app. When new update is found, updater tries to download it differentially and fails:
`Cannot download differentially, fallback to full download: Error: EBADF: bad file descriptor` (string from logs)

If I remove @sentry/electron, the app is updated successfully with full download. But with sentry it unexpectedly crashes without any bug reporting, without user warning. I suppose that exception is handled with error by sentry. So app can't update and work correctly. I had to replace with Raven again since this is critical to me

**Comment by alxmiron** [comment]
Issue is reproduced with v0.9.0

**Comment by HazAT** [comment]
@alxmiron Thanks for the update.
I suppose creating a minimal repro case for this is a bit more effort since it requires an endpoint to download the update, right?!
We try to make time for this to find out what's going on here.

**Comment by alxmiron** [comment]
Yes, this bug is hard to catch because it can be reproduced only in production mode (autoupdate is not working in dev mode)

Here is [my test app](https://www.dropbox.com/s/9tyg8m6fddx9cxb/Hitask-Test.exe?dl=0) v3.1.4, where you can see the error: launch it on windows 10 and wait 1-2 minutes. I will look for updates in [cdn.hitask.com/desktop/testask/windows/latest.yml](https://cdn.hitask.com/desktop/testask/windows/latest.yml) and try to upgrade to v3.1.5 (or newer). Once it finds the update - it crashes. Nothing is tracked in sentry.io. Logs are in "%USERPROFILE%\AppData\Roaming\Hitask-Test\log.log"

Sentry initialized as in tutorial:

```
import * as Sentry from '@sentry/electron';

Sentry.init({
	dsn: __SENTRY_PUBLIC_DSN__,
	release: __APP_VERSION__,
	environment: __ENV__,
});
```

Hope it will help

**Comment by timfish** [comment]
Closing as it sounds fixex
