### ISSUE TITLE
Disable console logs

### ISSUE THREAD

**Issue by akashnimare** [getsentry/sentry-electron#113]
Is it possible to disable the console logs?

**Comment by HazAT** [comment]
Which `console.log`s are you talking about?

**Comment by akashnimare** [comment]
It's the browser's console log. The one you get on opening the app's `dev tools > console`.

**Comment by HazAT** [comment]
Can you please post a screenshot what you exactly mean?
Sentry does't do any `console.log` by default, only if you enable `debug: true`

**Comment by jan-auer** [comment]
@akashnimare These consoles are empty, so which logs exactly are you referring to? Ideally, could you please point to the origin of the log so we can figure out where it might be coming from (the file and line number on the right of a log, once it's there)? 
Thanks!

**Comment by akashnimare** [comment]
That's just for showing the console thing. Can you share your email or something so that I can directly share the sentry logs and other info as well?

**Comment by untitaker** [comment]
@akashnimare in case you're asking how to prevent the entire developer tools window from showing, this is not related to the Sentry SDK. Electron does this.

**Comment by jan-auer** [comment]
@akashnimare sure thing, please send them over to jan.auer@sentry.io

**Comment by akashnimare** [comment]
> in case you're asking how to prevent the entire developer tools window from showing, this is not related to the Sentry SDK. Electron does this.

@untitaker ah, no this is not what I want. I'll make myself a bit more clear in the email.

**Comment by timfish** [comment]
We have just released v3.0.0 of the SDK which includes a lot of changes and improvements since this issue was opened. 

If you can still reproduce this with v3, please open a new issue and I'll look into it.
