### ISSUE TITLE
100% CPU when adding renderer reporting

### ISSUE THREAD

**Issue by jondot** [getsentry/sentry-electron#118]
Hi,
Not sure how to give you a self-contained example, but I'm having a case where renderer process is stuck 100% cpu when adding integration into renderer process and entire app is unresponsive, nor have access to dev toos. main process works fine and reports crashes well.

**Comment by jondot** [comment]
Actually exactly like the demo states. simply copy/paste the code snippet.
I did another experiment as well - just require the library, and then after app loads, open inspector, and issue the `init` manually through developer console, get a freeze after 10 sec.

**Comment by timfish** [comment]
We have just released v3.0.0 of the SDK which includes a lot of changes and improvements since this issue was opened. 

If you can still reproduce this with v3, please open a new issue and I'll look into it.
