### ISSUE TITLE
Where can I find sentry-symbols.js?

### ISSUE THREAD

**Issue by aguynamedben** [getsentry/sentry-electron#125]
I didn't use "Sentry Wizard" to implement this library with my Electron project. How can I find the [sentry-symbols.js file](https://docs.sentry.io/platforms/javascript/electron/native/#uploading-debug-information)?

As a workaround, I'm downloading the debug information file myself to ~/Download/ and running:
```
./node_modules/.bin/sentry-cli upload-dif -t dsym ~/Downloads/electron-v2.0.11-darwin-x64-dsym.zip --org my-org --project my-project
```

**Comment by HazAT** [comment]
The script can be found here, you should be able to use it by just calling it like `node sentry-symbols.js`

https://github.com/getsentry/sentry-wizard/blob/master/scripts/Electron/symbols.js

Sentry Wizard just copies it to your project and makes sure all deps are installed.

**Comment by aguynamedben** [comment]
@HazAT Ah! I was Googling for a while but didn't come across getsentry/sentry-wizard. Thanks!

**Comment by aguynamedben** [comment]
FYI @HazAT our app is based on the popular electron-react-boilerplate project, and I posted in this issue some things you might be interested in how we setup electron-sentry with that project: https://github.com/electron-react-boilerplate/electron-react-boilerplate/issues/1560

Y'all have it pretty well-covered in your docs, but that's how we do it in a real day-to-day app. The main "ahhh nice" thing was cleaning up breadcrumb logging from electron-log and redux-logger.
