### ISSUE TITLE
Sourcemaps in typescript app doesn't work

### ISSUE THREAD

**Issue by danii1** [getsentry/sentry-electron#133]
Trying to get sourcemaps working for a few days, but unable to do so, I've checked issues with sourcemaps including #54, but wasn't able to figure out the problem with them. Link to issue on sentry.io:
https://sentry.io/disco/disco-bulkuploader/issues/738792264/

<img width="677" alt="screen shot 2018-10-22 at 14 13 19" src="https://user-images.githubusercontent.com/5345961/47289704-b209cc80-d604-11e8-8ded-3c3534315634.png">

Artifacts were uploaded for renderer process(renderer.js, renderer.js.map), I ended up disabling uglifier in an attempt to at least see the js file contents, but with no luck. Current SentryWebpackPlugin config looks like this:
```js
new SentryWebpackPlugin({
      include: ['./dist/renderer'],
      ext: ['map', 'js', 'ts'],
      ignoreFile: '.sentrycliignore',
      ignore: ['node_modules'],
      configFile: 'sentry.properties',
    }),
```
tried using this to upload ts files also in the ./src directory, doesn't make any difference
```js 
include: ['./dist/renderer', '.'],
```

.tsconfig.production.json
```js
{
  "extends": "./tsconfig",
  "compilerOptions": {
      "sourceMap": true,
      "inlineSources": true,
      "sourceRoot": "/",
  }
}
```

I don't know where to look anymore, maybe someone from Sentry developers can get some insight what's wrong with the config?

**Comment by steverandy** [comment]
I'm also having issue with sourcemaps.
Previously, it was working well, but since I've updated the recent versions of sentry-electron, the sourcemaps no longer working.
Is there a way to identify the root cause?
For me nothing have changed, except the sentry-electron version.

**Comment by Superjo149** [comment]
Would love to see an example or someone who implemented this properly. With sourcemaps, my sentry still shows minified code, and mostly doesn't show the right location. https://github.com/Superjo149/auryo

**Comment by adipascu** [comment]
Version 0.13.0 does not work with renderer source maps.
I just checked 0.14.0 and it works!

@Superjo149 Check out https://github.com/adipascu/sentry-electron-example for a working example.

Cheers!

**Comment by HazAT** [comment]
`0.14.0` should fix the problem.

**Comment by danii1** [comment]
Seems to work, but I've had to add ```include: ['.', './dist/renderer'],``` to get it working in my case ( project based on https://github.com/electron-userland/electron-webpack). Not sure if it's a bug in my configuration or sentry-electron.
