### ISSUE TITLE
showReportDialog() in it's own sub window?

### ISSUE THREAD

**Issue by UndefinedOffset** [getsentry/sentry-electron#141]
Is it possible to have the showReportDialog() open in a new window? Our app has a small main window and some small sub-windows so it would be nice to be able to open the report dialog in a new window. That way it's not so crammed into a small area.

**Comment by HazAT** [comment]
Right now it isn't, but we are working on internal API changes that makes things like this possible.
I can't give you a timeframe though.

**Comment by AbhiPrasad** [comment]
We now have the Sentry user feedback widget: https://docs.sentry.io/platforms/javascript/user-feedback/

This can be customized in a variety of ways, and connected to sentry session replay. We recommend using this for scenarios like what is outlined in this GH issue.

Closing this issue for now.
