### ISSUE TITLE
just catch crash & how to setup multi dsn to divsion error and crash 

### ISSUE THREAD

**Issue by ostrichl** [getsentry/sentry-electron#145]
I need send error and crash  to diffferent dsn,  now config  enableNative: true,
    enableJavaScript: false,   enableUnresponsive: false,   it will capture setup error
and another Sentry init just capture error is not work.  please give me some advices.thanks

**Comment by timfish** [comment]
We have just released v3.0.0 of the SDK which includes a lot of changes and improvements since this issue was opened. 

If you can still reproduce this with v3, please open a new issue and I'll look into it.
