### ISSUE TITLE
uncaughtException handler doesn't hide default Electron error message

### ISSUE THREAD

**Issue by ZudoMC** [getsentry/sentry-electron#146]
I have an application with both a `Sentry.init` call and a `process.on("uncaughtException", ...)` callback to display a custom error message to the user.

Handling an exception in this way should cause Electron's default "A JavaScript error occurred" dialog to be disabled, but after calling `Sentry.init`, the dialog is displayed anyway, along with my custom error message. 

Is there something I'm missing, or is this a bug?

@sentry/electron - 0.14.0
electron - 4.0.0

**Comment by timfish** [comment]
This is a bug as it should replicate the default Electron behavior. 

For now, you can disable the dialog by setting an empty `onFatalError` callback:
```typescript
    Sentry.init({
      dsn: '___DSN___',
      onFatalError: _ => {},
    });
```

**Comment by timfish** [comment]
PR #147, makes it so that both hooking the Sentry `onFatalError` or `process.on('uncaughtException')` disables the dialog.

Just be aware that if you want to terminate the process on error, you should be doing this in `onFatalError` where you can be sure that Sentry has finished sending its events.

**Comment by ZudoMC** [comment]
Got it, the `uncaughtException` handler is only there to show a user friendly error message.

I'll leave the issue open so it gets closed on a merge.
