### ISSUE TITLE
 Interface 'ElectronOptions' cannot simultaneously extend types 'Options' and 'NodeOptions'.

### ISSUE THREAD

**Issue by sjaanus** [getsentry/sentry-electron#150]
I have this added as npm dependency:
```
  "dependencies": {
    "@sentry/electron": "0.15.0"
}
```
And using it in the code like this, both on renderer and main proccess:

```
import * as Sentry from '@sentry/electron';

Sentry.init({
  dsn: AppConfig.sentryDsn
});

```
After npm install, I run npm start and I am getting this error. Are the typings wrong ?

![image](https://user-images.githubusercontent.com/964450/51208447-5eaece00-1916-11e9-9948-d9eb29c3043a.png)

Any idea how to get it to work?

**Comment by timfish** [comment]
From the linked PR it looks like you got this sorted!
