### ISSUE TITLE
Infinite loop when internet disconnected (net::ERR_INTERNET_DISCONNECTED)

### ISSUE THREAD

**Issue by aguynamedben** [getsentry/sentry-electron#151]
We occasionally see the the following native crash error from users:
```
EXC_BAD_INSTRUCTION / EXC_I386_INVOPatom::AtomBindings::Crash()
fatal
Fatal Error: EXC_BAD_INSTRUCTION / EXC_I386_INVOP
```

The error details have `v8::internal::V8::FatalProcessOutOfMemory(char const*, bool)` which is v8 killing the process because it's taking up too much memory.

A few times we've seen in our breadcrumbs powerMonitor events indicating the user had recently turned on their laptop (i.e. after getting to their office). We think the flow is this:
* The user runs our app with internet, everything is fine.
* The user goes to a different location and opens up their laptop. Our app is still running, but now there is no internet.
* Our app throws an error in the renderer.
* Sentry tries to handle the error in the main process.
* Sentry gets into an infinite loop (in the main process) of trying to report the error, failing, trying to report the error, failing.
* During the infinite loop the UI of our app is frozen and unusable.
* After 45-60 minutes the infinite loop uses too much memory and the main process crashes. This is especially bad because our app is a utility that is supposed to be "always on".

During the loop, in local logs this can be seen:
```
Sentry Logger [Error]: Error: net::ERR_INTERNET_DISCONNECTED
Sentry Logger [Error]: Error: net::ERR_INTERNET_DISCONNECTED
Sentry Logger [Error]: Error: net::ERR_INTERNET_DISCONNECTED
Sentry Logger [Error]: Error: net::ERR_INTERNET_DISCONNECTED
Sentry Logger [Error]: Error: net::ERR_INTERNET_DISCONNECTED
Sentry Logger [Error]: Error: net::ERR_INTERNET_DISCONNECTED
Sentry Logger [Error]: Error: net::ERR_INTERNET_DISCONNECTED
Sentry Logger [Error]: Error: net::ERR_INTERNET_DISCONNECTED
Sentry Logger [Error]: Error: net::ERR_INTERNET_DISCONNECTED
Sentry Logger [Error]: Error: net::ERR_INTERNET_DISCONNECTED
Sentry Logger [Error]: Error: net::ERR_INTERNET_DISCONNECTED
Sentry Logger [Error]: Error: net::ERR_INTERNET_DISCONNECTED
Sentry Logger [Error]: Error: net::ERR_INTERNET_DISCONNECTED
Sentry Logger [Error]: Error: net::ERR_INTERNET_DISCONNECTED
Sentry Logger [Error]: Error: net::ERR_INTERNET_DISCONNECTED
Sentry Logger [Error]: Error: net::ERR_INTERNET_DISCONNECTED
Sentry Logger [Error]: Error: net::ERR_INTERNET_DISCONNECTED
```

However, these message are not reported in breadcrumbs. My app does log memory stats to breadcrumbs, however, and we see things like:
```
HIGH RSS MEMORY USAGE - Memory usage - main - pid 295 - RSS: 2036 MB, Heap Used: 949 MB, Heap Total: 1458 MB, External: 0 MB
```
(the main process is using 2GB of memory! our app never does this normally!)

I think there is an error reporting issue similar to the [429 loop issue](https://github.com/getsentry/sentry-javascript/issues/1668) that was causing Electron apps to crash.

It looks like there were a few issue from Dec 2018 in sentry-javascript regarding infinite loops, I'll try to make sure I'm updated. Right now this is happening with:
```
├─ @sentry/core@4.3.4
├─ @sentry/electron@0.14.0
```

**Comment by aguynamedben** [comment]
It looks like this might have been fixed with the changes in @sentry/electron@0.15.0 and @sentry/javascript@4.5.x

![image](https://user-images.githubusercontent.com/107841/51338993-23102300-1a40-11e9-8036-78ed2e339769.png)

Can you confirm that this is the type of problem that was addressed?

**Comment by HazAT** [comment]
Yes, we internally had an issue where we did not handle an error gracefully if an error occurred in the transport. Now we do 😄 
Sorry, about the issue in the first place but this should be fixed now 🎉

**Comment by aguynamedben** [comment]
Thanks for confirming @HazAT 👍
