### ISSUE TITLE
What's the best practice for handling uncaught exceptions but still passing them to Sentry?

### ISSUE THREAD

**Issue by aguynamedben** [getsentry/sentry-electron#155]
A user of our app got: `ENOSPC: no space left on device, write` (issue 868195291, feel free to look)

Sentry breadcrumbs and our electron-log breadcrumbs show this happened soon after the user launched our app (app.browser-window-created). `crashed_process` is browser so I think the error happened in the renderer. It's unclear to me if this crashed the app, or caused our main BrowserWindow to fail to launch.

My question is: how can we better handle this error and show a message to the user if their disk is full?

* Should we use [`window.onerror`](https://developer.mozilla.org/en-US/docs/Web/API/GlobalEventHandlers/onerror)?
* Should we use Node.js' [`process.on('uncaughtException`)`](https://nodejs.org/api/process.html#process_event_uncaughtexception)
* If we decide it's a good idea to catch uncaught exceptions ourselves, how to we pass them to Sentry in a manner which preserves all the breadcrumbs, extras, stacktrace, etc.? Will plain ole `Sentry.captureException()` do for catching uncaught exceptions, or is that not advised?

**Comment by gavinkalika** [comment]
has `process.on(uncaughtException)` worked for you? It has not worked for me.
