### ISSUE TITLE
getCurrentHub().lastEventId() always returns undefined

### ISSUE THREAD

**Issue by beheh** [getsentry/sentry-electron#156]
I'm writing my own little User Feedback dialog specifically for errors in the main process at this time, and I'm looking for a way to access the last event id. Specifically, I'm trying to access the event id that is generated by the `OnUncaughtException` integration calling `captureException`:

https://github.com/getsentry/sentry-electron/blob/bbbb8aed6f84434818bbc4c9eeec263a53ef9bf8/src/main/integrations/onuncaughtexception.ts#L40

As far as I'm aware the suggested ways are to either look at the return value of `captureException` (which I'd like to avoid here, as that would mean I would have to write my own integration duplicating `OnUncaughtException`), or looking at `getCurrentHub().lastEventId()`. That last one always returns undefined when calling it from inside the `onFatalError`  callback. I've tried to give the SDK a moment to catch up using `setImmediate`/`setTimeout`, but that hasn't worked.

What's the recommded way to get hold of the eventId?

**Comment by timfish** [comment]
We have just released v3.0.0 of the SDK which includes a lot of changes and improvements since this issue was opened. 

If you can still reproduce this with v3, please open a new issue and I'll look into it.
