### ISSUE TITLE
captureMessage ignores severity parameter

### ISSUE THREAD

**Issue by beheh** [getsentry/sentry-electron#157]
Right now, `captureMessage` seems to ignore the second parameter (severity) and always shows as `Info` in the Sentry web interface and the event JSON:

```typescript
import {captureMessage, Severity} from "@sentry/electron";

captureMessage("My error message", Severity.Error); // will result in an "Info" event
```

I have to use the following code to actually create an `Error` event:

```typescript
import {captureMessage, Severity, withScope} from "@sentry/electron";

withScope(scope => {
  scope.setLevel(Severity.Error);
  captureMessage("My error message");
});
```

**Comment by timfish** [comment]
We have just released v3.0.0 of the SDK which includes a lot of changes and improvements since this issue was opened. 

If you can still reproduce this with v3, please open a new issue and I'll look into it.
