### ISSUE TITLE
Missing stacktrace when using custom protocol in electron

### ISSUE THREAD

**Issue by korob93** [getsentry/sentry-electron#159]
I use @sentry/electron version 0.16.0 with my electron app. I use custom protocol in my app, it looks like this:

```
const mainWindow = new BrowserWindow({
    show: false,
    title: 'My app',
    webPreferences: {
        nativeWindowOpen: true,
        webSecurity: false,
        allowRunningInsecureContent: false,
    },
});
mainWindow.loadURL(`protocol://app/index.html`);
```

When I try to call `captureException` manually in renderer process I get empty stacktrace in my Sentry instance, all errors tell me that the problem is `protocol://app/index.html`. Here is an [example  gist](https://gist.github.com/korob93/4ecec6b1f3ea7f20eff91f025ce4da10) with json event.

My investigations led me [here](https://github.com/getsentry/sentry-javascript/blob/1d8eae19610c461f372580a6ae9596ba1df90866/packages/browser/src/tracekit.ts#L954),to @sentry/browser's tracekit module, function computeStackTraceFromStackProp. When I monkeypatched chrome regexp this way `^\s*at (?:(.*?) ?\()?((?:file|https?|blob|chrome-extension|native|eval|webpack|<anonymous>|[a-z]+:|\/).*?)(?::(\d+))?(?::(\d+))?\)?\s*$` (added plus after `<anonymous>|[a-z]`) I began getting all stacktraces, so my protocol began to be recognized by tracekit module.

So, what I'm to do with this problem? I'm not quite sure, should I open issue here or in sentry-javascript project. but let me start here since it's eletron-speciefic issue.

**Comment by timfish** [comment]
Thanks for reporting this!

From a security standpoint, it is now recommended to use a custom protocol instead of `file://` in Electron.  `file://` can access any files on the users machine and a custom protocol can tightly limit the protocols access to specific directories. For this reason it's going to be important to support this.

@HazAT @kamilogorek what do you thing about this change in `@sentry/browser`?

**Comment by korob93** [comment]
@timfish hello. Sorry for bothering you, but my futher investigation brought me to a conclusion that `normalizeUrl` function in `normalize.ts` module of `@sentry/electron` should be also modified in order to support source-maps properly. For now stacktraces are correctly bound to uploaded source files, but according to [this docs](https://docs.sentry.io/platforms/javascript/electron/sourcemaps/) they are not source-map friendly. Or maybe some misconfiguration from my side =)

Just to make sure my config is ok. My catalog tree looks like this
```
|-webpack.config.js
|-sentry.properties
|+dist
 |+renderer
  |-index.html
  |+static
   |+js
    |-main.js
    |-main.js.map
```
My `protocol://app` points to `dist/renderer` folder, so `protocol://app/index.html` resolves to `dist/renderer/index.html` file and etc. My SentryCliPlugin config is the following:
```
{
  release: 'release',
  include: path.resolve(__dirname, 'dist', 'renderer', 'static', 'js'),
  configFile: path.resolve(__dirname, 'sentry.properties'),
  urlPrefix: '~/static/js',
}
```
Here is the [example gist](https://gist.github.com/korob93/c82021cccd4b62f6c966b0b451804482) of sentry event

So, since my sources and maps are located in the same directory and uploaded with same prefix and  since source files are resolved properly I guess something is wrong with stacktraces. What do you think about that?

**Comment by kamilogorek** [comment]
@timfish I think we can even be more generic, as protocol is inside non-capturing group anyway and change:

```
(?:file|https?|blob|chrome-extension|native|eval|webpack|<anonymous>|[a-z]+:|\/)
```

to just something like:

```
(?:[a-zA-Z]+|chrome-extension|<anonymous>:\/\/)
```

Thoughts @HazAT?

**Comment by timfish** [comment]
The latest `sentry-javascript` uses the following that fixes this:
```
(?:file|https?|blob|chrome-extension|native|eval|webpack|<anonymous>|[-a-z]+:|\/)
```
