### ISSUE TITLE
shouldSend / shouldSendCallback not fired

### ISSUE THREAD

**Issue by tommoor** [getsentry/sentry-electron#163]
I've found different docs that mention either a `shouldSendCallback` or a `shouldSend` option. This previously worked well with using the node client but on moving to the electron client we're no longer seeing the logic in either of these callbacks being triggered.

This is quite critical for us.

**Comment by HazAT** [comment]
We now have an option called `beforeSend` which receives the `event` and a `hint`.
If you return null in `beforeSend` the event will not be send and therefore is equal to `shouldSend` false.
```
Sentry.init({
  beforeSend(event, hint) {
    if(true){
      return null; // this is equal to shouldSend false
    }
    return event;
  }
});
```

**Comment by tommoor** [comment]
I'm still finding that returning `null` from `beforeSend` doesn't prevent the error from being sent to Sentry.
