### ISSUE TITLE
CrashReporter not reporting on Windows

### ISSUE THREAD

**Issue by GeorgS** [getsentry/sentry-electron#165]
I added sentry-electron to my renderer process like so:
```
win = new BrowserWindow(Object.assign({}, WINDOW_CONFIG, {
  webPreferences: {
    preload: path.join(__dirname, 'sentry.js')
  }
}))
```
This is my sentry.js file:
```
const { init } = require('@sentry/electron/dist/renderer');

init({
  dsn: 'XXX',
  enableNative: true,
  environment: process.env.NODE_ENV
})
```

In the main process: 
```
const { init } = require('@sentry/electron/dist/main')
init({
  dsn: 'XXX',
  enableNative: true,
  environment: process.env.NODE_ENV
})
````

On OSX I receive crash reports at sentry.io when I call `process.crash()` from within the DevTools.
On Windows I don't. I have already checked if the crash files are being created and they are.

<img width="812" alt="Screenshot 2019-03-22 at 11 37 50" src="https://user-images.githubusercontent.com/827885/54817338-f7572680-4c96-11e9-85b1-e8ca3fcb7f94.png">
Not sure what I am doing wrong here, would appreciate any hints.

**Comment by HazAT** [comment]
Are you using the latest release `0.17.0`?
We fixed a bug in the upload which might fix this.

**Comment by GeorgS** [comment]
Yes, I am on `0.17.0`.

**Comment by timfish** [comment]
If you set `debug: true` you'll get some debug output which might help:
```
const { init } = require('@sentry/electron/dist/main')
init({
  debug: true,
  dsn: 'XXX',
  enableNative: true,
  environment: process.env.NODE_ENV
})
```

**Comment by GeorgS** [comment]
Thanks for the info @timfish.
All the debug output I am getting is the installation of the integrations:
```
Sentry Logger [Log]: Integration installed: Dedupe
Sentry Logger [Log]: Integration installed: InboundFilters
Sentry Logger [Log]: Integration installed: FunctionToString
Sentry Logger [Log]: Integration installed: ExtraErrorData
Sentry Logger [Log]: Integration installed: Console
Sentry Logger [Log]: Integration installed: Http
Sentry Logger [Log]: Integration installed: OnUnhandledRejection
Sentry Logger [Log]: Integration installed: LinkedErrors
Sentry Logger [Log]: Integration installed: OnUncaughtException
Sentry Logger [Log]: Integration installed: Electron
```

I tested with the example app and got the same behaviour. CrashReports are sent on OSX but not on Windows 10 (1809, build version is  10.0.17763).

**Comment by GeorgS** [comment]
Updating `electron-fetch` to 1.3.0 resolved the issue (https://github.com/GeorgS/sentry-electron). There was a problem importing `fetch` (https://github.com/getsentry/sentry-electron/blob/master/src/main/uploader.ts#L97) and therefore the upload failed. 

I am guessing that this issue is related to my babel/webpack setup tough as "default" was exported using 1.1.0 while there was no default export from the lib itself.

**Comment by HazAT** [comment]
@GeorgS Do you mind opening an PR for this :) ?

**Comment by GeorgS** [comment]
@HazAT sure, will do

**Comment by GeorgS** [comment]
@HazAT could you release a new version?

**Comment by HazAT** [comment]
`0.17.1` has been released
