### ISSUE TITLE
Can't upload Electron 4.1.4 darwin debug symbols to Sentry

### ISSUE THREAD

**Issue by aguynamedben** [getsentry/sentry-electron#168]
This might be more of a sentry-cli issue, but it's related to a new version of Electron symbols so I thought it was more appropriate to ask here.

We recently upgraded from Electron 3->4, and I'm trying to upload the Electron debug symbols  to Sentry but the job is stalling.

My command:
```
$ ./node_modules/.bin/sentry-cli upload-dif -t dsym ~/Downloads/electron-v4.1.4-darwin-x64-dsym.zip --org=my-org --project=my-project
```

![image](https://user-images.githubusercontent.com/107841/55778870-f37a2100-5a58-11e9-8c52-994be112047d.png)

Steps 1-3 progress quickly, but when it gets to 4 it hangs forever (15+ minutes) and the dots by "Searching" just keep spinning.

Any ideas?

**Comment by jan-auer** [comment]
@aguynamedben Is this a separate issue from https://github.com/getsentry/sentry-cli/issues/509?

**Comment by aguynamedben** [comment]
Sorry, yes. I think GitHub was having a bug last night... I created that other ticket, then it was missing from the Issues page, so I recreated it. Closing this one.
