### ISSUE TITLE
Electron 5 debug file is 2.01 GB and is skipped

### ISSUE THREAD

**Issue by audiolion** [getsentry/sentry-electron#169]
Getting a warning from the `sentry-symbols.js` script after I upgraded to `electron@5.0.0`

![image](https://user-images.githubusercontent.com/2430381/57022988-d9b69e80-6bfe-11e9-8c75-c8fbda7326f0.png)

Not sure if this behavior is what we want or not, but I wanted to make you all aware of it at least.

**Comment by ccope** [comment]
I think this is preventing me from viewing Electron framework symbols in the sentry UI?

**Comment by jan-auer** [comment]
Thanks for bumping this issue. The signed integer limit is going to stick for a while, unfortunately.

The good news: You can soon stop to upload debug files as Sentry will pull them automatically. This feature is currently being evaluated and will be available to all customers in a few weeks.

**Comment by audiolion** [comment]
alright I will close off this issue then.

**Comment by mmartinson** [comment]
> The good news: You can soon stop to upload debug files as Sentry will pull them automatically. This feature is currently being evaluated and will be available to all customers in a few weeks.

@jan-auer any updates on this? I'm pretty blocked trying to debug a mysterious crash. 

Does anyone know a way around this limitation while waiting for the debug files to be uploaded?

**Comment by jan-auer** [comment]
We still need some time before we can make this feature GA. I know that this is important to many customers and we are working to get this out as soon as possible.

If you are blocked, you can also upload breakpad symbols of the affected debug file instead. In this case, locate the file `Electron Framework.sym` and upload it directly using `sentry-cli upload-dif`. With these symbols, Sentry will not be able to resolve inline frames, but at least you can get a fully symbolicated stacktrace for your crashes.
