### ISSUE TITLE
Electron should not be in peerDependencies

### ISSUE THREAD

**Issue by timfish** [getsentry/sentry-electron#17]
When creating an electron project, electron it is added to `devDependencies`. This is because the module it's only used when running in development or packaging a production app using `electron-builder` or `electron-packager`.

Including electron in `peerDependencies` means the `electron-builder` or `electron-packager` package electron as a dependency in `node_modules` which means the electron binaries get included twice. 😃

**Comment by kamilogorek** [comment]
This SDK will only ever be run in electron environment anyway. I agree that it's fair to remove it from `peerDependency` completely.
