### ISSUE TITLE
event_id: Discarded invalid value

### ISSUE THREAD

**Issue by o2genum** [getsentry/sentry-electron#170]
## Package + Version

- [ ] `@sentry/electron` 0.17.1

## Description

I'm getting `event_id: Discarded invalid value` error for all events.

Example event: https://sentry.io/share/issue/74208e9488ae4148a85e457ad4cdc014/

Similar stuff in the on-premise version: `Discarded invalid value for parameter 'event_id'`

**Comment by o2genum** [comment]
Reproduced the bug:

https://github.com/o2genum/sentry-electron-event-id-bug-demo

`@sentry/electron` sends `event_id: [undefined]` for some reason.

**Comment by o2genum** [comment]
Cause found!

When [this `clone()` happens](https://github.com/getsentry/sentry-electron/blob/bbbb8aed6f84434818bbc4c9eeec263a53ef9bf8/src/main/normalize.ts#L62), event happens to have a `event_id` property with value `undefined`. After cloning it is transformed into string `[undefined]`. That value is then untouched and is sent to Sentry.

**Comment by o2genum** [comment]
@HazAT I think I can fix this quickly and make a pull request.

I guess the `normalizeEvent()` function just should mutate the event, without cloning anything?

**Comment by jan-auer** [comment]
@o2genum go ahead, much appreciated! Thanks!

**Comment by shawnd** [comment]
Also experiencing this bug after upgrading to release 0.17.1
