### ISSUE TITLE
sentry-electron does not capture unhandled exceptions

### ISSUE THREAD

**Issue by SteinRobert** [getsentry/sentry-electron#172]
Hi guys,

thank you for this amazing product - we're using Sentry a lot and it helps us in a lot of situations.

We recently started using  the `@sentry/electron` version `0.17.1`.

Somehow it does not seem to work as expected 😢 

```js
import * as Sentry from '@sentry/electron'

Sentry.init({
  dsn: '__DSN_PLACEHOLDER__',
  debug: true
})
Sentry.captureException(new Error('This is my fake error message'))
```

This is included pretty early in our `renderer.js`.
The code works fine, the fake error is captured and sent to Sentry.
**However unhandled exceptions are not captured/sent.**

Interesting enough, I changed to `@sentry/browser` (latest) just to test:
```js
import * as Sentry from '@sentry/browser'

Sentry.init({
  dsn: '__DSN_PLACEHOLDER__',
  debug: true
})
Sentry.captureException(new Error('This is my fake error message'))
```

Which works the same except it now captures and sends unhandled exceptions to Sentry. 😲
I tried this with electron `3.1.9` and `4.1.4`. Same behavior. We also tried loading the script  through the `main` process via `preload`. Does not work either.

We'd like to use the electron SDK since it takes care of the path rewriting for source maps 😃  

Let me know if I missed something.

**Comment by timfish** [comment]
You mention loading via preload, but are you also calling `Sentry.init` from the main process too? Everything gets routed via the main process so breadcrumbs can be merged from multiple processes. If you don't call `init` from the main process, nothing will get sent, although it should warn about this in the renderer console.

**Comment by SteinRobert** [comment]
Thank you for the quick response!
The main process contains this:
```
import * as Sentry from '@sentry/electron'
...

Sentry.init({
  dsn: '__DSN_PLACEHOLDER__',
  environment: process.env.NODE_ENV
})
```

The is not warning in the renderer console, just the expected debug output.

**Comment by SteinRobert** [comment]
I managed to fix the issue. I did not mention I was using a the Vue Sentry integration which was actually causing my headaches.

My project is based on https://github.com/SimulatedGREG/electron-vue/

So what I came up with now:

**renderer.js**
```js
const { init, getIntegrations } = require('@sentry/electron')

new Vue({
  components: { App },
  router,
  store,
  template: '<App/>'
}).$mount('#app')

const VueIntegration = getIntegrations().browser.Vue

init({
  dsn: '__DSN__',
  integrations: [new VueIntegration({
    Vue,
    attachProps: true
  })],
  release: '__RELEASE__'
})
```

**main.js**
```js
init({
  dsn: '__DSN__'
})
```

The solution seems straightforward now doesn't it 😄 

This issue was pretty helpful: https://github.com/getsentry/sentry-javascript/issues/2033

I am generating  source maps which are uploaded to Sentry - works like a charm now. Thank you for your amazing product.
