### ISSUE TITLE
eventFromException function is error

### ISSUE THREAD

**Issue by wlk1204** [getsentry/sentry-electron#173]
error: `src/main/backend.ts` `eventFromException` func has one parameter missing.
it can lead to @sentey/node `eventFromException` func to be error.
![image](https://user-images.githubusercontent.com/33086234/59576800-85567800-90f3-11e9-87a9-bd31cd13a348.png)

Eventually lead to problems:
![image](https://user-images.githubusercontent.com/33086234/59576883-e67e4b80-90f3-11e9-95fb-88b931c8c03c.png)

Will that is a problem?

**Comment by timfish** [comment]
We have just released v3.0.0 of the SDK which includes a lot of changes and improvements since this issue was opened. 

If you can still reproduce this with v3, please open a new issue and I'll look into it.
