### ISSUE TITLE
Crash reading corrupt minidump from previous session [win32]

### ISSUE THREAD

**Issue by danni** [getsentry/sentry-electron#174]
I haven't totally narrowed this down yet but it appears possible to create a minidump that crashes in Sentry when you try to read it back the next time you init.

This has been reliably reproducible on Electron 4.2.x with the latest Sentry/Electron. It looks like a null-pointer dereference inside v8.

Removing the files, or running Sentry/Electron with `enableNative: false` appears to work around the issue.

**Comment by danni** [comment]
Struggling to symbolicate the crash it causes... I think it's a null pointer dereference.

[resulting-crash.dmp.zip](https://github.com/getsentry/sentry-electron/files/3299913/2db8da35-6459-4ad8-92a1-b217c063a4dd.dmp.zip)

**Comment by KASOGIT** [comment]
Same here on electron 7.0, my app segv on startup when reaching Sentry.init after a crash

**Comment by hxkuc** [comment]
i have same problem

**Comment by hxkuc** [comment]
big bug

**Comment by davej** [comment]
Also experiencing this.

**Comment by timfish** [comment]
We have just released v3.0.0 of the SDK which includes a lot of changes and improvements since this issue was opened. 

If you can still reproduce this with v3, please open a new issue and I'll look into it.
