### ISSUE TITLE
URI malformed error in normalizeEvent

### ISSUE THREAD

**Issue by timfish** [getsentry/sentry-electron#175]
I've started seeing a few of these since upgrading to 0.17.x

![image](https://user-images.githubusercontent.com/1150298/60712315-a0f0b980-9f0e-11e9-8181-567ddacbb316.png)

**Comment by yafp** [comment]
@timfish 
as i am seeing similar issues in one of my projects: have you found a solution or workaround for that?

what version are you currently using?
