### ISSUE TITLE
Electron 7 crashes on Sentry.init 

### ISSUE THREAD

**Issue by ranihorev** [getsentry/sentry-electron#192]
Updated Electron to 7.1.0 and since then the app crashes the moment `Sentry.init` is called. Does Sentry support that version?

Thanks

**Comment by HazAT** [comment]
We didn't run any tests with Electron 7 yet but thanks for highlighting it doesn't work.
We will take a look.

**Comment by ranihorev** [comment]
If you could let me know if there is a bug (even before fixing it), that would be great. I'm currently considering alternatives, but I'd love to keep using Sentry.

**Comment by timfish** [comment]
I've tested the included example app with `electron@7.1.1` and the app does not crash on init.

Can you give some reproduction steps? An example repository would help!

**Comment by ranihorev** [comment]
When you open the app for the first time it works just fine. It starts crashing only when you try to open it after the first crash. If you clear the `App crashes` folder, then it works again.
I should've mentioned that before, sorry...

**Comment by timfish** [comment]
When testing 7.1.1 I can see that Electron is now writing dump files to a `reports` directory that it never did before so they will not be uploaded but I still can't get the app to crash:

![image](https://user-images.githubusercontent.com/1150298/68901700-4eca6b00-072e-11ea-8365-6113d56e82a3.png)

**Comment by timfish** [comment]
Electron on Windows started using crashpad at v6. 

I've created a branch which ensures that on these versions it now uses the crashpad logic which fixes sentry on v6 but there are still issues with v7 related to `electron-fetch`:
https://github.com/arantes555/electron-fetch/issues/17

I've tried `electron-fetch@1.4.0` which was released a few hours ago but still no luck so it might be time to replace that dependency as it has broken things before.

**Comment by ranihorev** [comment]
If I understand correctly - you were able to make the app crash but you found out that it doesn't send any errors to sentry on Windows. 
I forgot to mention that I'm on Mac (10.15.1) but it also crashed on Windows last time I checked. 
We'll also try running electron with a debugger and narrow down the issue.

Thanks for looking into this!

**Comment by timfish** [comment]
The issues with `electron-fetch` and Electron v7 affected all platforms.

**Comment by momakes** [comment]
@timfish I think this affects a lot of people (as you can see the electron/electron#21240), it'd be awesome if you could move it to stable channel sooner imho 🙌🧡

**Comment by yafp** [comment]
i can fully confirm the behaviour @ranihorev described (using sentry 1.0.0).
In my case it did happen with electron 7.1.1 and 7.1.2

After upgrading to the sentry 1.1.0-beta.0 the problem was solved.

Please see https://github.com/electron/electron/issues/21240
