### ISSUE TITLE
Usages of app.getName() display warning in Electron v7

### ISSUE THREAD

**Issue by timfish** [getsentry/sentry-electron#193]
[`app.getName()`](https://github.com/getsentry/sentry-electron/blob/ce9750f6ab9ac1f4277eb7a113a5bbc9d2e635d4/src/main/context.ts#L220) is deprecated in Electron v8 and displays warnings on v7.

We'll need to cater for both!

**Comment by flesicek** [comment]
Is it possible to prioritize this issue? we are experiencing it as well

**Comment by HazAT** [comment]
Should be fixed with `1.1.0`
