### ISSUE TITLE
Discussion: Excessive use of remote / ipc

### ISSUE THREAD

**Issue by tommoor** [getsentry/sentry-electron#197]
The `sentry/electron` module appears to send an `ipc` message for every single console log that occurs in every browser window, as well as [other browser window events](https://github.com/getsentry/sentry-electron/issues/181). 

The core electron team has been advising against the use of `remote` for a while, and recently formalized this advice: https://medium.com/@nornagon/electrons-remote-module-considered-harmful-70d69500f31

I'd consider the amount of remote/ipc messages that the sentry module ends up introducing as problematic as Electron is already a slower environment than Chromium. Perhaps it would be worth thinking about a batching strategy?

![image](https://user-images.githubusercontent.com/380914/68973760-f2099780-07a3-11ea-86c7-328ab1142123.png)

**Comment by crussell52** [comment]
@tommoor That particular blog post is about the evils of `remote` specifically.  Is the sdk, aggressively using `remote` by your estimate or just `ipc.send()`?

I think I've read that over use of ipc.send can cause problems too though... **iirc**, there are important messages that the renderer needs to send to main and if the ipc channel is too noisy, those become laggy.  (open to corrections on that point -- can't find the specific article I read)

In any case, thanks for bringing it up... I'm just implementing Sentry w/ electron for the first time, so this is good to mindful of. Might make sense to turn off the default `Console` integration for apps that have a front end that likes to send a lot of console messages.

**Comment by timfish** [comment]
As @crussell52 says, the recommendation is to not use `remote` module. There is nothing wrong with using IPC and this is the recommended way to send data between the Electron processes. 

Using IPC is only problematic if you send large amounts of data as it has to be serialised before sending so `sentry-electron` does not do this. `sentry-electron` uses `ipc.send` which is async and does not block the process. Using `ipc.sendSync` blocks both processes and is generally bad so it's not used.

@tommoor in your recorded timeline, how long does the `send` take?

**Comment by tommoor** [comment]
Hey @timfish thanks for the additional context, I think we can close this out but I'd like to mention that if you're sending console log messages across is there an attempt to reduce the size of that payload?

I've also noticed that in the case of the sentry `scope` ipc message a function is getting serialized which is producing warnings in Electron 8 upwards, I can file a separate issue for this though.

**Comment by timfish** [comment]
Using Electron IPC only becomes an issue if you're sending multi-megabyte sized JavaScript objects as the serialisation time is blocking and it can disrupt communication between the renderer and GPU process. Usage in `sentry-electron` would only become a problem I you're doing something strange like passing huge objects to `console`. 

Some quick debugging shows that an average console message takes about 60 microseconds to send over IPC to the main process on my machine so this is not something you should be too concerned about. Anything you could do to reduce the size of this message would increase this time.

> I've also noticed that in the case of the sentry scope ipc message a function is getting serialized which is producing warnings in Electron 8 upwards, I can file a separate issue for this though.

Yes, please open an issue. I've not tested Electron 8 much yet.

**Comment by timfish** [comment]
The single usage of `remote` in `sentry-electron` is [here](https://github.com/getsentry/sentry-electron/blob/70cdcef280f9455d65a9b4b483db45894cd614df/src/renderer/backend.ts#L101). It's used to get the application name which is used by electron native crash reporter to name the crashes directory.

I think the best way allow usage without `remote` but keep the current convenience of the current setup would be to add an optional `appName` property to [`ElectronOptions`](https://github.com/getsentry/sentry-electron/blob/70cdcef280f9455d65a9b4b483db45894cd614df/src/common.ts#L53). 
If the user supplies this property, `sentry-electron` will use it and if none is supplied, it'll fallback to `remote.app.name/getName()`. If it reaches the fallback and `remote` is not available, there will be an error with a pointer to `ElectronOptions.appName`. I'll post a PR in a moment.
