### ISSUE TITLE
Huge amount of breadcrumbs

### ISSUE THREAD

**Issue by ghost** [getsentry/sentry-electron#205]
Current `"@sentry/electron": "1.1.0"` is sending unlimited amount of breadcrumbs:
![image](https://user-images.githubusercontent.com/56207736/71427328-8e3e8c80-26c8-11ea-8470-a5746a9e1c16.png)

I'm using Electron 6.1.5, and I'm using Sentry from the main and two renderer processes.

**Comment by kr-deps** [comment]
Rolled back to `"@sentry/electron": "0.17.3"`, sends only 21 breadcrumbs now as it used to.

**Comment by mateo-io** [comment]
I can confirm.

I develop a big electron app and the latest Sentry was causing big performance problems. Downgrading to `0.17.3` and they are no longer noticeable.

**Comment by williamweckl** [comment]
Anyone knows if this is still happening?

**Comment by williamweckl** [comment]
I think this is releated to #277. I've tested here and don't think this is still happening.
