### ISSUE TITLE
How to disable or unload sentry?

### ISSUE THREAD

**Issue by yafp** [getsentry/sentry-electron#207]
- [ x ] Review the documentation: https://docs.sentry.io/platforms/javascript/electron/
- [ x ] Search for existing issues: https://github.com/getsentry/sentry-electron/issues
- [ x ] Use the latest release: https://github.com/getsentry/sentry-electron/releases
- [ ] Provide a link to the affected event from your Sentry account

## Versions + Platform

- [ ] SKD version - `@sentry/electron@v1.1.0
- [ ] Electron version - `electron@v7.1.7
- [ ] Platform - `Linux`

## Description

How to disable sentry which was enabled on app start (reference implementation: https://github.com/getsentry/sentry-electron/tree/master/example )

Background: 
i wan't my users to be able to disable error-reporting if they want to (DSGVO).
This user preference will be stored in a json file and loaded on start or when the user changes the setting.

**Comment by yafp** [comment]
Any chance its similar to here?

https://github.com/getsentry/sentry-javascript/issues/2039

**Comment by yafp** [comment]
`Sentry.getCurrentHub().getClient().getOptions().enabled = false;`

seems to work for sentry-electron as well.
Might be worth adding it to the docs.

**Comment by HazAT** [comment]
Thanks for highlighting, we might consider adding a better API for this.

**Comment by timfish** [comment]
> Sentry.getCurrentHub().getClient().getOptions().enabled = false;

I'm not sure whether doing this will currently also disable native reporting too.

**Comment by HazAT** [comment]
It at least prevents the SDK from sending anything (which is the important part I guess)

**Comment by morrigan** [comment]
> `Sentry.getCurrentHub().getClient().getOptions().enabled = false;`
> 
> seems to work for sentry-electron as well.
> Might be worth adding it to the docs.
`Cannot read property 'getCurrentHub' of undefined`. Both in main and renderer process. 
My Import looks like this: `import Sentry from "@sentry/electron";` and types seem to be fine.

Unfortunately, this is still a valid issue.

**Comment by timfish** [comment]
The best way to disable reporting is to hook `beforeSend` and return null if you don't want anything sent. 

v3 of the Electron SDK (currently in beta) now respects `beforeSend` for native crashes too.  

In the main process:
```ts
import { init } from '@sentry/electron';

let reportingEnabled = true;

init({
  dsn: '__DSN__',
  beforeSend: (event) => reportingEnabled ? event : null
});
```
