### ISSUE TITLE
Sentry not report any error in my spawn process

### ISSUE THREAD

**Issue by Leaking** [getsentry/sentry-electron#208]
## Versions + Platform

- [ ] SKD version - `@sentry/electron@v1.1.0`
- [ ] Electron version - `electron@v7.1.2`
- [ ] Platform - `Windows & macOS`

## Description

I fork a child process from my main process, and init the sentry in my child process, but it can't report any error heppened in child process,

```
import * as SentryNode from '@sentry/electron'

SentryNode.init({
     dsn: dsn,
     release: packageJSON.version
})

```

**Comment by timfish** [comment]
We have just released v3.0.0 of the SDK which includes a lot of changes and improvements since this issue was opened. 

If you can still reproduce this with v3, please open a new issue and I'll look into it.
