### ISSUE TITLE
Critical dependency: require function is used in a way in which dependencies cannot be statically extracted

### ISSUE THREAD

**Issue by darthzeran** [getsentry/sentry-electron#211]
- [ ] SKD version - `@sentry/electron@v1.2.0`
- [ ] Electron version - `electron@v4.2.8`
- [ ] Platform - `Windows10/64bit`

## Description
I am getting an error in `./node_modules/@sentry/electron/dist/common.js `
saying  `Critical dependency: require function is used in a way in which dependencies cannot be statically extracted`

Um I just upgraded Sentry electron, ran it, and the warning appeared in my console.
Is this because of the other webpack issue that I found when googling this warning on google?

**Comment by timfish** [comment]
Yes, I get this too, although it's only a warning from webpack and it doesn't affect compilation or runtime behaviour.

I'll look into it as it should be easy to fix.

**Comment by GrzegorzZajac000** [comment]
@timfish Any new info about this warning?

**Comment by timfish** [comment]
Yes, I've worked out a fix for this. PR incoming next week.

**Comment by pdesantis** [comment]
Thanks so much!
