### ISSUE TITLE
Sentry is sending non-cloneable JavaScript objects through IPC

### ISSUE THREAD

**Issue by astutejoe** [getsentry/sentry-electron#214]
Electron 8 started throwing deprecation warnings for IPC method calls that have non-cloneable JavaScript objects as params. This is so they can move to a more efficient serializer from the V8 engine.

You can check more details in here:
https://github.com/electron/electron/pull/20214

From my investigations, Sentry is sending such non-cloneable objects at the following lines:
https://github.com/getsentry/sentry-electron/blob/master/src/renderer/backend.ts#L51
https://github.com/getsentry/sentry-electron/blob/master/src/renderer/backend.ts#L61

It still works on Electron 8, with deprecation warnings, and will stop working on Electron 9 according to their roadmap.

Personal note: I HATE when I have deprecation warnings in my application.

Thanks!

**Comment by timfish** [comment]
Thanks for the heads up!
