### ISSUE TITLE
Cannot read property 'Symbol(Symbol.iterator)' of undefined

### ISSUE THREAD

**Issue by MisterTaki** [getsentry/sentry-electron#216]
- [x] Review the documentation: https://docs.sentry.io/platforms/javascript/electron/
- [x] Search for existing issues: https://github.com/getsentry/sentry-electron/issues
- [ ] Use the latest release: https://github.com/getsentry/sentry-electron/releases
- [ ] Provide a link to the affected event from your Sentry account

## Versions + Platform

- [x] SKD version - `@sentry/electron@v1.1.0`
- [x] Electron version - `electron@v4.2.12`
- [x] Platform - `Windows`

## Description

hello, I'm using @sentry/electron package, but looks like 'breadcrumbs' property is undefined when
sentry/electron's ipc-scope clone.

![WechatIMG143](https://user-images.githubusercontent.com/15980621/74296475-ee73b580-4d7e-11ea-8e07-3ab0ca7b6975.jpeg)

**Comment by MisterTaki** [comment]
Another TypeError: Cannot convert undefined or null to object

![WechatIMG148](https://user-images.githubusercontent.com/15980621/74619627-1f822a80-5171-11ea-9bd0-b425e2e01259.jpeg)

**Comment by timfish** [comment]
We have just released v3.0.0 of the SDK which includes a lot of changes and improvements since this issue was opened. 

If you can still reproduce this with v3, please open a new issue and I'll look into it.
