### ISSUE TITLE
Cannot read property 'Symbol(Symbol.iterator)' of undefined

### ISSUE THREAD

**Issue by MisterTaki** [getsentry/sentry-electron#217]
- [x] Review the documentation: https://docs.sentry.io/
- [x] Search for existing issues: https://github.com/getsentry/sentry-javascript/issues
- [ ] Use the latest release: https://github.com/getsentry/sentry-javascript/releases
- [ ] Provide a link to the affected event from your Sentry account

## Package + Version

- [x] `@sentry/browser`
- [x] `@sentry/node`
- [ ] `raven-js`
- [ ] `raven-node` _(raven for node)_
- [x] other: `@sentry/electron`

### Version:

```
5.10.2
```

## Description

hello, I'm using @sentry/electron package, but looks like 'breadcrumbs' property is undefined when 
sentry/electron's ipc-scope clone.

![WechatIMG143](https://user-images.githubusercontent.com/15980621/74296046-c5065a00-4d7d-11ea-8145-dcd7603ac048.jpeg)

**Comment by HazAT** [comment]
Dupe https://github.com/getsentry/sentry-electron/issues/216

**Comment by zhaoxiaolei519109457** [comment]
Hey, how did you deal with it later? I have the same problem
