### ISSUE TITLE
NormalizeDepth not supported?

### ISSUE THREAD

**Issue by delewis13** [getsentry/sentry-electron#221]
Currently using [redux-sentry-middleware](https://github.com/vidit-sh/redux-sentry-middleware) to add redux state to my breadcrumbs. 

In order to get information for nested state, it was suggested in other forums that I supply 'normalizeDepth' parameter in the Sentry init.

Did this with the electron-SDK, didn't work. Works however for @sentry/browser SDK.

## Versions + Platform

- SKD version - @sentry/electron@v1.3.0
- Electron version - `electron@v7.1.7
- Platform - MacOS

**Comment by timfish** [comment]
We have just released v3.0.0 of the SDK which includes a lot of changes and improvements since this issue was opened. 

If you can still reproduce this with v3, please open a new issue and I'll look into it.
