### ISSUE TITLE
Could not connect to Sentry main process. Did you call init?

### ISSUE THREAD

**Issue by yanlee26** [getsentry/sentry-electron#222]
`
Could not connect to Sentry main process. Did you call init?
`

But I did init it !!

**Comment by rwwagner90** [comment]
Same issue here. Any suggestions?

**Comment by mishkinf** [comment]
+1

**Comment by timfish** [comment]
Could anyone supply a simplified example to reproduce this?

**Comment by rwwagner90** [comment]
@timfish in our case we have a preload script that looks like this:

```js
const { remote } = require('electron');
const Sentry = require('@sentry/electron');

Sentry.init({
  dsn: 'xxxxxxxxxxx' // redacted this in case it's bad to share out sentry ids.
});

if (process.platform === 'darwin') {
  const { nativeTheme, systemPreferences } = remote;

  const setOSTheme = () => {
    let theme = nativeTheme.shouldUseDarkColors ? 'dark' : 'light';
    remote.getCurrentWindow().send('setTheme', theme);
  };

  systemPreferences.subscribeNotification(
    'AppleInterfaceThemeChangedNotification',
    setOSTheme
  );

  setOSTheme();
}
```

And the preload script is called when creating the BrowserWindow:

```js
    webPreferences: {
      contextIsolation: false,
      preload: join(__dirname, 'preload.js'),
      nodeIntegration: true
    }
```

**Comment by timfish** [comment]
And you are also calling `Sentry.init({ .. })` early in the Electron main process?

**Comment by rwwagner90** [comment]
@timfish no, it's just in the preload script I pasted above. I thought it was supposed to go in a preload script?

**Comment by timfish** [comment]
An Electron app is made up of at least 2 node processes. The `main` process and a `renderer` process for each Electron window. `@sentry/electron` collects and merges events from all renderers in the `main` process so you need to call `init` there too. 

I'll submit a PR to improve the above error message to be more clear.

https://docs.sentry.io/error-reporting/quickstart/?platform=electron#configure-the-sdk

![image](https://user-images.githubusercontent.com/1150298/82577122-70dff280-9b82-11ea-918b-01f66878cbfa.png)

**Comment by rwwagner90** [comment]
@timfish so it should be in the main file **and** the preload file? I can give that a try. I swear I read somewhere to put it in a preload script, but maybe I didn't.

**Comment by rwwagner90** [comment]
Calling it twice does seem to fix the console warning. We'll see if it logs errors now!

**Comment by terminatorheart** [comment]
> An Electron app is made up of at least 2 node processes. The `main` process and a `renderer` process for each Electron window. `@sentry/electron` collects and merges events from all renderers in the `main` process so you need to call `init` there too.
> 
> I'll submit a PR to improve the above error message to be more clear.
> 
> https://docs.sentry.io/error-reporting/quickstart/?platform=electron#configure-the-sdk
> 
> ![image](https://user-images.githubusercontent.com/1150298/82577122-70dff280-9b82-11ea-918b-01f66878cbfa.png)

after so many people ask question related to this, may be give a more clear demo is necessary
