### ISSUE TITLE
renderer source map issue + works-for-me fix

### ISSUE THREAD

**Issue by jessedp** [getsentry/sentry-electron#225]
- [X] Review the documentation: https://docs.sentry.io/platforms/javascript/electron/
- [X] Search for existing issues: https://github.com/getsentry/sentry-electron/issues
- [X] Use the latest release: https://github.com/getsentry/sentry-electron/releases
- [X] Provide a link to the affected event from your Sentry account
https://sentry.io/organizations/jessedp/issues/1629926466/?project=5208692

## Versions + Platform

- [X] SDK version - `@sentry/electron@v1.3.0`
- [X] Electron version - `electron@v8.2.3`
- [X] Platform - All

## Description
The few steps to get events into Sentry were a breeze. Using @sentry/webpack-plugin v1.10.0 got the source maps there (apologies if this should be filed there). With both, I used the standard suggested configs (dsn/org/project/release here).

Sourcemaps in the main process (main.prod.js for me) worked perfectly without changing anything. The artificat in the Release is listed as  `~/app/main.prod.js(.map)`

The extra **app** seems weird as I've read that "~/" is shorthand to remove the protcol (app:// here).

The renderer process appears in the release artifacts as  `~/app/dist/renderer.prod.js(.map)`

Same extra **app** , though they are properly in the **dist** subdir.

In the GUI, the event shows 1 error (Source code was not found) saying it is looking for `app:///dist/renderer.prod.js`. Once I made it look for `app:///app/dist/renderer.prod.js` things worked correctly.

My fix was another one adding `beforeSend` to the init properties, though not one I'd found other places. Here's what worked for me:

```
  init({
    ...
    beforeSend(event) {
      if (
        !event.exception ||
        !event.exception.values ||
        !event.exception.values[0]
      ) {
        return event;
      }

      const value = event.exception.values[0];

      if (value.stacktrace && value.stacktrace.frames) {
        value.stacktrace.frames.forEach(frame => {
          if (frame.filename.includes('dist/')) {
            // this is stupid, but it seems to work for now @sentry/electron: 1.3.0
            frame.filename = frame.filename.replace('dist/', 'app/dist/');
            // for some reason the doubled up app/ , so fix the
            frame.filename = frame.filename.replace('app/app/', 'app/');
          }
        });
      }

      return event;
    }
  });
```

Is this expected behaviour and something that should be necessary? If no, is it even an issue in this pacakge?

**Comment by timfish** [comment]
We have just released v3.0.0 of the SDK which includes a lot of changes and improvements since this issue was opened. 

If you can still reproduce this with v3, please open a new issue and I'll look into it.
