### ISSUE TITLE
Add tslib in dependencies

### ISSUE THREAD

**Issue by xiaoxiangmoe** [getsentry/sentry-electron#227]
- [x] Review the documentation: https://docs.sentry.io/platforms/javascript/electron/
- [x] Search for existing issues: https://github.com/getsentry/sentry-electron/issues
- [x] Use the latest release: https://github.com/getsentry/sentry-electron/releases
- [x] Provide a link to the affected event from your Sentry account

## Versions + Platform

- [ ] SKD version - `@sentry/electron@v1.3.0`
- [ ] Electron version - `electron@v5.0.13`
- [ ] Platform - `Windows/macOS/Linux`

## Description

`@sentry/node` has tslib in dependencies.
`const tslib_1 = require("tslib");` exists in dist of `@sentry/electron` . 
Please add tslib in dependencies, also.

**Comment by xiaoxiangmoe** [comment]
@HazAT any updates?

**Comment by HazAT** [comment]
Oh sorry, missed that one will be fixed in the next patch.

**Comment by xiaoxiangmoe** [comment]
@HazAT When will next patch release? Also, can you update typescript to 3.9 and tslib to 2.0?
