### ISSUE TITLE
Issues with Vue integration @ render

### ISSUE THREAD

**Issue by ton77v** [getsentry/sentry-electron#243]
## Versions + Platform

- [ ] SDK version - `@sentry/electron@v1.3.1`
- [ ] Electron version - `electron@v5.0.0`
+ vue-cli-plugin-electron-builder 1.4.6
- [ ] Platform - `Windows 10`

## Description

I am following the guide:
https://docs.sentry.io/error-reporting/quickstart/?platform=electron#configure-the-sdk
https://docs.sentry.io/platforms/javascript/electron/

Since I use Webpack, I import { init } to prevent "TypeError: mod.require..."

It works well at the main process (background.js). Although I had a warning about "the request of a dependency is an expression" for iconv-loader I could fix that.
All the Exceptions are handled at main process and everything works great.

The render is another story 🙃

Seems that the best way to import is the same:
```
import * as Sentry from '@sentry/electron'
import { Vue as VueIntegration } from '@sentry/integrations'

const { init } = (process.type === 'browser')
  ? require('@sentry/electron/dist/main')
  : require('@sentry/electron/dist/renderer')

init({
  dsn: ........,
  integrations: [new VueIntegration({ Vue, attachProps: true })]
})
```

It allows to send events/errors/etc manually, but there are two problems:

1. The Dev Tools show all the console.* entries from 'instrument.js' instead of the ComponentName.vue | ScriptName.js as it used to be
2. Exceptions are not handled, i.e. say "myUndefinedFunction();" error won't be posted to Sentry from render process

Is there a way to fix these? For now I just disabled Sentry integration @ remder and use RPCmessages to report the issues I need from the main process

But maybe there's another way? Thanks!

**Comment by timfish** [comment]
The [latest beta release](https://www.npmjs.com/package/@sentry/electron/v/1.4.0-beta.0) uses the `main` and `browser` entries in `package.json` so Webpack and other bundlers should Just Work™ correctly in the main and renderer processes without having to do the `(process.type === 'browser')` detection.

```typescript
import { init } from '@sentry/electron';
 
init({
  dsn: '__DSN__',
  // ...
});
```

**Comment by ton77v** [comment]
> The [latest beta release](https://www.npmjs.com/package/@sentry/electron/v/1.4.0-beta.0) uses the `main` and `browser` entries in `package.json` so Webpack and other bundlers should Just Work™ correctly in the main and renderer processes without having to do the `(process.type === 'browser')` detection.
> 
> ```ts
> import { init } from '@sentry/electron';
>  
> init({
>   dsn: '__DSN__',
>   // ...
> });
> ```

Thanks, that's handy. Just Work™ indeed =)

Regarding the issues I mentioned, it's all the same at the render process

**Comment by timfish** [comment]
Closing this issues since it sounds like the v3 beta fixes your issue. Please open new issues for anything further.
