### ISSUE TITLE
'crashed' event is deprecated as of Electron 8.4

### ISSUE THREAD

**Issue by jleongDialpad** [getsentry/sentry-electron#246]
## Versions + Platform

- [ ] SDK version - `@sentry/electron@v1.3.0`
- [ ] Electron version - `electron@v8.4.0`
- [ ] Platform - `Windows/macOS/Linux`

## Description

Electron 8.4.0 has deprecated the 'crashed' event in favour of 'render-process-gone'. The new event gives finer detail over why the render process disappeared
```
Added new render-process-gone event on app to replace the renderer-process-crashed event. #24314
Added new render-process-gone event to replace the crashed event. #24308
```

https://www.electronjs.org/releases/stable?version=8#release-notes-for-v840

Notes of deprecation:
https://www.electronjs.org/docs/api/web-contents#event-crashed-deprecated
> This event is superceded by the render-process-gone event which contains more information about why the render process dissapeared. It isn't always because it crashed. The killed boolean can be replaced by checking reason === 'killed' when you switch to that event.

Current sentry-electron version handle the event here:
https://github.com/getsentry/sentry-electron/blob/d20053d89391c56dabcfba07e349f1c48466f90c/src/main/backend.ts#L216

To support older and present versions the proposed update would be to handle both crashed and render-process-gone event here.

**Comment by HazAT** [comment]
We will fix this in the next version :)
