### ISSUE TITLE
BeforeSend not tirgger when process crash

### ISSUE THREAD

**Issue by callmeguaishu** [getsentry/sentry-electron#249]
When I use the official example demo, 'BeforeSend' will be trigger when throw an error, but not working when process crash. Is it correct ?

**Comment by timfish** [comment]
If you have a native crash in the main process, the process terminates and no more code is executed so this would be expected.

If you have a native crash in a renderer process, the main process should continue and `beforeSend` should be called.

**Comment by callmeguaishu** [comment]
y

> If you have a native crash in the main process, the process terminates and no more code is executed so this would be expected.
> 
> If you have a native crash in a renderer process, the main process should continue and `beforeSend` should be called.

I crete a snetry instance in main process and another sentry instance in a renderer process, when renderer process crash, beforeSend(sentry instance in renderer process) not working, you mean that time, main process beforeSend will be called?

**Comment by callmeguaishu** [comment]
![image](https://user-images.githubusercontent.com/22768593/89882482-7ab14900-dbf9-11ea-9fec-4f96c1938cf0.png)

just like this, I use office example, add beforeSend function in sentry.js to print event hint, and click renderer process crash, main terminal didn't show event hint, just find mini dump and upload. click main error or renderer error is in line with expectation

**Comment by vyunikov** [comment]
The same is true for `addGlobalEventProcessor`, handler passed to it doesn't seem to be called if process crashes, though it works in cases when exception is thrown. Based on SDK docs, this handler is expected to get called in case of the crash either:
https://docs.sentry.io/platforms/javascript/guides/electron/enriching-events/attachments/#uploading-attachments

**Comment by theicfire** [comment]
I've run into the same issue. I think what @timfish mentioned is not correct. When the electron process restarts, it looks for any minidump files to send, and then sends them. But `beforeSend` isn't called.

It looks like the code is doing this on purpose in `captureMinidump`, but I don't know why:
```
    // We are not calling _processEvent here since we do not have beforeSend for minidump crashes
    this._prepareEvent(event, scope, undefined).then(
```

Note that in `sentry-javascript`, `_processEvent` is where `beforeSend` is called. So it looks like this is skipped.

Is there a reason why `beforeSend` is being skipped in `captureMinidump`?

**Comment by timfish** [comment]
Fixed in v3
