### ISSUE TITLE
Sending uncompressed crash reports is deprecated

### ISSUE THREAD

**Issue by ahallicks** [getsentry/sentry-electron#262]
- [x] Review the documentation: https://docs.sentry.io/platforms/javascript/electron/
- [x] Search for existing issues: https://github.com/getsentry/sentry-electron/issues
- [x] Use the latest release: https://github.com/getsentry/sentry-electron/releases
- [ ] Provide a link to the affected event from your Sentry account *n/a*

## Versions + Platform

- [x] SDK version - `@sentry/electron@v2.0.0`
- [x] Electron version - `electron@v10.0.0`
- [x] Platform - `Windows`

## Description

Accordingly in https://github.com/electron/electron/pull/23598 every time I run my app with the newly updated electron (v10.0.0) I get a deprecation warning that sending uncompressed crash reports is deprecated.

**Comment by ahallicks** [comment]
Hey @theArina. I am currently using `electron` v10.1.1 and `@sentry/electron` v2.0.0 and don't get any crashes. just that deprecation warning I mentioned above.

**Comment by HazAT** [comment]
This will be fixed with https://github.com/getsentry/sentry-electron/pull/260
once released
