### ISSUE TITLE
Unable to load preload script:

### ISSUE THREAD

**Issue by zhaoxiaolei519109457** [getsentry/sentry-electron#270]
## Versions + Platform

- [ ] SDK version - `@sentry/electron@v1.3.0`
- [ ] Electron version - 5.0.8
- [ ] Platform - Windows

## Description

When I use this version, I find that I can't import. But I can't upgrade the node version yet. I want to ask if there is a solution. Const {init} = require ('@ sentry / electron'); if used in this way, there will be a warning could not connect to sentry main process. Did you call init?

**Comment by terminatorheart** [comment]
may be you understand chinese;
当你在preload中集成sentry时，有两点需要注意：
1. 不能使用es6 module的语法，原因时electron中的preload脚本只能支持commonjs规范的模块语法，所以你需要写成如下的形式：
```
const { remote } = require('electron');
const Sentry = require('@sentry/electron');
```  
2. sentry需要init两次，一次在main进程中，一次在preload脚本中

从你上述描述看，应该是main进程中没有调用init方法

**Comment by timfish** [comment]
The latest version of `@sentry/electron` is 2.4.1 so I'm going to close this as stale and probably fixed but feel free open a new issue if the problem persists.
