### ISSUE TITLE
Memory leak: breadcrumbs accumulating

### ISSUE THREAD

**Issue by o2genum** [getsentry/sentry-electron#277]
The buggy line:
https://github.com/getsentry/sentry-electron/blob/942b1f21da743a975701bed46b8d1603c9d7193e/src/main/backend.ts#L309

The call needs the second argument `maxBreadcrumbs`. Currently breadcrumbs can accumulate endlessly through this particular call.

I'll submit a PR if I find out how to get `maxBreadcrumbs` from there.

**Comment by williamweckl** [comment]
Is this still happening?

**Comment by williamweckl** [comment]
I've tested here with a routine adding breadcrumbs every second. Kept my application running for 5 hours and was not able to see any memory issues.

I'm using version 2.1.0 of @sentry/electron.

Maybe this has been solved.

**Comment by o2genum** [comment]
My memory of this bug is blurry, but what I still remember:
1. The breadcrumbs accumulate either in renderer or in main process (I think in main process, breadcrumbs re-sent through IPC from renderer, accumulate).
2. Once in a while a breadcrumb from the renderer (or main process?) comes and resets accumulated breadcrumbs, "fixing" the bug.
3. The function call I quoted is the culprit, it lacks MAX argument and allows for infinite breadcrmb accumulation. In master branch, this function call is untouched.

**Comment by o2genum** [comment]
Also I think a dirty fix like this worked for me.
```
scope.addBreadcrumb(sentScope._breadcrumbs.pop(), 100);
```

But I was unsure how to obtain a proper MAX value from the surrounding code.
Again, the call simply lacks the argument that should be present.

If I'm not confusing anything, the bug occured when app window was hidden (hence renderer sent no breadrumbs, hence not remediating the bug by resetting the growing breadcrumb list).
