### ISSUE TITLE
Renderer Backend will not work without access to ipcRenderer

### ISSUE THREAD

**Issue by hibearpanda** [getsentry/sentry-electron#279]
Electron's security [documentation](https://www.electronjs.org/docs/tutorial/security) suggest setting:
- `nodeIntegration` to false
- `contextIsolation` to true
- using `contextBridge` (https://www.electronjs.org/docs/api/context-bridge, https://stackoverflow.com/a/57656281/6319004)

The sentry client for the renderer directly `requires` `ipcRenderer` (https://github.com/getsentry/sentry-electron/blob/master/src/renderer/backend.ts#L5) as a way to send events to the main process, but with the suggested security settings, this would not be possible (`ipcRenderer` wouldn't be available in the renderer process).

Are there any plans to allow us to use sentry in the renderer process without exposing `ipcRenderer` directly?

If not, would it be possible for us to submit a PR for this?

**Comment by timfish** [comment]
Last night I was working on a PR for exactly this which exposes IPC through `contextBridge` when context isolation is enabled. 

It's not a simple change because `@sentry/electron` still needs to work with context isolation disabled and in versions of Electron before context isolation even existed. 

With context isolation enabled, you'll need to call `init` in the main process, the renderer preload and in the renderer in the isolated context.

**Comment by hibearpanda** [comment]
That's wonderful @timfish. Thank you very much I took a look at your PR and can see where it is headed.

**Comment by ferretwithaberet** [comment]
> With context isolation enabled, you'll need to call `init` in the main process, the renderer preload and in the renderer in the isolated context.

I am trying to do this, but it does not seem to capture unhandled errors.

My code is:
```js
// Main process
...
const Sentry = require("@sentry/electron");
Sentry.init({
    dsn: "_DSN_",
});
...

// Preload script
...
const Sentry = require("@sentry/electron");
Sentry.init({
    dsn: "_DSN_",
});
contextBridge.exposeInMainWorld("electron", {
    // General
    Sentry: Sentry,
    ...
});

// Renderer
<script>
    electron.Sentry.init({
        dsn: "_DSN_",
    });
</script>
```

**Comment by timfish** [comment]
`contextIsoaltion` will only work once #280 is merged.

Once this is merged you'll need to call `init` from the main process and both the preload and renderer. You cannot call `init` via `contextBridge`.

[This test app](https://github.com/timfish/sentry-electron/tree/feat/contextIsolation/test/e2e/isolated-app/src) shows what is required.

**Comment by bermanboris** [comment]
Thanks for merging #280! 
@timfish @HazAT 
Any idea when it'll be available on npm?

**Comment by timfish** [comment]
@bermanboris Now!

**Comment by bermanboris** [comment]
Thanks for an update @timfish !

**Comment by hibearpanda** [comment]
Hi @timfish, would it be possible to provide an example of `preload.js`? [In the link to the test app, a `preload.js` file is provided](https://github.com/getsentry/sentry-electron/blob/master/test/e2e/isolated-app/src/main.js#L15) but I don't see this available in the test app.

**Comment by bermanboris** [comment]
@hibearpanda Hey! According to webpack configuration, it uses src/sentry.js file as preload. I hope this helps.
