### ISSUE TITLE
Missing built-in symbols for libGLESv2

### ISSUE THREAD

**Issue by poiru** [getsentry/sentry-electron#283]
Sentry has built-in debug symbol support for e.g. Electron.exe, but seems to be missing some of the other symbols that are distributed as part of the Electron symbols package. In particular, we need the libGLESv2 symbols.

```
$ unzip -l electron-v10.1.7-win32-x64-pdb.zip | grep libGLESv2
115564544  1980-01-01 00:00   libGLESv2.dll.pdb
```

Here is an example issue: https://sentry.io/share/issue/266bfdd1e38a446c9ac534f18dce26be/

As you can see, `electron.exe.pdb` was used but `libGLESv2.dll.pdb` is missing.

**Comment by poiru** [comment]
cc @jan-auer because you wrote the Sentry + Electron blog post, any idea why this may be?

**Comment by timfish** [comment]
Sentry has the symbols via the Electron symbol server but I think on Windows they don't work via that route because the electron binary gets renamed to your app name for distribution.

If you manually upload the symbols it can match the pdbs via the id.

**Comment by timfish** [comment]
Alternatively, `libGLESv2.dll.pdb` might be missing from the symbol server for the version of electron you're using?

**Comment by poiru** [comment]
@MarshallOfSound Do you know if `libGLESv2.dll.pdb` gets uploaded to the Electron symbol server?

**Comment by jan-auer** [comment]
I can't solve this on my end, unfortunately, but here is some additional information. The symbol has the debug identifier `dc9b50f6-8734-d595-4c4c-44205044422e-1`.

Symbols would be expected at one of the following URLs, and they are indeed missing:
- https://symbols.electronjs.org/libGLESv2.dll.pdb/dc9b50f68734d5954c4c44205044422e1/libGLESv2.dll.pdb
- https://symbols.electronjs.org/libGLESv2.dll.pdb/dc9b50f68734d5954c4c44205044422e1/libGLESv2.dll.sym

This is a crash from Electron 10.1.7 on Windows x64. The corresponding [PDB archive](https://github.com/electron/electron/releases/download/v10.1.7/electron-v10.1.7-win32-x64-pdb.zip) does contain `libGLESv2.dll.pdb` with the matching identifier. 

Until this is uploaded to the Electron symbol server, I would recommend to retrieve the PDB from the linked archive and upload it to your Sentry project, like @timfish suggested.

**Comment by poiru** [comment]
Ah! Thanks for the info, I opened electron/electron#26961 instead to get symols on the Electron symbol server.
