### ISSUE TITLE
Sentry module crashes with infinite loop in case of uncaught exception

### ISSUE THREAD

**Issue by shafalibhatia** [getsentry/sentry-electron#289]
SDK version - `@sentry/electron@1.5.2`
Electron version - `electron@9.2.0`
Platform - `Windows/macOS`

## Description

In case of uncaught exception, it crashes. Setting to disable the handler for uncaught exception is not working. I tried to use defaultIntegration: false in settings.

**Comment by drinksbydrew** [comment]
Where does it infinite loop? Do you have a trace?

**Comment by mcandmc** [comment]
@sentry/electron: 2.4.1

**Comment by timfish** [comment]
If you're still seeing this in 2.4.1 I'm going to need a stack trace or some example code to reproduce the issue.

**Comment by timfish** [comment]
This should be fixed in 2.4.1. If not, please open a new issue!
