### ISSUE TITLE
(cannot read property Symbol(Symbol.iterator))

### ISSUE THREAD

**Issue by zhaoxiaolei519109457** [getsentry/sentry-electron#296]
-  Review the documentation: https://docs.sentry.io/platforms/javascript/electron/
- Search for existing issues: https://github.com/getsentry/sentry-electron/issues
-  Use the latest release: https://github.com/getsentry/sentry-electron/releases
-  Provide a link to the affected event from your Sentry account

## Versions + Platform

- SDK version - `@sentry/electron@v2.1.0`
- Electron version - `electron@v5.0.8`
-  Platform - `Windows`

## Description
We used the 2.1.0 version of the backend sentry and now we have updated the sentry/electron to find this error frequently and how to handle it or which version the author has recommended to use. Looking forward to your reply

**Comment by christhegrand** [comment]
This is also happening to us. We released a new Electron build yesterday that upgraded @sentry/electron to 2.0.4 from 1.3.0 and we now have about 260, 000 occurrences of this error in Sentry.

**Comment by zhaoxiaolei519109457** [comment]
We also upgraded from 1.3.0 to 2.1.0. Have you found a solution？

**Comment by christhegrand** [comment]
We updated the app to use the same version of Sentry Electron for both the main and renderer processes (they're both on 2.2.0 now). We're not seeing this error on the newer version of the app as far as I can tell.

**Comment by zhaoxiaolei519109457** [comment]
Thank you for your advice. Which version number of Electron do you use? And then I have another question to ask you, about electron crashReporter. Start only available in the main process or does it also need to start in the rendering process? Looking forward to your reply

**Comment by timfish** [comment]
If you run different versions in the main and renderer it'll only be luck if anything works.

The renderer passes events and content through the main process and much has changed between those version numbers.

**Comment by christhegrand** [comment]
zhaoxiaolei519109457, we're on Electron 11.2.3.
