### ISSUE TITLE
Update to latest Sentry SDKs

### ISSUE THREAD

**Issue by eelco** [getsentry/sentry-electron#298]
When will this package be upgraded to use the 6.x SDKs?

**Comment by hipstersmoothie** [comment]
This is currently doubling the size of the included sentry code in our application

![Screen Shot 2021-05-03 at 6 00 46 PM](https://user-images.githubusercontent.com/1192452/116950322-7c181b00-ac39-11eb-904c-ac320adce123.png)

**Comment by hipstersmoothie** [comment]
Looks like it's a non breaking change. PR incoming!

**Comment by hipstersmoothie** [comment]
Saw the PR up to update this. Won't send a PR, but I urge you to merge it ;P

**Comment by timfish** [comment]
The Sentry v6 SDKs automatically track sessions and we are undecided as to how this should work in the context of an Electron application. If we update to the v6 SDKs without considering sessions, Sentry will begin reporting session information that is highly unlikely to match your expectations.

**Comment by timfish** [comment]
Update to 6.4.1 is already merged into master and is awaiting on a couple of other things before release.

Sessions are disabled for now.
