### ISSUE TITLE
crashReporter.getCrashesDirectory is deprecated and no longer available

### ISSUE THREAD

**Issue by defunctzombie** [getsentry/sentry-electron#301]
Per [electron docs](https://www.electronjs.org/docs/api/crash-reporter#crashreportergetcrashesdirectory-deprecated) the `crashes.getCrashesDirectory` method is deprecated. It is replaced by `app.getPath('crashDumps')`.

The current behavior results in this error (based on my packaging) within the main process during startup:

```
TypeError: electron__WEBPACK_IMPORTED_MODULE_1__.crashReporter.getCrashesDirectory is not a function
    at MainBackend.eval (webpack:///../node_modules/@sentry/electron/esm/main/backend.js?:200:92)
```

I've inspected the `crashReporter` object returned via the import statement and indeed `getCrashesDirectory` is no longer present.

`app.getPath('crashDumps')` was introduced in [electron v9](https://github.com/electron/electron/blob/v9.0.0/docs/api/app.md#appgetpathname)

---

- [x] Review the documentation: https://docs.sentry.io/platforms/javascript/electron/
- [x] Search for existing issues: https://github.com/getsentry/sentry-electron/issues
- [x] Use the latest release: https://github.com/getsentry/sentry-electron/releases
- [ ] Provide a link to the affected event from your Sentry account

## Versions + Platform

- [x] SDK version - `@sentry/electron@v2.3.0`
- [x] Electron version - `electron@v12`
- [x] Platform - Any platform

**Comment by kaatt** [comment]
please cut a new release now that this is fixed?

**Comment by timfish** [comment]
Bear with me while I add Electron v12 to the test suite.

No point rolling a release if there are other incompatibilities with v12.
