### ISSUE TITLE
minidump 0kb

### ISSUE THREAD

**Issue by Z-SmallRock** [getsentry/sentry-electron#307]
-  Review the documentation: https://docs.sentry.io/platforms/javascript/electron/
-  Search for existing issues: https://github.com/getsentry/sentry-electron/issues
-  Use the latest release: https://github.com/getsentry/sentry-electron/releases
-  Provide a link to the affected event from your Sentry account

## Versions + Platform

- SDK version - `@sentry/electron@v2.1.0`
- Electron version - `electron@v5.0.8`
- Platform - `Windows`

## Description

After minidump submitted. It was found to be 0KB DMP. Under what circumstances does this happen?

![image](https://user-images.githubusercontent.com/43021784/110297766-cb254380-802e-11eb-869a-382e4b74c955.png)

**Comment by timfish** [comment]
We have just released v3.0.0 of the SDK which includes a lot of changes and improvements since this issue was opened. 

If you can still reproduce this with v3, please open a new issue and I'll look into it.
