### ISSUE TITLE
Missing stacktrace in renderer process when using Node.js API integration

### ISSUE THREAD

**Issue by clemp6r** [getsentry/sentry-electron#308]
- [x] Review the documentation: https://docs.sentry.io/platforms/javascript/electron/
- [x] Search for existing issues: https://github.com/getsentry/sentry-electron/issues
- [x] Use the latest release: https://github.com/getsentry/sentry-electron/releases
- [ ] Provide a link to the affected event from your Sentry account

## Versions + Platform

- [x] SDK version - `@sentry/electron@v2.4.0`
- [x] Electron version - `electron@v11.0.4`
- [x] Platform - `macOS`

## Description

When capturing a exception thrown by the Node integration in the renderer process, the reported stacktrace is empty.

Sample code to reproduce:
```ts
  const exec = promisify(childProcess.exec);
  const command = `commandThatFails`;
  let stdout: string;
  try {
    const response = await exec(command);
    stdout = response.stdout;
  } catch (error) {
    console.log('got error', error);
    stdout = error.stdout;
    if (!stdout) {
      Sentry.captureException(error);
    }
  }
```

The console prints the following (we can see here the value of error.stack):
```
got error Error: Command failed: commandThatFails
/bin/sh: commandThatFails: command not found

    at ChildProcess.exithandler (child_process.js:312)
    at ChildProcess.emit (events.js:315)
    at maybeClose (internal/child_process.js:1021)
    at Socket.<anonymous> (internal/child_process.js:443)
    at Socket.emit (events.js:315)
    at Pipe.<anonymous> (net.js:674)
```

The error is correctly reported when calling `Sentry.captureException(error)` but in the Sentry web interface the stacktrace is empty. Only the first two lines appear:

```
Command failed: commandThatFails
/bin/sh: commandThatFails: command not found
```

It seems the Sentry client tries to parse the stack as a Chrome stack, but as the error comes from the Node integration, the format does not match and all frames are skipped.

**Comment by timfish** [comment]
You don't want to catch each exception twice. Once from nodejs, and once from Electron forwarding to Chrome.

I seem to remember that subscribing to the nodejs error events disables the re-throwing in the Chrome context.

**Comment by clemp6r** [comment]
> You don't want to catch each exception twice

That's not what is happening. See my sample code: Node APIs are called from the renderer, and then an error is thrown and is caught a few lines below, in the renderer.

**Comment by timfish** [comment]
I understand your issue and it is caused by the fact that `@sentry/node` is not used in the renderer.

I'm saying that to fix your issue, `@sentry/electron` needs to be modified to use `@sentry/node` in the renderer and we need to ensure that exceptions are not caught twice.

**Comment by clemp6r** [comment]
Besides, I looked again at my sample stacktrace and it seems there is nothing interesting into, it apart technical framework frames. No function from my application appear. I may have to create new Error objects if I want to have a good stracktrace. Or it is Sentry's responsiblity?

```ts
  try {
    const response = await exec(command);
  } catch (error) {
    console.log('got error', error);
    stdout = error.stdout;
    if (!stdout) {
      const wrappedError = new Error('Unable to run command: ' + error);
      Sentry.captureException(wrappedError);
    }
 ```
