### ISSUE TITLE
Problems in renderer process with contextIsolation: true

### ISSUE THREAD

**Issue by richardfritsch** [getsentry/sentry-electron#316]
- [x] Review the documentation: https://docs.sentry.io/platforms/javascript/electron/
- [x] Search for existing issues: https://github.com/getsentry/sentry-electron/issues
- [x] Use the latest release: https://github.com/getsentry/sentry-electron/releases
- [ ] Provide a link to the affected event from your Sentry account

## Versions + Platform

- [x] SDK version - `@sentry/electron@v2.4.0`
- [x] Electron version - `electron@v12.0.2`
- [x] Platform - `Windows/macOS/Linux`

## Description

I'm facing two issues with exceptions occurring in a web page loaded in BrowserWindow started with `contextIsolation: true` and `nodeIntegration: false` (Sentry is initialized as the first thing in a preload script):
* Unhandled exceptions are not sent to Sentry at all – maybe the `'error'` event handler is not working when set up in the isolated context
* To capture exceptions manually, I expose `Sentry.captureException` in `window` by `contextBridge.exposeInMainWorld`, but any exception passed to it goes through the context isolation machinery, which creates a new Error object that only has a message property – stacktrace and error type is lost.

How should we deal with this? Loading and initializing only @sentry/browser in the actual webpage instead of the preload script would work, but then we lose all Electron breadcrumbs etc.

**Comment by timfish** [comment]
Thanks for reporting this. I added the context isolation feature with tests but I have not tested it in a production app yet.

The tests run against [this demo app](https://github.com/getsentry/sentry-electron/tree/master/test/e2e/isolated-app) which [throws an error in the renderer](https://github.com/getsentry/sentry-electron/blob/83b09ed2f11cd0242afc95842eba53adbfe17dcb/test/e2e/isolated-app/src/renderer.js#L4).

<details><summary>Running the above test in Electron v12, the following event gets sent to the test server</summary>
<p>

```json
{
  "data":{
    "environment":"production",
    "extra":{
      "crashed_process":"browser",
      "arguments":[
        
      ]
    },
    "release":"isolated-app@1.0.0",
    "user":{
      "ip_address":"{{auto}}"
    },
    "exception":{
      "values":[
        {
          "type":"Error",
          "value":"Some renderer error",
          "stacktrace":{
            "frames":[
              {
                "colno":49435,
                "filename":"app:///dist/renderer.js",
                "function":"r",
                "in_app":true,
                "lineno":46
              },
              {
                "colno":42209,
                "filename":"app:///dist/renderer.js",
                "function":"?",
                "in_app":true,
                "lineno":46
              }
            ]
          },
          "mechanism":{
            "handled":true,
            "type":"instrument",
            "data":{
              "function":"setTimeout"
            }
          }
        }
      ]
    },
    "level":"error",
    "event_id":"83ecbc8f747e4b8da3a45c9f44bd1961",
    "platform":"javascript",
    "sdk":{
      "name":"sentry.javascript.electron",
      "packages":[
        {
          "name":"npm:@sentry/browser",
          "version":"5.27.6"
        },
        {
          "name":"npm:@sentry/electron",
          "version":"2.4.0"
        }
      ],
      "version":"2.4.0",
      "integrations":[
        "InboundFilters",
        "FunctionToString",
        "Console",
        "Http",
        "OnUnhandledRejection",
        "LinkedErrors",
        "OnUncaughtException",
        "Electron"
      ]
    },
    "timestamp":1616930345.223,
    "breadcrumbs":[
      {
        "timestamp":1616930343.989,
        "category":"electron",
        "message":"app.will-finish-launching",
        "type":"ui"
      },
      {
        "timestamp":1616930344.055,
        "category":"electron",
        "message":"app.ready",
        "type":"ui"
      },
      {
        "timestamp":1616930344.124,
        "category":"electron",
        "message":"app.session-created",
        "type":"ui"
      },
      {
        "timestamp":1616930344.13,
        "category":"electron",
        "message":"app.web-contents-created",
        "type":"ui"
      },
      {
        "timestamp":1616930344.131,
        "category":"electron",
        "message":"app.browser-window-created",
        "type":"ui"
      },
      {
        "timestamp":1616930344.576,
        "category":"electron",
        "message":"app.gpu-info-update",
        "type":"ui"
      },
      {
        "timestamp":1616930344.713,
        "category":"electron",
        "message":"WebContents[1].dom-ready",
        "type":"ui"
      },
      {
        "timestamp":1616930344.717,
        "category":"console",
        "data":{
          "arguments":[
            "%cElectron Security Warning (Insecure Content-Security-Policy)",
            "font-weight: bold;",
            "This renderer process has either no Content Security\n    Policy set or a policy with \"unsafe-eval\" enabled. This exposes users of\n    this app to unnecessary security risks.\n\nFor more information and help, consult\nhttps://electronjs.org/docs/tutorial/security.\nThis warning will not show up\nonce the app is packaged."
          ],
          "logger":"console"
        },
        "level":"warning",
        "message":"%cElectron Security Warning (Insecure Content-Security-Policy) font-weight: bold; This renderer process has either no Content Security\n    Policy set or a policy with \"unsafe-eval\" enabled. This exposes users of\n    this app to unnecessary security risks.\n\nFor more information and help, consult\nhttps://electronjs.org/docs/tutorial/security.\nThis warning will not show up\nonce the app is packaged."
      }
    ],
    "request":{
      "url":"app:///dist/index.html",
      "headers":{ }
    },
    "contexts":{
      "app":{
        "app_name":"isolated-app",
        "app_version":"1.0.0"
      },
      "browser":{
        "name":"Chrome"
      },
      "chrome":{
        "name":"Chrome",
        "type":"runtime",
        "version":"89.0.4389.69"
      },
      "device":{
        "arch":"x64",
        "family":"Desktop"
      },
      "node":{
        "name":"Node",
        "type":"runtime",
        "version":"14.16.0"
      },
      "os":{
        "kernel_version":"20.3.0",
        "name":"macOS",
        "version":"11.2.3",
        "build":"20D91"
      },
      "runtime":{
        "name":"Electron",
        "version":"12.0.0"
      },
      "electron":{
        "crashed_process":"renderer[1]",
        "crashed_url":"app:///dist/index.html"
      }
    },
    "tags":{
      "event_type":"javascript"
    }
  },
  "dump_file":false,
  "id":"277345",
  "sentry_key":"37f8a2ee37c0409d8970bc7559c7c7e4",
  "method":"envelope"
}
```
</p>
</details>

This event has all the expected context and exception information.

Please ensure that you've called `Sentry.init()` in:
- The main process
- The renderer preload
- AND the renderer isolated context

This is required so that events are correctly passed from Isolated > non-isloated > main.

If you're correctly starting Sentry as above and you are still seeing issues with missing events, can you supply a minimal example reproducing your setup? Better still, adding a failing test case would show me exactly what we're missing!

**Comment by richardfritsch** [comment]
Thanks for looking into it. I didn't know I have to call Sentry.init in the renderer isolated context, this is not mentioned anywhere. Your test code is heavily pre-preprocessed before it's executed, so it's not clear what it actually does – you can't call `require('./sentry')` in the (renderer isolated) webpage with `nodeIntegration: false` and `contextIsolation: true`, the `require` function is not available. What does your `require` function in renderer.js do in terms of pure JS?

The question is, where do I get `Sentry.init` from in the renderer isolated context? It's not in `window.__SENTRY_IPC__` after calling `init` in preload. If I expose it by `contextBridge.exposeInMainWorld` in preload myself and call it, it still doesn't send events. If I expose `Sentry.captureException` and call it, then the exceptions lose context. The other option of including pure browser `<script type="text/javascript" src="sentry/bundle.es6.min.js"></script>` in the webpage would mean no Electron info.

**Comment by timfish** [comment]
Yes, there is no `require` in the isolated renderer context so just when targeting a browser, you'll need to use a bundler if you want to import/require modules.

All three entry points for the isolated test app are built with Webpack. You can see the configuration [here](https://github.com/getsentry/sentry-electron/blob/83b09ed2f11cd0242afc95842eba53adbfe17dcb/test/e2e/isolated-app/webpack.config.js). This Webpack configuration outputs three files, `main.js`, `preload.js` and `renderer.js`.

**Comment by richardfritsch** [comment]
Right, makes sense. We use another minifier for our app, so I used Webpack to process a JS file containing only `window.Sentry = require("@sentry/electron");` with `target: "web"` and it works. I can use the resulting file the same way as @sentry/browser's bundle.es6.min.js file, which we use for the pure web flavour for our app. This approach might be useful to others and maybe you could provide a bundle like this with @sentry/electron releases. Could you please update the docs for Electron to include all the important details that you posted here? Thanks.

**Comment by richardfritsch** [comment]
We‘ve run into another issue – with `contextIsolation: true`, scope updates in an isolated renderer aren‘t propagated to main, so erorrs occurring there lack tags and breadcrumbs that were added in the isolated renderer. Looking at Sentry code, it seems that `RendererBackend._setupScopeListener()` is only executed for non-isolated renderers, but it should be executed for both isolated and non-isolated renderers. If I call it myself, things work as expected.

**Comment by timfish** [comment]
Thanks for reporting. I'll take a look!

**Comment by timfish** [comment]
I've run [this](https://github.com/getsentry/sentry-electron/blob/0d7bde795b06a64c8de08bb11be71b8eebb5a241/test/e2e/index.test.ts#L362) isolated test locally and get the following event data:
<details>
 <summary>Event</summary>

```json
{
  "data": {
    "environment": "production",
    "extra": {
      "crashed_process": "browser",
      "arguments": []
    },
    "release": "isolated-app@1.0.0",
    "user": {
      "ip_address": "{{auto}}"
    },
    "exception": {
      "values": [
        {
          "type": "Error",
          "value": "Some renderer error",
          "stacktrace": {
            "frames": [
              {
                "colno": 50027,
                "filename": "app:///dist/renderer.js",
                "function": "r",
                "in_app": true,
                "lineno": 46
              },
              {
                "colno": 42801,
                "filename": "app:///dist/renderer.js",
                "function": "?",
                "in_app": true,
                "lineno": 46
              }
            ]
          },
          "mechanism": {
            "handled": true,
            "type": "instrument",
            "data": {
              "function": "setTimeout"
            }
          }
        }
      ]
    },
    "level": "error",
    "event_id": "d2bee32df1a445ac8d2392087f3e11da",
    "platform": "javascript",
    "sdk": {
      "name": "sentry.javascript.electron",
      "packages": [
        {
          "name": "npm:@sentry/browser",
          "version": "5.27.6"
        },
        {
          "name": "npm:@sentry/electron",
          "version": "2.4.0"
        }
      ],
      "version": "2.4.0",
      "integrations": [
        "InboundFilters",
        "FunctionToString",
        "Console",
        "Http",
        "OnUnhandledRejection",
        "LinkedErrors",
        "OnUncaughtException",
        "Electron"
      ]
    },
    "timestamp": 1619516226.474,
    "breadcrumbs": [
      {
        "timestamp": 1619516225.784,
        "category": "electron",
        "message": "app.will-finish-launching",
        "type": "ui"
      },
      {
        "timestamp": 1619516225.787,
        "category": "electron",
        "message": "app.ready",
        "type": "ui"
      },
      {
        "timestamp": 1619516225.798,
        "category": "electron",
        "message": "app.session-created",
        "type": "ui"
      },
      {
        "timestamp": 1619516225.802,
        "category": "electron",
        "message": "app.web-contents-created",
        "type": "ui"
      },
      {
        "timestamp": 1619516225.804,
        "category": "electron",
        "message": "app.browser-window-created",
        "type": "ui"
      },
      {
        "timestamp": 1619516225.955,
        "category": "electron",
        "message": "app.gpu-info-update",
        "type": "ui"
      },
      {
        "timestamp": 1619516225.969,
        "category": "electron",
        "message": "WebContents[1].dom-ready",
        "type": "ui"
      },
      {
        "timestamp": 1619516225.973,
        "category": "console",
        "data": {
          "arguments": [
            "%cElectron Security Warning (Insecure Content-Security-Policy)",
            "font-weight: bold;",
            "This renderer process has either no Content Security\n    Policy set or a policy with \"unsafe-eval\" enabled. This exposes users of\n    this app to unnecessary security risks.\n\nFor more information and help, consult\nhttps://electronjs.org/docs/tutorial/security.\nThis warning will not show up\nonce the app is packaged."
          ],
          "logger": "console"
        },
        "level": "warning",
        "message": "%cElectron Security Warning (Insecure Content-Security-Policy) font-weight: bold; This renderer process has either no Content Security\n    Policy set or a policy with \"unsafe-eval\" enabled. This exposes users of\n    this app to unnecessary security risks.\n\nFor more information and help, consult\nhttps://electronjs.org/docs/tutorial/security.\nThis warning will not show up\nonce the app is packaged."
      }
    ],
    "request": {
      "url": "app:///dist/index.html",
      "headers": {}
    },
    "contexts": {
      "app": {
        "app_name": "isolated-app",
        "app_version": "1.0.0"
      },
      "browser": {
        "name": "Chrome"
      },
      "chrome": {
        "name": "Chrome",
        "type": "runtime",
        "version": "89.0.4389.69"
      },
      "device": {
        "arch": "x64",
        "family": "Desktop"
      },
      "node": {
        "name": "Node",
        "type": "runtime",
        "version": "14.16.0"
      },
      "os": {
        "name": "Windows",
        "version": "10.0.19042"
      },
      "runtime": {
        "name": "Electron",
        "version": "12.0.0"
      },
      "electron": {
        "crashed_process": "renderer[1]",
        "crashed_url": "app:///dist/index.html"
      }
    },
    "tags": {
      "event_type": "javascript"
    }
  },
  "dump_file": false,
  "id": "277345",
  "sentry_key": "37f8a2ee37c0409d8970bc7559c7c7e4",
  "method": "envelope"
}
```
</details>

This event has all the context I would expect.

You should be calling `init` in the main process, in the preload script and in the isolated context. This allows us to pass data and context through `Isolated > Non-isolated > IPC > Main`.

If you can supply code that reproduces the lack of context you are seeing I can get a better idea of what's going wrong.

**Comment by richardfritsch** [comment]
Sorry, I guess I wasn‘t very clear. The problem is with errors occurring in the *main* process, your test case only tests an error in the isolated renderer. I am calling `init` in all three, as per your advice from before, so events get submitted. The issue is that I call
```js
Sentry.configureScope(scope => {
    scope.setUser({ id });
});
```
in the isolated renderer, and then at some point in the future, if an exception is thrown in the *main* process and sent to Sentry, it doesn't have the user info that was provided before.

If I call
```js
Sentry.getCurrentHub().getClient()._backend._setupScopeListener();
```
in the isolated renderer right after calling `init`, then all errors that occur in *main* will have that user info, breadcrumbs etc.

Does that make sense?

**Comment by timfish** [comment]
Ah, yes you are correct, we're listening to scope changes in the "preload" scope updates, but we're not listening to scope changes in the isolated context.

**Comment by timfish** [comment]
2.4.1 should be on npm any minute now.

Thank you @richardfritsch for all your testing and reporting!

**Comment by mjwvb** [comment]
WIth 2.4.1 I still have the same problem. I force the main process to crash, but it still doesn't get the scope and events from my sentry (react) implementation in the html context. 

It seems that sentry-electron and sentry-react don't work together. I tested it with sentry-electron in the html context instead, and then the scope and events are indeed copied over. Now I have to enable nodeIntegration as a workaround, which I don't like. Do I have to do something special to integrate sentry-react with sentry-electron?
