### ISSUE TITLE
Sentry not symbolicating macOS ARM64 crashes

### ISSUE THREAD

**Issue by poiru** [getsentry/sentry-electron#325]
Here is an example of a poorly symbolicated crash: https://sentry.io/share/issue/8f7827b77a304f02b4e449dcd6e1a3b8/

I suspect your internal setup is not downloading symbols for Electron 11+ macOS ARM64 builds (e.g. `electron-v11.4.4-darwin-arm64-dsym.zip` and `electron-v11.4.4-darwin-arm64-symbols.zip`). This works perfectly fine for x86-64 builds.

**Comment by poiru** [comment]
cc @jan-auer

**Comment by timfish** [comment]
Sentry does not download Electron symbols from Github releases, it uses Electrons official symbol server. I suppose the first question is does the Electron server have the macOS arm64 symbols?

You can manually upload the symbols from zips downloaded from GitHub releases using `sentry-cli`. The Sentry wizard offers [a script](https://github.com/getsentry/sentry-wizard/blob/master/scripts/Electron/symbols.js) to automate the process.

**Comment by poiru** [comment]
@timfish Is the symbol server used for macOS as well? I thought symbol servers were a thing only on Windows, but I could well be wrong.

**Comment by timfish** [comment]
Yep, normally Windows only but they've used it for all platforms. I saw a load of issues/PRs on the Electron repository towards the end of last year where they fixed problems with all sorts of missing symbols so it's possible macOS arm64 symbols were forgotten when the platform was added.

I _think_ you can take the module IDs from your unsymbolicated crash and look them up manually on the server to check if they're on there but I can't remember how to construct the URLs.

**Comment by timfish** [comment]
Although having said all of the above, [this](https://github.com/electron/electron/blob/0b4231680354921244a149a4453cc2afb6509cd8/script/release/uploaders/upload-symbols.py#L49-L55) looks like Electron builds are in fact pushing symbols to Sentry!

**Comment by timfish** [comment]
I've tested this working only last week with recent versions of Electron and the [Electron symbol server enabled](https://docs.sentry.io/platforms/javascript/guides/electron/#debug-information).
