### ISSUE TITLE
Source maps are not being traced in Sentry error for React JS

### ISSUE THREAD

**Issue by Dipesh-Das97** [getsentry/sentry-electron#327]
Hello,
I working on a CRA and integrated sentry. I dont have a repo integration and I am uploading the files manually. The files are being uploaded to the artifacts both the source file and source map. I am using the below 3 variables and executing the js file with sentry-cli:
const create_release = `sentry-cli releases --org=${SENTRY_ORG} new --project=${SENTRY_PROJECT} ${REACT_APP_SENTRY_RELEASE}`;
const maps = `sentry-cli releases --org=${SENTRY_ORG} --project=${SENTRY_PROJECT} files ${REACT_APP_SENTRY_RELEASE} upload-sourcemaps ./build --url-prefix "~/build/static/js" --validate build/static/js`
const files = `sentry-cli releases --org=${SENTRY_ORG} --project=${SENTRY_PROJECT} files ${REACT_APP_SENTRY_RELEASE} upload ./build --url-prefix "~/build/static/js"`

I followed all the steps but its still persits. I will upload any info need. 
Below show all the source files and maps being uploaded:
![Screenshot (262)](https://user-images.githubusercontent.com/59877761/117580024-74fa7c80-b113-11eb-9879-deacf96793cb.png)
The local repo will show how the build file structure is:
![Screenshot (263)](https://user-images.githubusercontent.com/59877761/117580082-c571da00-b113-11eb-8d7f-d37b93c13707.png)
This is how the stack looks:
![Screenshot (264)](https://user-images.githubusercontent.com/59877761/117580166-47620300-b114-11eb-87ec-c8cdf5f7d3f7.png)
My Sentry SDK looks like this:
`Sentry.init({
  dsn: "https://f70c3fee.....",
  integrations: [new Integrations.BrowserTracing()],
  autoSessionTracking: true,
  release: REACT_APP_SENTRY_RELEASE,
  attachStacktrace: true
});`

Created the API token with `project:write`

**Comment by timfish** [comment]
I don't have much experience in fixing sourcemap issues but I notice that your sources/maps are uploaded starting with `~/build/static/...` but the paths in your stack-traces start with `~/static/...`. 

Therefore I _think_ you should be using `--url-prefix "~/static/js"`.

**Comment by Dipesh-Das97** [comment]
Hi @timfish  thanks for replying. I was able to fix the issue by deploying the application to GAE. Basically local host has a firewall and it wasn't allowing the source to be fetched. Although I'm not sure why Sentry wasn't using the source file and source map saved as artifacts for detecting the errors and map to its source.

**Comment by Dipesh-Das97** [comment]
Fixed the issue so closed this.
