### ISSUE TITLE
Source code was not found

### ISSUE THREAD

**Issue by madnesspie** [getsentry/sentry-electron#331]
- [x] Review the documentation: https://docs.sentry.io/platforms/javascript/electron/
- [x] Search for existing issues: https://github.com/getsentry/sentry-electron/issues
- [x] Use the latest release: https://github.com/getsentry/sentry-electron/releases
- [x] Provide a link to the affected event from your Sentry account https://sentry.io/organizations/sensorehab/issues/2397023279/?project=5762775&query=is%3Aunresolved

## Versions + Platform

- [x] SDK version - `@sentry/electron@v2.4.1`
- [x] Electron version - `electron@v11.0.1`
- [x] Platform - `Windows`

## Description

Hello! I'm truing to set up source maps. I successfully uploaded sources and source maps to Sentry and it looks like this:
![image](https://user-images.githubusercontent.com/20173040/118122172-24c53800-b3fb-11eb-8599-375ef91cfa19.png)

But on the issue page I see an the error:
![image](https://user-images.githubusercontent.com/20173040/118122496-9c936280-b3fb-11eb-8bd8-a316ad9ce2c7.png)

**Comment by HazAT** [comment]
You only have source code / source maps uploaded for release `1.0.5` and not for `electron-react-boilerplate@1.0.5`, the release has to match 100% otherwise we can't find the source maps.
