### ISSUE TITLE
Sentry module crashes with infinite loop when using proxy with authentication set up  

### ISSUE THREAD

**Issue by PremkantPrasad** [getsentry/sentry-electron#344]
- [ ] Review the documentation: https://docs.sentry.io/platforms/javascript/electron/
- [ ] Search for existing issues: https://github.com/getsentry/sentry-electron/issues
- [ ] Use the latest release: https://github.com/getsentry/sentry-electron/releases
- [ ] Provide a link to the affected event from your Sentry account

## Versions + Platform

- [ ] SDK version - `@sentry/electron@v2.4.1`
- [ ] Electron version - `electron@v13.1.4`
- [ ] Platform - `Windows/macOS`

## Description

Please set up a proxy server with a username and password.
add proxy server in mac or windows
try to run the electron application integrated with sentry

**Comment by timfish** [comment]
> try to run the electron application integrated with sentry

This occurs when you run the application?

**Comment by PremkantPrasad** [comment]
> > try to run the electron application integrated with sentry
> 
> This occurs when you run the application?

Yes

**Comment by PremkantPrasad** [comment]
Please set up a proxy server with a username and password.
add proxy server in mac or windows
try to run the electron application integrated with sentry 
Also please use a machine where there is no internet and all the traffic is only going through proxy server

**Comment by timfish** [comment]
How do you know it's crashing with an infinite loop?

**Comment by PremkantPrasad** [comment]
> How do you know it's crashing with an infinite loop?
function sentryError(error) {
    console.log('sentry error');
}
init({
    onFatalError: sentryError,
})

I used onFatalError properties getting continuously "sentry error" log in console

**Comment by PremkantPrasad** [comment]
Error: net::ERR_TUNNEL_CONNECTION_FAILED
    at SimpleURLLoaderWrapper.<anonymous> (electron/js2c/browser_init.js:105:7029)
    at SimpleURLLoaderWrapper.emit (events.js:315:20)
    at SimpleURLLoaderWrapper.EventEmitter.emit (domain.js:467:12)

Getting this error

**Comment by timfish** [comment]
I don't have any means to setup an authenticated proxy to test this so you are going to have to supply more information.

When you start an Electron application which uses Sentry with the default configuration, it doesn't send anything. If `onFatalError` is being called, then a fatal error has occurred. Are you triggering an error for testing? Is `onFatalError` being triggered unexpectedly? What code are you using to configure Sentry? What code are you using to trigger the error? 

`sentry-electron` [uses Electrons build in `net` module](https://github.com/getsentry/sentry-electron/blob/master/src/main/transports/net.ts). Does Electron load remote pages via the `net` module through the proxy you're using? 

The above stacktrace shows only `SimpleURLLoaderWrapper` which is built into Electron.

**Comment by PremkantPrasad** [comment]
I am using Sentry.captureMessage(message) to reproduce the issue. I am using a local file system to open the page and using Axios to call over the network for HTTP(s) calls.

**Comment by timfish** [comment]
Related: https://github.com/electron/electron/issues/24948

**Comment by timfish** [comment]
@PremkantPrasad it's on my to do list.

Please don't ping me from multiple issues!

**Comment by PremkantPrasad** [comment]
> @PremkantPrasad it's on my to do list.
> 
> Please don't ping me from multiple issues!

@timfish apologize for that. is there any ETA for it as I have to do a public release in 5-6 days.
