### ISSUE TITLE
setupOnce is not a function with integrations function

### ISSUE THREAD

**Issue by felipe-linares** [getsentry/sentry-electron#353]
- [x] Review the documentation: https://docs.sentry.io/platforms/javascript/electron/
- [x] Search for existing issues: https://github.com/getsentry/sentry-electron/issues
- [x] Use the latest release: https://github.com/getsentry/sentry-electron/releases
- [ ] Provide a link to the affected event from your Sentry account

## Versions + Platform

- [x] SDK version - `@sentry/electron@v2.5.1`
- [x] Electron version - `electron@v13.1.6`
- [x] Platform - `Windows/macOS/Linux`

## Description

Our team recently switched to using context bridges with `contextIsolation: true` on Electron windows. However, this is causing issues with initializing sentry when using a function as the value for `integrations` field in `init` object.

Even if we pass a function as simple as 
```
(integrations) => {
    return integrations
 }
```

Contextbridge implementation seems to be stripping integrations objects of any function definitions, so what is the best approach here? 

Things we've tried:
- Initializing only in preload.js -> doesn't capture unhandled exceptions nor context from isolated renderer process (`sentry.captureException` only works if we expose the entire sentry object via `contextBridge`)
- Defining the integrations callback in preload.js itself -> same issue with no difference, objects are still being stripped of function definitions

This could totally be us misinterpreting the proper way to set this up, but there seems to be a lack in documentation for using contextBridges properly

**Comment by mwein99** [comment]
+1

**Comment by TCWTEAM** [comment]
+1

**Comment by timfish** [comment]
> This could totally be us misinterpreting the proper way to set this up

You haven't said how are you setting this up so I can only guess.

Check out the isolated app that runs in the tests:
https://github.com/getsentry/sentry-electron/tree/master/test/e2e/isolated-app

You need to call init in the main, preload and isolated renderer context.

**Comment by felipe-linares** [comment]
You're right, our implementation was incorrect. We were exposing sentry via context bridge from preload context which caused issues. Sentry should've been directly bundled with webpack and imported into renderer.
