### ISSUE TITLE
Initial install and setup - Cannot find module '../../package.json'

### ISSUE THREAD

**Issue by davidwinter** [getsentry/sentry-electron#365]
- [x] Review the documentation: https://docs.sentry.io/platforms/javascript/electron/
- [x] Search for existing issues: https://github.com/getsentry/sentry-electron/issues
- [x] Use the latest release: https://github.com/getsentry/sentry-electron/releases
- [x] Provide a link to the affected event from your Sentry account

## Versions + Platform

- [x] SDK version - `@sentry/electron@v2.5.3`
- [x] Electron version - `electron@v14.0.0`
- [x] Platform - `Linux`

## Description

Followed the initial setup from this page:

https://docs.sentry.io/platforms/javascript/guides/electron/

Added the following to the top of my main and preload scripts:

```js
import * as Sentry from "@sentry/electron";

Sentry.init({dsn: 'https://MY_DSN'});
```
I get this error:

```
A JavaScript error occurred in the main process
Uncaught Exception:
Error: Cannot find module '../../package.json'
Require stack:
- /home/davidwinter/projects/nimblenote/packages/main/dist/index.cjs
- /home/davidwinter/projects/nimblenote/node_modules/electron/dist/resources/default_app.asar/main.js
- 
    at Module._resolveFilename (internal/modules/cjs/loader.js:892:15)
    at Function.n._resolveFilename (electron/js2c/browser_init.js:245:1128)
    at Module._load (internal/modules/cjs/loader.js:737:27)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12913)
    at Module.require (internal/modules/cjs/loader.js:964:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/home/davidwinter/projects/nimblenote/packages/main/dist/index.cjs:6994:19)
    at Module._compile (internal/modules/cjs/loader.js:1083:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1113:10)
    at Module.load (internal/modules/cjs/loader.js:940:32)
```

I assume this might be due to this line:

https://github.com/getsentry/sentry-electron/blob/edd2775048d4658f88fd23a989574da913e6762a/src/main/context.ts#L13

I'm using Vite with Electron.

I'm guessing the resolving of the `package.json` file for this module is failing. I've had this on one of my projects, and I followed guidance here: https://gist.github.com/sindresorhus/a39789f98801d908bbc7ff3ecc99d99c#what-do-i-use-instead-of-__dirname-and-__filename

**Comment by AbhiPrasad** [comment]
This has been changed in WIP v3 branch of the SDK: https://github.com/getsentry/sentry-electron/pull/361/files#diff-6f97f25a80db330c059a31ed17c3fb095077173b6222d224bd4b318f4b570aadR8.

@timfish perhaps we should cherry pick the `SDK_VERSION` change to master?

**Comment by davidwinter** [comment]
Would appreciate a cherry-pick, as I can't use Sentry at all currently :cry:

**Comment by timfish** [comment]
We could backport this to v2 but there are many users who haven't encountered this issue so I'd be interested to see a way to reproduce it.

It's not triggered by regular nodejs resolution or via webpack so I'd be interested to see a full example repository that reproduces the issue so we can add it to the tests.

**Comment by davidwinter** [comment]
@timfish I'll try and setup an example repo. I wonder if it's something that Vite is doing in that case... though sounds like something they would have uncovered already also.

**Comment by timfish** [comment]
It's almost certainly caused by Vite bundler configuration not handling loading of json files. 

I've backported a better solution from the v3 PR!
