### ISSUE TITLE
Using sentry-electron with contextIsolation, preload.js, and nodeIntegration off

### ISSUE THREAD

**Issue by hisnameisjimmy** [getsentry/sentry-electron#366]
Hi there!

I'm trying to get errors from `renderer.js`, where I can't require/import anything because I have nodeIntegration turned off for security reasons. 

I looked at [your sample app](https://github.com/getsentry/sentry-electron/tree/master/test/e2e/isolated-app), but even initializing sentry in the `preload.js`, I'm still not able to get exceptions from `renderer.js`. I test this by trying to run a non-existent function in `renderer.js`, similar to the example you have in the docs.

This is probably a noob-level misunderstanding, but I can't figure out what I'm supposed to do here, despite reading through a number of [issues like this one](https://github.com/getsentry/sentry-electron/issues/279).

I'm happy to share code, but I'd love an example of _exactly_ what I need to put in `renderer.js`, `preload.js`, and `main.js/index.js` to make this work. 

Thank you for making sentry-electron!

Jimmy

**Comment by hisnameisjimmy** [comment]
I decided to go ahead and whip up a [quick stripped down version of things](https://github.com/hisnameisjimmy/sentry-electron-render-test) based on the [Electron Quickstart](https://www.electronjs.org/docs/tutorial/quick-start) to make this a bit clearer. I must be missing something obvious here, but I can't pinpoint it.

Could you take a look at [this repo](https://github.com/hisnameisjimmy/sentry-electron-render-test) and see what I could be missing?

**Comment by timfish** [comment]
Hi Jimmy.

You should not be exposing Sentry across `contextBridge` like this:
```ts
contextBridge.exposeInMainWorld(
	'api', {
		Sentry: Sentry,
	}
);
```
You need to call `init` in every process, so that's the main process, the preload and the renderer. 

So in the renderer, you need to call `init` just like you already are in the preload and main:
```ts
const Sentry = require('@sentry/electron');

Sentry.init({
  dsn: 'DSN',
});
```

The SDK needs to actually be executed in the isolated renderer context so that it can correctly be configured to capture errors.

**Comment by timfish** [comment]
The SDK reports renderer errors with `contextIsolation` enabled and `nodeIntegration` disabled. You need to call `init` in every context so everything can be hooked up.

**Comment by hisnameisjimmy** [comment]
So I think that's where I'm confused. If I try and call require from `renderer.js`, I'm going to hit an error for require (see attached where I try and do it in the test repo from above). Again, I feel like I'm missing something obvious here, but not sure how to close the loop. I appreciate your patience!

<img width="800" alt="CleanShot 2021-09-09 at 19 16 37@2x" src="https://user-images.githubusercontent.com/740373/132788875-5092b031-ab99-4607-8667-644eaaa0f2f3.png">

**Comment by timfish** [comment]
When using `nodeIntegration: false` and `contextIsolation: true`, there is no access to require in the renderer. 

This means that if you want to use any external dependencies in the renderer you'll need to use a bundler like Webpack. This applies to any dependencies, not just the Sentry SDK.

**Comment by hisnameisjimmy** [comment]
Ah ok, that makes sense. So in my case, without using webpack, I would just init Sentry in `main.js`, or maybe `main.js` and `preload.js`.

**Comment by timfish** [comment]
Yes. Unless you bundle your renderer code, you will not be able to use any dependencies in the renderer process with `nodeIntegration: false`.

**Comment by stdavis** [comment]
Does anyone have an example of our to bundle the preload script with webpack? I'm struggling to wire everything up correctly.

**Comment by timfish** [comment]
With 3.0.0-beta.1, here is an example in the integration test examples:
https://github.com/getsentry/sentry-electron/tree/master/examples/webpack-context-isolation

If you can wait a few days 3.0.0-beta.2 should remove the need for a preload unless you're bundling the main process code and using Electron < v5:
https://github.com/getsentry/sentry-electron/pull/377

**Comment by svallory** [comment]
> With 3.0.0-beta.1, here is an example in the integration test examples: https://github.com/getsentry/sentry-electron/tree/master/examples/webpack-context-isolation
> 
> If you can wait a few days 3.0.0-beta.2 should remove the need for a preload unless you're bundling the main process code and using Electron < v5: #377

Hi! I tried everything I could, I've read a lot of docs and issues, but could not get Sentry to work on the code side of a Figma plugin :/

I'm not that familiar with electron, but simply importing sentry seems to break Figma itself.

Here's my rollup config:

```
import resolve from "@rollup/plugin-node-resolve";
import commonjs from "@rollup/plugin-commonjs";
import typescript from "@rollup/plugin-typescript";
import { sentryRollupPlugin } from "@sentry/rollup-plugin";

export default [
  // CODE.JS
  // The part that communicates with Figma directly
  // Runs in a sandboxed environment (isolated context in electron)
  // with no access to Node, the DOM, or any of the node/browser APIs
  {
    input: "src/code/init.ts",
    output: {
      file: "dist/code.js",
      format: "iife",
      name: "code",
      sourcemap: true,
    },
    plugins: [
      typescript(),
      resolve({
        browser: true,
        moduleDirectories: ["node_modules"],
      }),
      commonjs({ transformMixedEsModules: true, typescript: true }),
      // production && terser(),
      // Put the Sentry rollup plugin after all other plugins
      sentryRollupPlugin({
        org: "toki-labs",
        project: "cva-code",

        // Auth tokens can be obtained from https://sentry.io/settings/account/api/auth-tokens/
        // and need `project:releases` and `org:read` scopes
        authToken: "cfdb3b212fb641d8975053d5fe1ac5ffdc8799f52aad40d982cd0b33cc65c4f3",
      })
    ],
  }
]
```

Here's the error I'm getting:

```
00:24:17.803 figma_app.min.js.br:5 Error: Syntax error on line 2380: Unexpected token ...
    at sHo (figma_app.min.js.br:1628:98)
    at async figma_app.min.js.br:1758:6222
(anonymous) @ figma_app.min.js.br:5
vef @ figma_app.min.js.br:1758
await in vef (async)
(anonymous) @ figma_app.min.js.br:1758
(anonymous) @ figma_app.min.js.br:1758
runLastPlugin @ figma_app.min.js.br:2409
_FigmaApp_runLastPlugin @ compiled_wasm.js.br:2
$wasm-function[12721] @ compiled_wasm.wasm.br:0xa5d952
$wasm-function[19997] @ compiled_wasm.wasm.br:0xc1b6a8
$wasm-function[1022] @ compiled_wasm.wasm.br:0x21a75
$wasm-function[18831] @ compiled_wasm.wasm.br:0xbfea0a
$wasm-function[8628] @ compiled_wasm.wasm.br:0x662bca
$wasm-function[29734] @ compiled_wasm.wasm.br:0xfd09e1
$wasm-function[3412] @ compiled_wasm.wasm.br:0x1a2cc7
$wasm-function[26663] @ compiled_wasm.wasm.br:0xd6f638
(anonymous) @ compiled_wasm.js.br:2
wrappedCallback @ compiled_wasm.js.br:2
r @ figma_app.min.js.br:16
```

I think I'm missing something, that's why I posted it here. But let me know if I should open another issue!

**Comment by timfish** [comment]
Hi @svallory, please open a new issue with more details. This seem unrelated to this issue.
