### ISSUE TITLE
Offline integration does not seem to work

### ISSUE THREAD

**Issue by chetbox** [getsentry/sentry-electron#369]
- [x] Review the documentation: https://docs.sentry.io/platforms/javascript/electron/
- [x] Search for existing issues: https://github.com/getsentry/sentry-electron/issues
- [x] Use the latest release: https://github.com/getsentry/sentry-electron/releases
  ⚠️ I am unable to use the latest release because of https://github.com/getsentry/sentry-electron/issues/363#issuecomment-930076320
- [x] Provide a link to the affected event from your Sentry account
  ⚠️ The event does not get sent to Sentry

## Versions + Platform

- [x] SDK version - `@sentry/electron@v2.4.0`
- [x] Electron version - `electron@v12.0.9`
- [x] Platform - `Linux`

## Description

We initialise Sentry like this as described [in the docs](https://docs.sentry.io/platforms/javascript/guides/electron/configuration/integrations/plugin/#offline):

```js
const { Offline: OfflineIntegration } = require('@sentry/integrations');

const { logger } = require('@sentry/utils');
logger.enable();

Sentry.init({
      dsn: '...',
      integrations: [new OfflineIntegration()],
});
```

If I turn off wifi and start the application I see the following log when I force an error from the main process:

```
Sentry Logger [Error]: Error while sending event: Error: net::ERR_INTERNET_DISCONNECTED
```

Forcing an error from the main process or from the renderer does not seem to cause an error to be logged to Sentry, even when restarting the application.

EDIT:

Forcing an error from a renderer process gives a different error, but when the machine becomes online:

```
Sentry Logger [Error]: Error while sending event: Error: net::ERR_NAME_NOT_RESOLVED
```

**Comment by timfish** [comment]
I've never looked at the `OfflineIntegration` so I'd guess it was never designed to work with the Electron SDK. 

It's certainly something that would be useful though so I'll look into it.

**Comment by timfish** [comment]
Just checked the code and it uses `localForage` which is browser only so this won't play very well with the Electron SDK.

The Electron SDK merges all context and breadcrumbs in the main process so you get the same data for both JavaScript and native crashes. The main process is nodejs so that integration simply won't work there.

We already handle queuing native crashes if there is no connection and it would make sense to do this for JavaScript errors too.

**Comment by chetbox** [comment]
Does this mean offline crashes will be stored and uploaded when online from the main process without the Offline plugin?

The [Electron docs](https://docs.sentry.io/platforms/javascript/guides/electron/configuration/integrations/plugin/#offline) suggest the Offline plugin is designed to work with Electron.

**Comment by timfish** [comment]
> Does this mean offline crashes will be stored and uploaded when online from the main process without the Offline plugin?

Currently only for native crashes. JavaScript errors are currently dropped if there is no connection.

> The Electron docs suggest the Offline plugin is designed to work with Electron.

I suspect that this is because the Electron docs are derived from the core JavaScript docs so much of the JavaScript stuff gets included too. I'll open an issue about this.
