### ISSUE TITLE
Use better defaults for some options

### ISSUE THREAD

**Issue by jan-auer** [getsentry/sentry-electron#37]
- **release** - `app.getName()` + `app.getVersion()`
- **environment** - `process.defaultApp ? 'development' : 'packaged'`
- **user.id** - `node-machine-id.machineId()`

**Comment by timfish** [comment]
After suggesting  `node-machine-id` I found [this issue](https://github.com/automation-stack/node-machine-id/issues/27) which could become a pain and we don't require anything quite so persistent. 

Maybe another `Store` instance with a uuid will be enough.

**Comment by jan-auer** [comment]
I think we'll leave the machine ID out. Besides, that should rather be in `app.device_app_hash` and the `user.id` should identify the authenticated user, if the app has such a concept.
