### ISSUE TITLE
Show correct Electron version in Sentry

### ISSUE THREAD

**Issue by jan-auer** [getsentry/sentry-electron#40]
We should always send info on Electron framework (name, version, build) and send consistent OS information so that the corresponding context item can be shown in Sentry. Currently, it looks like this:

**Native Crash**:

<img width="757" alt="screen shot 2018-03-14 at 11 31 49" src="https://user-images.githubusercontent.com/1433023/37397284-7ea2cde8-277b-11e8-804c-eb1ec27efdb3.png">

**Renderer Error**:

<img width="758" alt="screen shot 2018-03-14 at 11 31 33" src="https://user-images.githubusercontent.com/1433023/37397280-7b38a056-277b-11e8-98e6-e11369e6a267.png">

**Main Processes Error**:

*nothing*

**Comment by timfish** [comment]
I also noticed that JavaScript exceptions in the renderer are classified as **Error** whereas in the main process they're classified as **Fatal**.

**Comment by jan-auer** [comment]
This will need a fix in Sentry.
