### ISSUE TITLE
Deepmerge import is broken in vite/rollup

### ISSUE THREAD

**Issue by artplan1** [getsentry/sentry-electron#403]
- [x] Review the documentation: https://docs.sentry.io/platforms/javascript/electron/
- [x] Search for existing issues: https://github.com/getsentry/sentry-electron/issues
- [x] Use the latest release: https://github.com/getsentry/sentry-electron/releases
- [ ] Provide a link to the affected event from your Sentry account

## Versions + Platform

- [x] SDK version - `@sentry/electron@v3.0.0-beta-3`
- [x] Electron version - `electron@v16.0.5`
- [x] Platform - `Windows/macOS/Linux`
- [x] Bundler - `Vite/Rollup`

## Description

Errors:
```bash
Cannot call a namespace ('deepMerge')
```

```bash
Sentry Logger [Error]: SentryError2: Event processing pipeline threw an error, original event will not be sent. Details have been sent as a new event.
Reason: TypeError: deepMerge is not a function
```

The way deepmerge is imported at https://github.com/getsentry/sentry-electron/blob/12058e46133f762bb7bdc873982727a3da813e88/src/common/merge.ts#L3 works incorrectly in Vite/Rollup - https://github.com/TehShrike/deepmerge/issues/102

Similar issue: https://github.com/vitejs/vite/issues/2261#issuecomment-808961321

Fix is to change import to intended: https://github.com/TehShrike/deepmerge/issues/102#issuecomment-384975231
```js
import deepmerge from 'deepmerge'
```

**Comment by timfish** [comment]
I've added an example test for vite/rollup and it works without any SDK changes:
https://github.com/getsentry/sentry-electron/pull/406

If you can supply an example where it doesn't work I'd be happy to take a look!
