### ISSUE TITLE
Custom Transactions are not showing in the Performance tab

### ISSUE THREAD

**Issue by umerkk** [getsentry/sentry-electron#418]
## Versions + Platform

- [ ] SDK version - `@sentry/electron@v3.0.0`
- [ ] Electron version - `electron@v13.6.3`
- [ ] Platform - `macOS`

## Description

`

    "@sentry/electron": "^3.0.0",
    "@sentry/integrations": "^6.17.0",
    "@sentry/node": "^6.17.0",
    "@sentry/react": "^6.17.0",
    "@sentry/tracing": "^6.17.0",
    "@sentry/types": "^6.17.0",
`

I am instrumenting custom transactions based on the docs however the transaction does not appear in the performance dashboard.
It is is capturing the default `Request` transaction from electron but not my custom one.
I do see in the logs that the transaction is started & finished but never sent to sentry.

My sampleRate & traceSampleRate is set to 1.

`

      enabled: true,
      debug: true,
      environment: Environment.Development,
      sampleRate: 1,
      tracesSampleRate: 1,
`

my code looks like:

`

    const Sentry = require('@sentry/node');

    async initSequence() {

      const transaction = Sentry.startTransaction({ name: 'InitSequence', op: 'task' });
      Sentry.getCurrentHub().configureScope((scope) => scope.setSpan(transaction));
    
      const initializeServicesSpan = transaction.startChild({ op: 'initializeServices' });
      await this.initializeServices();
      initializeServicesSpan.finish();
      transaction.finish();
    }
`

Here is what I see in logs
  
 Sentry Logger [Log]: [Tracing] starting task transaction - InitSequence 
 Sentry Logger [Log]: [Tracing] Finishing task transaction: InitSequence. 
 Sentry Logger [Log]: Sending 'transaction' request
 Sentry Logger [Log]: Successfully sent

**Comment by timfish** [comment]
Thanks for the detailed report. I'll take a look!

**Comment by timfish** [comment]
It looks like transaction spans are not getting serialised correctly when captured from the Electron main process.

Currently the docs only cover tracing in the renderer so I need to add some more details about configuring in the main process.

As in the [node.js performance docs](https://docs.sentry.io/platforms/node/performance/), you need to import `@sentry/tracing` for transactions to work as this hooks the tracking extension points in the SDK:

```ts
const Tracing = require('@sentry/tracing');
// Note: You MUST import the package for tracing to work
```

**However**, I've just tried this myself and it still doesn't appear to fix the serialisation issue so I will need to dig a bit deeper!

**Comment by umerkk** [comment]
Yeah i tried importing Tracing package but still it didn't work.

**Comment by umerkk** [comment]
Just for my knowledge, @timfish - how long does it take for the new release to be available with this fix?

**Comment by timfish** [comment]
I've triggered the release of `v3.0.2` so once the CI tests have passed, it just needs someone approving the release [here](https://github.com/getsentry/publish/issues/855).
