### ISSUE TITLE
Importing @sentry/electron without calling init() yields an error

### ISSUE THREAD

**Issue by andersk** [getsentry/sentry-electron#427]
- [x] Review the documentation: https://docs.sentry.io/platforms/javascript/electron/
- [x] Search for existing issues: https://github.com/getsentry/sentry-electron/issues
- [x] Use the latest release: https://github.com/getsentry/sentry-electron/releases

## Versions + Platform

- [x] SDK version - `@sentry/electron@3.0.3`
- [x] Electron version - `electron@17.1.0`
- [x] Platform - `Linux`

## Description

We call `init()` conditionally, so that our users have an option to turn off error reporting. This worked fine in `@sentry/electron@2.5.4`, but in `@sentry/electron@3.0.3`, when `init()` is not called, we get this console error in the renderer process from #377:

```
Fetch API cannot load sentry-ipc://sentry-electron.ping. URL scheme "sentry-ipc" is not supported.", source: …/node_modules/@sentry/electron/renderer/ipc.js (15)
Sentry SDK failed to establish connection with the Electron main process.
 - Ensure you have initialized the SDK in the main process
 - If your renderers use custom sessions, be sure to set 'getSessions' in the main process options
 - If you are bundling your main process code and using Electron < v5, you'll need to manually configure a preload script", source: …/node_modules/@sentry/electron/renderer/ipc.js (15)
```

`@sentry/electron` do nothing before `init()` is called (like the documentation [says](https://github.com/getsentry/sentry-electron/#usage)).

### Minimal reproducible example

**`index.js`**

```js
const Sentry = require("@sentry/electron");
const { app, BrowserWindow } = require("electron");

if (false /* we decided not to */) {
  Sentry.init({ dsn: "__DSN__" });
}

app.whenReady().then(() => {
  const win = new BrowserWindow({
    webPreferences: {
      preload: require.resolve("./preload.js"),
    },
  });
  win.loadURL("about:blank");
});
```

**`preload.js`**

```js
const Sentry = require("@sentry/electron");

if (false /* we decided not to */) {
  Sentry.init({ dsn: "__DSN__" });
}
```

**`package.json`**

```json
{
  "dependencies": {
    "@sentry/electron": "^3.0.3",
    "electron": "^17.1.0"
  }
}

**Comment by timfish** [comment]
Thank you for reporting this. I will change this so the relevant code is evaluated lazily.

Disabling the SDK by not initialising it might not be ideal. Usually you'll need to store your user preference somewhere, almost certainly on disk and this means delaying the start of the SDK until this value is loaded. It's preferable to start the SDK as early as possible to ensure you capture all errors and then use the `beforeSend` hook to disable sending. 

With the Electron SDK, everything is sent from the main process, so you would always `init` in the preload/renderer:

`preload.js`
```ts
const Sentry = require("@sentry/electron");
// You can actually leave the DSN/options out here because its not used in the renderer
Sentry.init();
```
and then in the main process use `beforeSend` to skip sending when the SDK is disabled:

`main`js`
```ts
async function sdkEnabled(): Promise<boolean> {
  // return whether sdk should send events
}

Sentry.init({ 
  dsn: "__DSN__",
  // beforeSend function is (event: Event) => Promise<Event | null>
  // If null is returned, the event will not be sent
  beforeSend: (event) => sdkEnabled().then(enabled => enabled ? event : null)
});
```
