### ISSUE TITLE
beforeSend callback not fire in renderer

### ISSUE THREAD

**Issue by onion7878** [getsentry/sentry-electron#437]
- [x] Review the documentation: https://docs.sentry.io/platforms/javascript/electron/
- [x] Search for existing issues: https://github.com/getsentry/sentry-electron/issues
- [x] Use the latest release: https://github.com/getsentry/sentry-electron/releases
- [x] Provide a link to the affected event from your Sentry account

## Versions + Platform

SDK version - `@sentry/electron": "^3.0.4`
Electron version - `electron": "17.1.2`
Platform - `Windows`

## Description

step:

1. use electron forge create project
`yarn create electron-app my-new-app --template=webpack`

2. add sentry/electron
3. in main.js:

```js
import * as Sentry from '@sentry/electron/main';

Sentry.init({
  dsn: 'https://xxx@xxx.ingest.sentry.io/xxx',
  debug: !app.isPackaged,
  beforeSend: (event, hint) => {
    console.log('main beforeSend');
    return null; // for test
  },
});
```
4. in renderer.js

```js
import * as Sentry from '@sentry/electron';

Sentry.init({
    beforeSend: (event, hint) => {
      console.log('renderer beforeSend');
      return null;
    },
  });

setTimeout(() => {
    myUndefinedFunction();
}, 3000)
```

5. `yarn start` and wait, terminal show `main beforeSend` but in devtools console cant see `renderer beforeSend'`

---

my intention is to use Feedback in the beforeSend in the rendering thread，Just like it says in the documentation：

https://docs.sentry.io/platforms/javascript/guides/electron/enriching-events/user-feedback/#integration

```js
const { init, showReportDialog } = require("@sentry/electron");

init({
  dsn: "https://examplePublicKey@o0.ingest.sentry.io/0",
  beforeSend(event) {
    // Check if it is an exception, if so, show the report dialog
    // **Note that this only will work in the renderer process, it's a noop on the main process**
    if (event.exception) {
      showReportDialog();
    }
    return event;
  },
});
```

but beforeSend is not fired in the rendering thread, so I can't implement it.

Is there any documented information that I missed or my implementation is not correct?

**Comment by timfish** [comment]
This SDK works by passing all events and scope changes from the renderer processes to the main process where they are merged with the main context. 

Nothing is passed from main to renderer which means that `beforeSend` in the renderer will not be hit.

I would be great if we can get the report dialog opening in a new BrowserWindow.

**Comment by onion7878** [comment]
Solved, thank you for your reply
