### ISSUE TITLE
Paths with spaces are not normalised correctly in node exceptions

### ISSUE THREAD

**Issue by timfish** [getsentry/sentry-electron#44]
Awaiting [this PR](https://github.com/getsentry/raven-node/pull/437) to make it into a release.

**Comment by jan-auer** [comment]
[This test](https://github.com/getsentry/sentry-electron/pull/43/files#diff-59c74a1eaad1a236348f8128f3d36f30R59) needs to be activated afterwards.

**Comment by timfish** [comment]
Fixed by v0.5.0 release
