### ISSUE TITLE
`electron.net` breadcrumbs are recorded for sending Sentry envelopes:

### ISSUE THREAD

**Issue by timfish** [getsentry/sentry-electron#453]
## Versions + Platform

- SDK version - `@sentry/electron@v3.x.y`
- Electron version - `all`
- Platform - `all`

## Description

`electron.net` breadcrumbs are recorded for sending Sentry envelopes:
![image](https://user-images.githubusercontent.com/1150298/160909533-f674da34-4f5c-4a0f-9784-7305114b3e53.png)

This code attempts to stop this but isn't working for some reason:
https://github.com/getsentry/sentry-electron/blob/cfeacf652bf6fdc8c026d2a6684ab9fcab733d6b/src/main/integrations/net-breadcrumbs.ts#L137-L139

**Comment by timfish** [comment]
This is a strange once since I can't reproduce this locally 🤔

**Comment by timfish** [comment]
> Seems like the request headers are only added for the store endpoint and node?

I ran the e2e tests and logged the headers at the test server and logged at the point where we bail out for Sentry requests and everything I saw was as expected 

> Can we grab details about the dsn/URL from options and try to match that way?

Yep, that might be more reliable.

**Comment by timfish** [comment]
Now I'm thinking it may be related to the ordering/execution here:
https://github.com/getsentry/sentry-electron/blob/75a3b3bbd0ce98f2506b74d3a2b3cf55b11ed2cf/src/main/integrations/net-breadcrumbs.ts#L134-L139

`originalRequestMethod.apply` is calling and starting the request. Can it throw at this point and is this causing #454?

I'm only actually seeing `electron.net` breadcrumbs for failed requests. If the request fails, maybe the headers are missing and the check fails?

**Comment by AbhiPrasad** [comment]
@timfish this still applies? Or can we close?

**Comment by timfish** [comment]
Yep, close!
