### ISSUE TITLE
Broken exports map

### ISSUE THREAD

**Issue by Kiyozz** [getsentry/sentry-electron#462]
- [x] Review the documentation: https://docs.sentry.io/platforms/javascript/electron/
- [x] Search for existing issues: https://github.com/getsentry/sentry-electron/issues
- [x] Use the latest release: https://github.com/getsentry/sentry-electron/releases
~~Provide a link to the affected event from your Sentry account~~

## Versions + Platform

- [x] SDK version - `@sentry/electron@v3.0.6`
- [x] Electron version - `electron@v18.0.1`
- [x] Platform - `macOS`

## Description

This issue [evanw/esbuild#2163](https://github.com/evanw/esbuild/issues/2163) describe the problem.

The exports map is broken. This lead of this problem

![https://user-images.githubusercontent.com/12450333/162207644-b643fe76-cff0-4a93-98f3-de5f6bc45869.png](https://user-images.githubusercontent.com/12450333/162207644-b643fe76-cff0-4a93-98f3-de5f6bc45869.png)

evanw said

>This package looks broken. The correct condition name for imports is import not module:

**Comment by timfish** [comment]
A fix for this has been released in 3.0.7
