### ISSUE TITLE
Some links in readme.md can not be opened normally

### ISSUE THREAD

**Issue by xuxunsheng** [getsentry/sentry-electron#466]
Deep Dive
[Configuration](https://docs.sentry.io/platforms/javascript/electron/#configuring-the-client)
[JavaScript Usage](https://docs.sentry.io/platforms/javascript/electron/)
[Native Usage](https://docs.sentry.io/platforms/javascript/electron/native/)
[Source Maps](https://docs.sentry.io/platforms/javascript/electron/sourcemaps/)[](https://github.com/getsentry/sentry-electron#resources)
Resources
[Releases](https://github.com/getsentry/sentry-electron/releases)
[Bug Tracker](https://github.com/getsentry/sentry-electron/issues)
[Example App](https://github.com/getsentry/sentry-electron/tree/master/example)

The link of "Native Usage" and  "Example App" can not be opened normally.

**Comment by timfish** [comment]
Thanks for reporting. I will fix these!
