### ISSUE TITLE
 SentryError: An event processor returned null, will not send event.

### ISSUE THREAD

**Issue by bayun2** [getsentry/sentry-electron#469]
## Versions + Platform

- [x] SDK version - `@sentry/electron@v3.0.7`
- [x] Electron version - `electron@v18.0.3`
- [x] Platform - `macOS`

## Description
```
webPreferences: {
      minimumFontSize,
      nodeIntegration: false,
      contextIsolation: true,
      preload: __dirname + '/preload.js',
}
```
In the main process
```
import * as Sentry from '@sentry/electron/main'
Sentry.init({
    dsn: 'xxxx',
})
setTimeout(() => {
  throw new Error('Some main error5678')
}, 5000)
```
in the proload.js
```
import "@sentry/electron/preload";
```
in the renderer process
```
import * as Sentry from '@sentry/electron/renderer'
Sentry.init({ debug: true })

setTimeout(() => {
  throw new Error('Some renderer error999')
}, 10000)
```
main log info
<img width="715" alt="image" src="https://user-images.githubusercontent.com/3183696/164064457-135a13e7-1f27-4c9d-a477-169f86b27af9.png">

renderer log info

<img width="1154" alt="image" src="https://user-images.githubusercontent.com/3183696/164064375-c9a17ab5-cbcd-4ceb-b6ed-9b020c054e8f.png">

Result
'Some main error5678' report to Sentry, But 'Some renderer error999' can't report to Sentry

**Comment by timfish** [comment]
I'm going to close this since `An event processor returned null` is expected in the renderer since events are intercepted and send via the main process.

Please open further issues for any other problems!
