### ISSUE TITLE
Improve size of dependencies

### ISSUE THREAD

**Issue by timfish** [getsentry/sentry-electron#47]
Most consumers of this library are not going to bundle it and its dependencies as they will access it directly from `node_modules`.

Currently it adds around 8MB to the app size and over 1MB to the compressed installer sizes of an empty Electron app. 

It looks like we could save around 75% of this if we didn't have to include the whole of `raven-js/dist`. 

![image](https://user-images.githubusercontent.com/1150298/37572777-5bedec86-2b10-11e8-836a-4d1b6ddd0afd.png)

**Comment by jan-auer** [comment]
Looping in @kamilogorek @HazAT. I was wondering if we should just bundle `raven-js` and `raven` manually instead of adding it as a node module. Still haven't looked at how Electron bundles files inside `node_modules`, but maybe we can just exclude those files somehow...

**Comment by timfish** [comment]
As far as I understand it, most electron packagers by default simply `prune --production` the dependencies before packaging and include the entire `node_modules` directory after that.

`electron-builder` allows us to apply glob expressions during packaging. Some of these are quite aggressive and would likely break things for others:
```yml
# exclude all those build artifacts while ensuring we have the native binary
- "!**/node_modules/*/build/*"
- "**/node_modules/*/build/**/*.node"
# exclude some other native things
- "!**/node_modules/**/{*.cc,*.c,*.h,*.obj,*.pdb}"
```

I haven't checked but assuming `@sentry/browser` is using `raven-js/dist/raven.js` I could add the following to exclude everything else in dist:
```yml
- "!**/node_modules/raven-js/dist/*"
- "**/node_modules/raven-js/dist/raven.js"
```

But if the output of `raven-js` changes it breaks the above.

**Comment by jan-auer** [comment]
I think it makes more sense to just check in a build of `raven.js` manually for now, until it is fully implemented in `@sentry/browser`.

**Comment by timfish** [comment]
Much improved by v0.5.0 release
