### ISSUE TITLE
Lost tracing & beforeSend hook stopped working after upgrading to latest version

### ISSUE THREAD

**Issue by ahmedmukhtar1133** [getsentry/sentry-electron#473]
## Versions + Platform

- [ ] SDK version - `^3.0.7`
- [ ] Electron version - `13`
- [ ] Platform - `macOS`

## Description

I've just upgraded this package to latest version (3.0.7 from 2.5.1), and noticed all the console logs, warns and errors are being reported from `instrument.js` as a result I can't keep trace from which file log, and warns are coming.

**Is there any way to disable this behavior?** As I want to report exceptions manually using  `Sentry.capureException`.

``` 
  var consoleError = console.error
  console.error = function() {
    var args = Array.prototype.slice.call(arguments)
    const error = reduceConsoleArgs(args)
        Sentry.captureException(error, { level: 'error' })
    return consoleError.apply(console, args)
  }
  
  -----------------------------------------------------
  
  const logWarn = log.warn
  log.warn = function() {
    var args = Array.prototype.slice.call(arguments)
    Sentry.addBreadcrumb({ category, ...translateArgs(args), timestamp: Date.now(), level: Sentry.Severity.warn })
    return logWarn.apply(log, args)
  }
  ```
  
  **Also beforeSend in renderer is not working anymore.**
  ```
  const Sentry = require('@sentry/electron/')
const sentryIssues = [] // global session array

function getConfig(version) {
  return {
    dsn: 'https://7099e9f9235f491587153e5195138d3c@sentry.io/1554144',
    release: 'Repeato-' + version + '-' + process.platform,
    integrations: [],
    // debug: true,
    beforeSend(event, hint) {
      console.log('CheckSentryMessage', hint, hint.originalException?.message)
      return null // do not report the error
    }
  }
}
module.exports = { getConfig, sentryIssues, Sentry }

  ```
  
<img width="1390" alt="image" src="https://user-images.githubusercontent.com/15345707/165147548-b53083fd-e178-4854-aff4-9ca28c420016.png">

**Comment by timfish** [comment]
> I've just upgraded this package to latest version (3.0.7 from 2.5.1), and noticed all the console logs, warns and errors are being reported from instrument.js as a result I can't keep trace from which file log, and warns are coming.
>
> Is there any way to disable this behavior? As I want to report exceptions manually using Sentry.capureException.

You can disable console breadcrumbs in the renderer via the `Breadcrumbs` integrations:
```ts
import { init, Integrations } from '@sentry/electron/renderer';

init({
  dsn: '__DSN__',
  integrations: [new Integrations.Breadcrumbs({ console: false })]
})
```

> Also beforeSend in renderer is not working anymore.

Events are not sent directly from the renderer so `beforeSend` is not called. You should use `beforeSend` in the main process.

**Comment by timfish** [comment]
I'm going to close this as there aren't any actions left to take. Feel free to open new issues if you come across anything else!
