### ISSUE TITLE
SentryMinidump: native crash report does not contain expected scope / context if a beforeSend function is supplied

### ISSUE THREAD

**Issue by bowswung** [getsentry/sentry-electron#481]
- [x] Review the documentation: https://docs.sentry.io/platforms/javascript/electron/
- [x] Search for existing issues: https://github.com/getsentry/sentry-electron/issues
- [x] Use the latest release: https://github.com/getsentry/sentry-electron/releases
- [ ] Provide a link to the affected event from your Sentry account

## Versions + Platform

- [x] SDK version - `@sentry/electron@v3.0.7`
- [x] Electron version - `electron@v16.0.10`
- [x] Platform - `Windows`

## Description

As in title - if you supply a `beforeSend` function then the default SentryMinidump integration will not correctly fill in the scope on the event when sending a crash report.

This may be intentional, but I couldn't find docs stating this. The problematic line is this one - https://github.com/getsentry/sentry-electron/blob/master/src/main/integrations/sentry-minidump/index.ts#L234 

which instead of giving the `beforeSend` function the `newEvent` that has been filled with scope, it passes the original `event`.

Fixing should be trivially to pass `newEvent` to `beforeSend` (we have patched this in locally and it seems to be working in the way we expect).

**Comment by timfish** [comment]
Thank you for reporting, I'll take a look!
