### ISSUE TITLE
Getting 403 error on any event with sentry v3

### ISSUE THREAD

**Issue by Amethystafyy282** [getsentry/sentry-electron#483]
- [x] Review the documentation: https://docs.sentry.io/platforms/javascript/electron/
- [x] Search for existing issues: https://github.com/getsentry/sentry-electron/issues
- [x] Use the latest release: https://github.com/getsentry/sentry-electron/releases
- [x] Provide a link to the affected event from your Sentry account

## Versions + Platform

- [ ] SDK version - `@sentry/electron@v3.0.7`
- [ ] Electron version - `electron@v16.0.6`
- [ ] Platform - `macOS`

## Description
- This is a selfhost WITH `http` protocol, idk if it must be `https`.
From This Issue: #275

Code:
```
import * as Sentry from '@sentry/electron';
Sentry.init({
    dsn: reportUrl,
    debug: true,
    autoSessionTracking: false,
    environment: process.env.NODE_ENV,
    release: app.getVersion(),
    beforeSend: (event) => {
        console.log('before send', event);
        return event;
    },
});
Sentry.captureMessage('Hello, world!');
Sentry.captureException(new Error('Good bye'));
Sentry.captureEvent({
    message: 'Manual',
});
```

Log:
```
Sentry Logger [Log]: Sending 'event' request
Sentry Logger [Warn]: Dropping request: HTTPError: HTTP Error (403)
    at ClientRequest.<anonymous> (/Volumes/Projects/msgr-client-electron/node_modules/@sentry/electron/main/transports/electron-net.js:139:36)
    at ClientRequest.emit (node:events:394:28)
    at ClientRequest.emit (node:domain:475:12)
    at SimpleURLLoaderWrapper.<anonymous> (node:electron/js2c/browser_init:101:6816)
    at SimpleURLLoaderWrapper.emit (node:events:394:28)
    at SimpleURLLoaderWrapper.emit (node:domain:475:12) {
  status: 'invalid'
}
```

**Comment by timfish** [comment]
What version of self hosted Sentry are you running?

**Comment by Amethystafyy282** [comment]
> What version of self hosted Sentry are you running?
> 
> SDK Version >= 2 requires Sentry Server >= v20.6.0

After upgrade from 9 to 22, event successfully sent. Thank you!
