### ISSUE TITLE
JS V7.beta-1 support

### ISSUE THREAD

**Issue by umerkk** [getsentry/sentry-electron#487]
Hi
Is current Electron SDK compatiable with the new Sentry JS SDK V7 (in beta)?

I am trying to use V7-beta.1 sdk (Node, React, Integrations, types) with Electron SDK.
However, it seems like the way integrations used to be added (as a FN) is throwing a type mismatch error which I cannot figure out.

Looks like the signature on `@sentry/integrations` are not compatible with what Electron SDK init function requires.

```
import * as Sentry from '@sentry/electron';
import { CaptureConsole, ExtraErrorData, Offline, Transaction } from '@sentry/integrations';
import { Integration } from '@sentry/types';

    Sentry.init({
      ...Config.APM.CLIENT_CONFIG,
      release: `${systemInfo.hubVersion()}`,
      integrations: (integrations) => [
        ...integrations,
        new CaptureConsole({ levels: ['error'] }),
        new ExtraErrorData({ depth: 3 }),
        new Offline({ maxStoredEvents: 20 }),
        new Transaction(),
      ],
      beforeSend: this.beforeSendHandler,
    });

```

![Screen Shot 2022-05-19 at 1 49 06 PM](https://user-images.githubusercontent.com/16906595/169364968-4f05cf8c-0898-40fb-b9a0-2dccca9e4265.png)

**Comment by AbhiPrasad** [comment]
Hey, thanks for writing in! Currently v7 of the JS SDK is not compatible with the Electron SDK, we are making the changes needed for this here: https://github.com/getsentry/sentry-electron/pull/471

**Comment by umerkk** [comment]
Wonderful!!!
 This is what i am really looking for.

Is there any timeline around this new release?

**Comment by timfish** [comment]
> Is there any timeline around this new release?

Bumping the underlying JavaScript SDKs to v7 will force a major version bump of the Electron SDK so it's likely to be weeks rather than days.
