### ISSUE TITLE
Missing `addAttachment` function

### ISSUE THREAD

**Issue by AuHau** [getsentry/sentry-electron#496]
## Versions + Platform

- [ ] SDK version - `@sentry/electron@v3.0.7`
- [ ] Electron version - `electron@v18.0.1`
- [ ] Platform - `macOS`

## Description

I am trying to attache some logs as attachments as per your [documentation](https://docs.sentry.io/platforms/javascript/guides/electron/enriching-events/attachments/#uploading-attachments) for this SDK, but I am getting `scope.addAttachment is not a function`.

**Comment by timfish** [comment]
This feature was added the the JavaScript SDKs in v7.

The Electron SDK is in the process of being upgraded here:
https://github.com/getsentry/sentry-electron/pull/471

**Comment by AuHau** [comment]
I see, well the fact that this is already part of the Electron documentation is quite confusing. Is there any ETA for the upgrade? Or is there any workaround to use that feature? For example, using the JS SDK@v7 alongside this Electron one?

**Comment by timfish** [comment]
Sorry the docs being mismatched is my fault since I forgot to gate the Electron docs when I added the new feature!

The upgrade will cause a major version bump of the Electron SDK due to transport changes but I would hope to have a beta out by next week.
