### ISSUE TITLE
SentryMinidump not using given environment

### ISSUE THREAD

**Issue by devinfoley** [getsentry/sentry-electron#497]
- [x] Review the documentation: https://docs.sentry.io/platforms/javascript/electron/
- [x] Search for existing issues: https://github.com/getsentry/sentry-electron/issues
- [x] Use the latest release: https://github.com/getsentry/sentry-electron/releases
- [] Provide a link to the affected event from your Sentry account

## Versions + Platform

- [x] SDK version - `@sentry/electron@v3.0.7`
- [x] Electron version - `electron@v17.4.2`
- [x] Platform - `macOS`

## Description

When I start `Sentry.init({ dsn: ..., environment: 'dev' })`, and trigger a crash, I can see in the resulting HTTP request that the default environment, `development` is used, instead of `dev`. Meanwhile, if I inspect the HTTP requests created by `MainProcessSession`, I can see that `dev` is used there, as expected. I've done a bit of debugging but haven't found what's causing the issue yet. `ElectronMinidump` works as expected, sending `dev` as the environment.

**Comment by timfish** [comment]
Fixed in 4.0.0-beta.1

**Comment by timfish** [comment]
Fixed in 4.0.0-beta.1
