### ISSUE TITLE
Can't Ignore Errors

### ISSUE THREAD

**Issue by tance77** [getsentry/sentry-electron#5]
There seems to be no options to ignore specific errors. At least as far as I'm reading. Is there a way of doing this?

https://docs.sentry.io/clients/javascript/config/

see ignoreErrors

**Comment by timfish** [comment]
Thank you for posting this issue. 

I'll make sure this is taken care of in #2 (Follow Sentry SDK guidelines).

**Comment by tance77** [comment]
https://github.com/timfish/electron-sentry/pull/6 not sure, but I tried to help. Seemed to be working. Could test a but more.

**Comment by timfish** [comment]
This will be possible with the @sentry/core API changes. Docs and release to come.

**Comment by akashnimare** [comment]
@timfish can you tell us what should we do to ignore particular errors?

**Comment by timfish** [comment]
The `ignoreErrors` property from Raven.js config still works for browser errors:

```
    Sentry.init({
      dsn: dsn,
      ignoreErrors: [/TimeoutError/, /AbortError/]
    });
```
