### ISSUE TITLE
Issues on Windows don't get merged because of user path

### ISSUE THREAD

**Issue by SpaceK33z** [getsentry/sentry-electron#503]
- [x] Review the documentation: https://docs.sentry.io/platforms/javascript/electron/
- [x] Search for existing issues: https://github.com/getsentry/sentry-electron/issues
- [x] Use the latest release: https://github.com/getsentry/sentry-electron/releases
- [x] Provide a link to the affected event from your Sentry account

## Versions + Platform

- [x] SDK version - `@sentry/electron@v3.0.7`
- [x] Electron version - `electron@v18.2.3`
- [x] Platform - `Windows`

## Description

In my Electron app issues are not properly merged from Windows users.
In the app I'm basically doing:

```
Sentry.captureException(new Error('Tried to send recordingEvent [...]'));
```

These are the duplicate issues that I get in Sentry:

![Screenshot 2022-07-06 at 12 45 30](https://user-images.githubusercontent.com/533616/177535131-5b9f62bd-6d34-4f7e-955d-0472233dc34a.png)

I can see the full user path as a description. I'd expect `C:\Users\myusername` to be replaced to e.g. `~` (or something else), and I guess then it can be merged properly? On macOS this doesn't seem to be an issue.

Or is there another way to rewrite the errors so this user path doesn't get included?

**Comment by timfish** [comment]
Paths should already be normalised and I haven't seen this so far with any apps that I support.

Could you supply a minimal example repository so I can look into how this path is ending up in an event?

**Comment by timfish** [comment]
@SpaceK33z  Did you manage to fix this issue?

If not, could you share a link to an affected event?

**Comment by timfish** [comment]
I've managed to track this down to paths getting into the `module` field in the stack trace frames. This appears to be caused by the `app.asar` part of the path but I need to investigate further.

**Comment by SpaceK33z** [comment]
@timfish Sorry for not responding anymore, thanks so much for tracking down this issue!!
