### ISSUE TITLE
Capture performance tracing via Electron `contentTracing` API

### ISSUE THREAD

**Issue by timfish** [getsentry/sentry-electron#504]
Electron includes a [`contentTracing`](https://www.electronjs.org/docs/latest/api/content-tracing) API which allows you to capture traces in the Chromium json [trace event format](https://docs.google.com/document/d/1CvAClvFfyA5R-PhYUmn5OOQtYMH4h6I0nSsKchNAySU/preview#). 

Could this be parsed and converted to format suitable for submitting to Sentry?

**Comment by timfish** [comment]
> IIrc that format was quite heavyweight

Indeed it can be, although it looks like you have full control of the categories that are captured so it might be possible to keep it slimmed down.

> Would be great if we could have a few example profiles

I'll see what I can do!

> but I assume that the startProfiling/stopProfiling are electron bindings to the v8 cpu and memory profiler?

Yes, as far as I understand it, it hits up the same code as Chrome dev tools

**Comment by JonasBa** [comment]
> Indeed it can be, although it looks like you have full control of the categories that are captured so it might be possible to keep it slimmed down.

That is great, we can hopefully trim it down to the bare minimum.

> Yes, as far as I understand it, it hits up the same code as Chrome dev tools
From my investigations, the direct output of the CPU profiler (when interfacing with node bindings) is not a chrometrace like format, it is instead more like a call graph (see [GetTopDownRoot method](https://v8docs.nodesource.com/node-18.2/db/d79/classv8_1_1_cpu_profile.html#a0928ddea256ae72a3a7b8a5d18daf6f1))

I'm actually wondering if we could avoid using the electron API and just import our own profiling sdk for node. I know very little about Electron, but the idea that profiling interface is re-exposed through Electron makes me think that our own bindings would not work.

**Comment by timfish** [comment]
> just import our own profiling sdk for node

In Electron you have the main root node process that is mainly used for opening and taking care of windows and orchestrating IPC. Each window (a "renderer") is essentially a Chromium tab and with the default configuration there is no node.js available in these. They highly discourage enabling node.js in the browser windows because of the many security implications when mixed with remote content!

There are ways to expose node.js functionality into the browser windows but this is via an isolated context (I think using the same underlying tech as Chromium extensions). However this isolated context probably makes it useless for things like tracing where I'm guessing globals and things get patched, modified etc.

**Comment by AbhiPrasad** [comment]
Going to close this for now for clean-up, we can re-visit later.

**Comment by JonasBa** [comment]
Just a note here, but adding support for trace format would also enable tracing of typescript compiler (the output of --generateTrace is a series of open/close events). I must have forgotten about this issue, but we have in fact experimented with adding support for this a while back and were actually able to visualize this format (see https://github.com/getsentry/sentry/pull/31705). Sadly, we never added proper support for it via ingest and it was more of a hack to make it work, but this is something we could revisit. 

Iirc one issue with the evented format is the cost associated with it, as it is often generated by deterministic profilers, which means we could be looking at magnitudes more data and cost associated with it.

**Comment by timfish** [comment]
> one issue with the evented format is the cost associated with it

I think this will be the case with the Electron API
