### ISSUE TITLE
Attach screenshots with the SDK

### ISSUE THREAD

**Issue by AbhiPrasad** [getsentry/sentry-electron#505]
Now that we have mobile screenshots, let's do it for desktop! https://blog.sentry.io/2022/07/07/introducing-mobile-screenshots-and-suspect-commits/

https://develop.sentry.dev/sdk/features/#screenshots

This will have to be **opt-in**. We can configure this through an `attachScreenshot` option, and add a BIG warning about PII

**Comment by timfish** [comment]
There are a few things to consider with this feature and Electron. 

- We cannot capture screenshots of windows that have native crashed.
- An app can have multiple windows. Which should we capture?
- For some crashes, screenshots probably don't make any sense (I'm thinking of things GPU crashes here)

**Comment by AbhiPrasad** [comment]
> An app can have multiple windows. Which should we capture?

Can we send screenshots for every window? The spec: `Subsequent screenshots in the same event should be named screenshot-n, where n is the screenshot number starting with 2`. Maybe this can be user configurable 🤔.

Whatever we decide here will propogate to other desktop platforms, so we have the freedom to make the call.

> For some crashes, screenshots probably don't make any sense (I'm thinking of things like GPU crashes here)

On mobile we only send screenshots for errors, not messages. I think we can just send it for all errors/crashes to start, and then refine it down as we get feedback.

**Comment by timfish** [comment]
Rather than adding a `attachScreenshot` option, would it not be better to use a non-default included integration? 

That way we can keep the potential PII code completely excluded unless it's specifically included.

**Comment by AbhiPrasad** [comment]
I think we can include the integration by default as long as we are sure that it's all locked behind the `attachScreenshot` option.
