### ISSUE TITLE
Errors while process crashes in native add-on

### ISSUE THREAD

**Issue by haoxi911** [getsentry/sentry-electron#507]
## Versions + Platform

- [x]  SDK version - @sentry/electron@v3.0.7
- [x]  Electron version - electron@v19.0.8
- [x]  Platform - macOS

## Description

Can anyone help to take a look at this [issue](https://sentry.io/organizations/simplified-it-products/issues/3411630838/?project=6468531&query=is%3Aunresolved)? It says there is an error while processing the event: **sdkProcessingMetadata: Discarded unknown attribute**

When I run `npx sentry-cli sourcemaps explain b280d03d3e6c486691baa0d38b602f6d`, it gives the following output:
```
✔ Fetched data for event: b280d03d3e6c486691baa0d38b602f6d
✔ Event has release name: darwin@4.5.5
✔ Event has a valid exception present
✔ Event has a valid stacktrace present
✖ Event exception stacktrace top frame has incorrect abs_path (valid url is required). Found /Users/Kevin/Projects/Electron/.../addon/src/feature/mac/PhotosSearch.m
```

The symbol was resolved properly though, just curious if we can get rid of these errors.

**Comment by AbhiPrasad** [comment]
We have to make sure `sdkProcessingMetadata` is stripped before it is sent to the server.

Perhaps we have to strip it here? https://github.com/getsentry/sentry-electron/blob/f11ab00774db8e85417d08f5f243bf9c290520a0/src/main/integrations/electron-minidump.ts#L162
