### ISSUE TITLE
Add support for Culture Context

### ISSUE THREAD

**Issue by AbhiPrasad** [getsentry/sentry-electron#525]
https://develop.sentry.dev/sdk/event-payloads/contexts/#culture-context

The [language field in device context was deprecated](https://develop.sentry.dev/sdk/event-payloads/contexts/#device-context),

**Comment by AbhiPrasad** [comment]
upstream changes will be published as part of https://github.com/getsentry/publish/issues/1327

**Comment by AbhiPrasad** [comment]
Released in `7.12.0` - https://github.com/getsentry/sentry-javascript/releases/tag/7.12.0

**Comment by timfish** [comment]
Now most of the context has moved to `@sentry/node`, I just need to work out how to bring those changes into the Electron SDK without making it a breaking change!

**Comment by timfish** [comment]
Is removing the existing `event.contexts.device.language` considered a breaking change?

**Comment by timfish** [comment]
I'm tempted to leave this until the next major version bump since adding this now would simply involve copying code from `@sentry/node` and deleting it for v5.

**Comment by AbhiPrasad** [comment]
> Is removing the existing event.contexts.device.language considered a breaking change?

This is not indexed by Sentry, so I don't think it is.

> I'm tempted to leave this until the next major version bump since adding this now would simply involve copying code from @sentry/node and deleting it for v5.

Yeah I think that's fine, we can leave it for the next major bump
