### ISSUE TITLE
Sourcemaps Problem ReactJS + Electron

### ISSUE THREAD

**Issue by cristiano-linvix** [getsentry/sentry-electron#530]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

I'm sending the sourcemaps through sentry-cli and I'm using the sourcemaps explain to identify failures, but sentry doesn't identify the artifacts it is returning in partially matching.

### Expected Result

It should locate the sourcemaps correctly.

### Actual Result

✔ Fetched data for event: 2d7866133c4d402db3f552f6df61af40
✔ Event has release name: pdv-nfce@1.0.55
✔ Event has a valid exception present
✔ Event has a valid stacktrace present
✖ Uploaded artifacts do not include entry: ~/C:/LINVIX%20Sistemas/PDV%20NFCe/resources/app.asar/build/static/js/main.a7b02a94.js
ℹ Found entry with partially matching filename: ~/C:/Linvix%20Sistemas/PDV%20NFCe/resources/app.asar/build/static/js/main.a7b02a94.js. Make sure that that --url-prefix is set correctly.

**Comment by AbhiPrasad** [comment]
Closing this issue for cleanup. Please re-open if this still applies. Thanks!
