### ISSUE TITLE
Why use a synchronous API (writeFileSync) for file writing

### ISSUE THREAD

**Issue by niugm** [getsentry/sentry-electron#534]
Sentry is a great project, we use it on the Electron client, and there's a question I don't quite understand: Why use a synchronous API (writeFileSync) for file writing?On some low-end devices, especially computers that use mechanical disks, the main process execution can be blocked

**Comment by timfish** [comment]
Thanks for opening an issue about this.

It looks like `writeFileSync` is used in the `Store` which has gone virtually untouched for over 3 years when it was pulled from `@sentry/utils`. 

I did quickly have a go at making the store entirely async and got some test failures, so it looks like the session handling is at least partially relying on the sync writing. 

<img width="534" alt="image" src="https://user-images.githubusercontent.com/1150298/184613339-6e5e2a41-2c89-445d-b669-4ff9391800c5.png">

**Comment by niugm** [comment]
> 

Thank you for your attention to this feedback, looking forward to the optimized version

**Comment by AbhiPrasad** [comment]
Re-opening as fix was reverted in https://github.com/getsentry/sentry-electron/pull/552
