### ISSUE TITLE
`ERR_UNKNOWN_URL_SCHEME` in internal developer tools

### ISSUE THREAD

**Issue by eelco** [getsentry/sentry-electron#546]
- [x] Review the documentation: https://docs.sentry.io/platforms/javascript/electron/
- [x] Search for existing issues: https://github.com/getsentry/sentry-electron/issues
- [x] Use the latest release: https://github.com/getsentry/sentry-electron/releases
- [ ] Provide a link to the affected event from your Sentry account

## Versions + Platform

- [x] SDK version - `@sentry/electron@v4.0.0`
- [x] Electron version - `electron@v20.0.2`
- [x] Platform - `macOS`

## Description

I’m upgrade to the latest @sentry/electron from a 2.x version, but I run into trouble.

I’ve tried both importing using `@sentry/electron` and using the `…/main` and `…/renderer` imports, but I get errors about `ERR_UNKNOWN_URL_SCHEME`:
<img width="858" alt="image" src="https://user-images.githubusercontent.com/12829/189134903-6cfb8325-1f4c-4380-a972-e96d7a95332f.png">

How do I resolve this? We build the app using a pretty standard Electron Forge setup, the only “odd” thing we have is a plugin to use ESBuild to compile the TypeScript app.

**Comment by timfish** [comment]
Not entirely sure what's going on here as I appears that the SDK is not initialised in the main process.

If you set the `debug` option to true do you see output in the main process that suggest the SDK it fully initialised in the main process?
```
init({
  dsn: '__YOUR_DSN__',
  debug: true
})

There are a couple of working [examples](https://github.com/getsentry/sentry-electron/tree/master/examples) for Electron Forge.

**Comment by eelco** [comment]
This is what it logs:
<img width="952" alt="image" src="https://user-images.githubusercontent.com/12829/189643947-1c183ecd-0275-4819-9690-3f93824868cc.png">

The only other thing I can think off is that we already do use a custom protocol/scheme in the application, but even after disabling that code (and config) it still does not work.

From the debug messages above I did get the impression that adding the preload import might help, and indeed, after including that the error messages went away.
