### ISSUE TITLE
Sentry Issue - Not seeing source map / code file in the stack trace. 

### ISSUE THREAD

**Issue by chintsan** [getsentry/sentry-electron#567]
Please can you let know what needs to be done to start seeing source code ? 

Having a react app and have done needful to create release, source maps etc. using webpack for bundling.

Details as below. 

Stack trace as below. **_doesn't give option to expand stack trace._** 

<img width="1211" alt="Screen Shot 2022-10-01 at 9 23 54 am" src="https://user-images.githubusercontent.com/15031528/193376251-40baa014-d8e1-43a5-852d-2a1ae56b6145.png">

Release artifcats - file in question is present as attached along with source map.

<img width="1195" alt="Screen Shot 2022-10-01 at 10 43 51 am" src="https://user-images.githubusercontent.com/15031528/193376386-b7d98bcc-e96c-4cfe-a88d-99416485057b.png">
<img width="1225" alt="Screen Shot 2022-10-01 at 10 43 40 am" src="https://user-images.githubusercontent.com/15031528/193376387-8a8d6217-dbec-494d-93a4-2b133e17a894.png">

Webpack / output structure. public folder has all minified js 

<img width="251" alt="Screen Shot 2022-10-01 at 10 46 23 am" src="https://user-images.githubusercontent.com/15031528/193376468-fc0b5fff-9b69-417f-9fd3-ad12a44cfd90.png">

_Originally posted by @chintsan in https://github.com/getsentry/sentry-electron/issues/54#issuecomment-1264175451_

**Comment by kamilogorek** [comment]
Stacktrace frame is already pointing to a `.tsx` file, which most likely means that you are using `source-map-support` package, either directly or indirectly. And because of that, stacktrace given to sentry is already pre-resolved, which we than cennot use for our own proceseeing.

See warning at https://docs.sentry.io/platforms/node/sourcemaps/generating/

**Comment by chintsan** [comment]
yes we are using source-map-support. if i understand correctly, in this case we won't get stack trace resolved from sentry at all ?

**Comment by kamilogorek** [comment]
That is correct.

**Comment by chintsan** [comment]
thank you @kamilogorek .
