### ISSUE TITLE
Should you use private or public DSN?

### ISSUE THREAD

**Issue by steverandy** [getsentry/sentry-electron#58]
Just saw the updated documentation on sentry website for electron integration.

Initally I thought that you must use private DSN. But in the new doc, the example uses public DSN.
Is it ok to use public DSN for main an renderer process? Is there any downside?

**Comment by jan-auer** [comment]
Hi @steverandy, sorry for the confusion. This actually has changed with the last release. Private DSNs will be completely deprecated for all SDKs and removed from Sentry in near future. You can, but don't have to use private DSNs after upgrading to the latest version. 

Note that this also requires hosted Sentry. On-premise installations will need to continue to use the private DSN until the next release. I will add a section on this to docs.

**Comment by lsmith77** [comment]
https://docs.sentry.io/platforms/javascript/guides/vue/ still refers to `__PUBLIC_DSN__` which confused me .. but if I understand this ticket properly .. as a new user of sentry.io, there is no such thing as a private DSN anymore.

**Comment by jan-auer** [comment]
@lsmith77 This is actually a typo in our docs and should render the actual DSN of your project. You can just use the regular DSN.
