### ISSUE TITLE
beforeSend is now using the current tags when sending crash dumps from previous sessions

### ISSUE THREAD

**Issue by schontz** [getsentry/sentry-electron#585]
- [x] Review the documentation: https://docs.sentry.io/platforms/javascript/electron/
- [x] Search for existing issues: https://github.com/getsentry/sentry-electron/issues
- [x] Use the latest release: https://github.com/getsentry/sentry-electron/releases
- [x] Provide a link to the affected event from your Sentry account

## Versions + Platform

- [x] SDK version - `@sentry/electron@v4.1.0`
- [x] Electron version - `electron@v18.1.0`
- [x] Platform - `macOS`

## Description

When a crash occurs, it may not be sent to Sentry until the app restarts. In that situation, it used to send the previous session's tags/context to be sent with the event. 

### How it _used_ to work in 4.0.2 (expected result):

1. Set a session-specific tag, e.g.:
  ```
setTag('session', myAppSession); 
  ```
2. App crashes
3. Restart app, with a new `myAppSession` value
4. Inspect event in `beforeSend`:
  ```
  beforeSend: (event) => {
    if (myAppSession !== event.tags.myAppSession) {
      console.log('this event was on a different session');
    }
  }
```

### How it works in 4.1.0 (actual result):

`event.tags.myAppSession` now is the same as the current session's. I assume the breadcrumbs may be the same as well?

**Comment by timfish** [comment]
The only this that could have caused this regression is the change to using a fully async store. I'll do some testing and see if I can pin down the cause.
