### ISSUE TITLE
Sentry.init() causes app to hang on arm64

### ISSUE THREAD

**Issue by Gmentsik** [getsentry/sentry-electron#597]
- [x] Review the documentation: https://docs.sentry.io/platforms/javascript/electron/
- [x] Search for existing issues: https://github.com/getsentry/sentry-electron/issues
- [x] Use the latest release: https://github.com/getsentry/sentry-electron/releases
- [ ] Provide a link to the affected event from your Sentry account

## Versions + Platform

- [x] SDK version - `@sentry/electron@v4.1.2`
- [x] Electron version - `electron@v21.3.1`
- [x] Platform - `Ubuntu 22.04.1 LTS (GNU/Linux 5.15.0-1018-raspi aarch64)`

## Description

When deploying an electron-app which calls Sentry.init() on a RPi, the app seems to stop right at the line the init ist called.
The only log that is printed is:

```
chrome_crashpad_handler: --database is required
Try 'chrome_crashpad_handler --help' for more information.
[9860:1125/163121.082983:ERROR:socket.cc(120)] recvmsg: Connection reset by peer (104)
```

```
Sentry.init(SentryConfig);
```

is the first line in the code, if I remove it, the app starts up fine.

**Comment by Gmentsik** [comment]
Opened the issue too quickly, for reference: the error was caused by the ~/.config/AppName folder was owned by `root`, which causes this kind of error. I'm not sure why Sentry.init has surfaced this error.

**Comment by timfish** [comment]
We write temporary data to a `sentry` directory within the apps data directory.

Maybe we should handle this.

Will an Electron app run correctly with permissions like that?

**Comment by Gmentsik** [comment]
My electron app is super simple, so I wouldn't take it for granted. Only fs operation I did before is reading a config file, which worked.

Would be still nice to have any output or clue what's wrong.

**Comment by timfish** [comment]
I'm going to re-open this and improve the behaviour in this case

**Comment by Gmentsik** [comment]
Let me know if you need further info, although it should be fairly easy to reproduce.

**Comment by timfish** [comment]
I can't reproduce hanging. Did you get any error output in the console?

**Comment by Gmentsik** [comment]
I didn't get any outout except the one above. I'm not sure what state the app was in, electrons AppReady wasn't triggered for sure.

**Comment by timfish** [comment]
Oh sorry, I completely missed that in the description. It looks like this error is coming directly from Electron and no doubt due to the permissions. 

I just double checked our file read/write code and everything is wrapped in try/catch so it shouldn't cause any issues.

This can safely be closed!
