### ISSUE TITLE
How to set autoBreadcrumbs in main?

### ISSUE THREAD

**Issue by lanistor** [getsentry/sentry-electron#599]

**Comment by timfish** [comment]
I'm going to need a bit more information to be able to help you.

**Comment by lanistor** [comment]
@timfish By [original Sentry](https://docs.sentry.io/clients/javascript/config/), we can set `autoBreadcrumbs` to disable some measures, such as `xhr` , but `sentry-electron` cannot support it, using `@sentry/electron` or `@sentry/electron/main`, cannot set `autoBreadcrumbs` to disable `xhr`.

**Comment by timfish** [comment]
`@sentry/electron/renderer` uses `@sentry/browser` where these options are valid.
`@sentry/electron/main` uses `@sentry/node` plus some additional Electron specific integrations which have different options.

Which main process breadcrumbs are you attempting to disable?

To disable specific breadcrumbs integrations (like `ElectronBreadcrumbs`, `Net`, `Console`, `Http`, etc) you should filter them like:

```ts
init({
  dsn: '__DSN__',
  integrations: (integrations) => integrations.filter(i => i.name !== 'Console` && i.name !== 'ElectronBreadcrumbs')
});
```

**Comment by lanistor** [comment]
@timfish This seem cannot work. I still can find lots of logs in renderer's debug console panel.

I use Sentry.init in both main and renderer, Is this right?

```js
Sentry.init({
  environment: __BUILD_ENV__,
  dsn: 'https://xxx.ingest.sentry.io/5568600',
  integrations: (integrations) => integrations.filter(i => i.name !== 'Console' && i.name !== 'ElectronBreadcrumbs'),
});
```

**Comment by timfish** [comment]
The main and renderer process use different Sentry SDKs and when using a custom configuration it can be simpler to `init` them in separate files:

`sentry-main.js`
```ts
import { init } from '@sentry/electron/main';

init({
  environment: __BUILD_ENV__,
  dsn: 'https://xxx.ingest.sentry.io/5568600',
  integrations: (integrations) => integrations.filter(i => i.name !== 'Console' && i.name !== 'ElectronBreadcrumbs' && i.name !== 'Http' && i.name !== 'Net'),
});
```

It's worth noting that in the renderers, it is not required to supply `dsn` or `release` since all events are sent via the main process.

`sentry-renderer.js`
```ts
import { init } from '@sentry/electron/renderer';

init({
  autoBreadcrumbs: false
});
```

**Comment by timfish** [comment]
I'm going to close this as resolved.

I'm often in the #electron channel in the Sentry Discord if you have any more questions.
https://discord.com/channels/621778831602221064/623415030867820554

**Comment by lanistor** [comment]
> The main and renderer process use different Sentry SDKs and when using a custom configuration it can be simpler to `init` them in separate files:
> 
> `sentry-main.js`
> 
> ```ts
> import { init } from '@sentry/electron/main';
> 
> init({
>   environment: __BUILD_ENV__,
>   dsn: 'https://xxx.ingest.sentry.io/5568600',
>   integrations: (integrations) => integrations.filter(i => i.name !== 'Console' && i.name !== 'ElectronBreadcrumbs' && i.name !== 'Http' && i.name !== 'Net'),
> });
> ```
> 
> It's worth noting that in the renderers, it is not required to supply `dsn` or `release` since all events are sent via the main process.
> 
> `sentry-renderer.js`
> 
> ```ts
> import { init } from '@sentry/electron/renderer';
> 
> init({
>   autoBreadcrumbs: false
> });
> ```

Sorry for the late reply, this cannot work, i still got lots of log report of http.

**Comment by timfish** [comment]
> Sorry for the late reply, this cannot work, i still got lots of log report of http.

Do you have an example of the breadcrumb captured?
