### ISSUE TITLE
Best approach for integrating Sentry into a vscode extension w/ webview & LSP server

### ISSUE THREAD

**Issue by riotrah** [getsentry/sentry-electron#611]
- [x] Review the documentation: https://docs.sentry.io/
- [x] Search for existing issues: https://github.com/getsentry/sentry-javascript/issues
- [ ] Use the latest release: https://github.com/getsentry/sentry-javascript/releases
- [ ] Provide a link to the affected event from your Sentry account

## Package + Version

- [x] `@sentry/browser`
- [x] `@sentry/node`
- [ ] `raven-js`
- [ ] `raven-node` _(raven for node)_
- [x] other: `@sentry/react`

### Version:

```
3.3.6
```

## Description

Hi!

Tried to find info elsewhere. Open to creating an issue elsewhere if appropriate.

TLDR:

1. What's the best way to instrument a vscode (thus electron) extension with an iframe-embedded webview and language server implemented in node?
2. What's the best to dedupe by error?

Details:

I'm working on a vscode extension. It has a react-based webview component, and also features a language server. I want to instrument the extension in three places: the webview, the language server, and the vscode extension code component that launches the language server and manages the webview.

I didn't know whether the electron sdk was appropriate, but I tried:

1. The react sdk for the webview
2. The node sdk for the language server
3. The node sdk for the extension code

It appeared to work until 2 issues surfaced:

1. The node sdk for the language server and extension code report errors from other, unrelated extensions to Sentry.io. It also uses the console statements of other, unrelated extensions as breadcrumbs.
2. The language server is flooding Sentry.io with _thousands_ of error events in minutes-long bursts. Eg ~2 thousand over a few minutes of activity, and ~12 thousand over an hour, in some cases.

**Comment by smeubank** [comment]
transfering here since it might be useful to more folks on this repo that might look here,

**Comment by smeubank** [comment]
i don't see anymore responses since the last comments from quite some time ago, closing but feel free to reopen- or creat a discussion around this topic

cool use case here!
