### ISSUE TITLE
missing util.promise shim in context.ts

### ISSUE THREAD

**Issue by hibiyasleep** [getsentry/sentry-electron#64]
[src/context.ts](https://github.com/getsentry/sentry-electron/blob/20d96580593d98ab062f5e827f680025843e3b62/src/context.ts#L5) didn't require `util.promisify/shim`, unlike [src/uploader.ts](https://github.com/getsentry/sentry-electron/blob/0b45fca1c7ca6b260ce17dff0de91aad9d2bebca/src/uploader.ts#L2) do.

because of this, this moudle doesn't work on electron 1.8.x and/or below.

**Comment by timfish** [comment]
I'm using the latest release in Electron 1.8.4 without any issues. What error are you getting?

**Comment by jan-auer** [comment]
Will be published with the next release today.
