### ISSUE TITLE
App takes a long time to close when machine has network but no internet

### ISSUE THREAD

**Issue by chetbox** [getsentry/sentry-electron#643]
### Is there an existing issue for this?

- [X] I have checked for existing issues https://github.com/getsentry/sentry-javascript/issues
- [X] I have reviewed the documentation https://docs.sentry.io/
- [X] I am using the latest SDK release https://github.com/getsentry/sentry-javascript/releases

### How do you use Sentry?

Sentry Saas (sentry.io)

### Electron SDK Version

4.2.0

### Electron Version

19.1.9

### What platform are you using?

MacOS

### Steps to Reproduce

1. Connect your machine to one network only, an access point that does **not** have access to the internet
2. Open Electron app
3. Close Electron app

### Expected Result

The application closes near-instantly

### Actual Result

The application hangs for 30s - 60s after the `will-quit` Electron event. Turning on Sentry logging shows me this:

```
Sentry Logger [Log]: [MainProcessSession] Exit Handler
Sentry Logger [Log]: Ending session
Sentry Logger [Log]: Sending 'session' request
... many seconds later ...
Sentry Logger [Log]: Error sending Error: net::ERR_NETWORK_CHANGED
Sentry Logger [Log]: Queuing request
Sentry Logger [Log]: [MainProcessSession] Error ending session Error: net::ERR_NETWORK_CHANGED
```

Note that for us it's very common for our app (https://cogs.show) to be used on a network but without internet connectivity, or with infrequent internet connectivity.

This issue is related but doesn't cover the case where the machine has a network but no connection to the Sentry servers: https://github.com/getsentry/sentry-electron/issues/438

Is there a way of applying/reducing the timeout of the Sentry logic in `will-quit`?

Is this an appropriate workaround?

```ts
app.on('will-quit', () => process.exit())
```

**Comment by timfish** [comment]
Sorry that's not great, I guess we need to pass a timeout to `flush` here:
https://github.com/getsentry/sentry-electron/blob/f979333f2013e77d8101d5217fcf59a4a18efc45/src/main/sessions.ts#L57

I'll fix this and add a test to confirm it's fixed.

> Is this an appropriate workaround?

This issue is caused by flushing of sessions. The easiest way to workaround this is to disable tracking of sessions via:
```ts

Sentry.init({
  dsn: '__DSN__',
  autoSessionTracking: false
});
```
Overriding `will-quit` might also work but it could also skew your session stats.

**Comment by chetbox** [comment]
Thanks for the rapid turnaround on this. 👏🏼
