### ISSUE TITLE
`@sentry/utils` `stripSentryFramesAndReverse` may no longer limit number of stack frames 

### ISSUE THREAD

**Issue by timfish** [getsentry/sentry-electron#653]
### Problem Statement

Once [this PR](https://github.com/getsentry/sentry-javascript/pull/7410#discussion_r1134440755) is merged and released, limiting stack frames may move from `stripSentryFramesAndReverse` into `createStackParser`.

### Solution Brainstorm

If this occurs, limiting the number of stack frames will need to be added here:
https://github.com/getsentry/sentry-electron/blob/0d2eb16bf8daf9e330da85a9a823d20c80ad16ac/src/renderer/stack-parse.ts#L11-L27

**Comment by AbhiPrasad** [comment]
Released with `7.44.0` https://github.com/getsentry/sentry-javascript/releases/tag/7.44.0
