### ISSUE TITLE
Invalid data expected an object

### ISSUE THREAD

**Issue by ahmedmukhtar1133** [getsentry/sentry-electron#660]
### Is there an existing issue for this?

- [X] I have checked for existing issues https://github.com/getsentry/sentry-javascript/issues
- [X] I have reviewed the documentation https://docs.sentry.io/
- [X] I am using the latest SDK release https://github.com/getsentry/sentry-javascript/releases

### How do you use Sentry?

Sentry Saas (sentry.io)

### Electron SDK Version

4.1.2

### Electron Version

12.2.3

### What platform are you using?

MacOS

### Link to Sentry event

https://stephan-petzl.sentry.io/issues/4040133110/?alert_rule_id=829169&alert_timestamp=1679923869387&alert_type=email&environment=production&project=1554144&ref_fallback=ctrl&referrer=alert_email

### Steps to Reproduce

Just adding custom breadcrumb like this:
```
function translateArgs(args) {
  const [firstArg, ...otherArgs] = args
  const params = {}
  if (typeof firstArg === 'string') {
    params.message = firstArg
    if (otherArgs && otherArgs.length > 0) {
      params.data = { otherArgs }
    }
  } else {
    params.data = args
  }
  return params
}

 Sentry.addBreadcrumb({ category, ...translateArgs(args), level: 'debug' })
```

### Expected Result

Most of the time custom breadcrumbs are working fine, but found strange case where it shows error in breadcrumbs data `Invalid data expected an object`.

### Actual Result

It should show actual breadcrumb info instead of this error.

**Comment by AbhiPrasad** [comment]
@ahmedmukhtar1133 With your current code, `params.message` is only conditionally being set, and data can be set to `null`.

This is causing the breadcrumb to be invalid. Use the JSON button to examine the event JSON and see what the SDK sent as breadcrumbs values.

![image](https://user-images.githubusercontent.com/18689448/230105921-25223fc7-8704-454d-a4ab-0cbff613e875.png)

**Comment by timfish** [comment]
I'm just tidying up the stale issues in this repository. Please open another issue if this is still causing you problems.
