### ISSUE TITLE
Sentry breaks custom protocols because it calls `registerSchemesAsPrivileged` which can be called only once

### ISSUE THREAD

**Issue by pie6k** [getsentry/sentry-electron#661]
### Is there an existing issue for this?

- [X] I have checked for existing issues https://github.com/getsentry/sentry-javascript/issues
- [X] I have reviewed the documentation https://docs.sentry.io/
- [X] I am using the latest SDK release https://github.com/getsentry/sentry-javascript/releases

### How do you use Sentry?

Sentry Saas (sentry.io)

### Electron SDK Version

4.4.0

### Electron Version

24.0.0

### What platform are you using?

MacOS

### Steps to Reproduce

Create any custom protocol:

```ts
  protocol.registerBufferProtocol("foobar", (request, callback) => {
    return callback({ data: Buffer.from("Hello World") });
  });
```

Mark it as priviliged so it supports fetch API

```ts
protocol.registerSchemesAsPrivileged([
    {
      scheme: "foobar",
      privileges: { bypassCSP: true, corsEnabled: true, supportFetchAPI: true },
    },
  ]);
```

Initialize sentry main module (and renderer module)

```ts
import * as Sentry from "@sentry/electron/main";

export function initSentryMain() {
  console.info("Initializing Sentry");

  Sentry.init(sentryConfig);
}
```

### Expected Result

I am able to call my custom protocol with fetch API on renderer eg. `fetch("foobar://some-path");`

### Actual Result

After 2 totally ruined days of debugging this; having no clue it can be caused by sentry, I finally found that the issue happens because in `main/ipc.ts` of Sentry you do:

```ts
/** Enables Electron protocol handling */
function configureProtocol(options: ElectronMainOptionsInternal): void {
  if (app.isReady()) {
    throw new SentryError("Sentry SDK should be initialized before the Electron app 'ready' event is fired");
  }

  protocol.registerSchemesAsPrivileged([
    {
      scheme: PROTOCOL_SCHEME,
      privileges: { bypassCSP: true, corsEnabled: true, supportFetchAPI: true },
    },
  ]);
```

Which is incorrect. As Electron docs says https://www.electronjs.org/docs/latest/api/protocol#protocolregisterschemesasprivilegedcustomschemes 

> Note: This method can only be used before the ready event of the app module gets emitted **and can be called only once.**

As a result - you're silently overwriting previously defined schemes with your own, without warning. 

It results in 

```
Fetch API cannot load foobar://fooo. URL scheme "foobar" is not supported.
```

What makes it even more confusing is that in my case (and I imagine most of the cases) Sentry is only enabled in production, which made my custom protocols work just fine in dev.

Please fix it and please be careful when you use code that overwrites settings defined by the app. It caused a lot of stress and hair-pulling.

-------------------

## Workaround:

To workaround the issue and keep sentry working, AFTER initializing sentry, call

```ts
export function registerPriviligedProtocols() {
  protocol.registerSchemesAsPrivileged([
    {
      scheme: "sentry-ipc",
      privileges: { bypassCSP: true, corsEnabled: true, supportFetchAPI: true },
    },
    // <<--- REST OF MY CUSTOM SCHEMES HERE
  ]);
}
```

to register both sentry protocols and our own protocols.

**Comment by timfish** [comment]
Sorry, I didn't notice that `registerSchemesAsPrivileged` could only be called once and silently allowed it to be called more times! 

Probably the easiest way to work around this until we come up with a better solution is to use [IPC via preload injection](https://docs.sentry.io/platforms/javascript/guides/electron/#preload-injection) rather than a protocol scheme. You can disable protocol setup by configuring `ipcMode: IPCMode.Classic`:

```ts
const { init, IPCMode } = require("@sentry/electron");

init({
  dsn: "__DSN__",
  ipcMode: IPCMode.Classic,
});
```

**Comment by timfish** [comment]
I'm still not sure what to do to improve this since Electron doesn't supply a means to test if `registerSchemesAsPrivileged` has already been called.

The only mild improvement I can think of (which I'd still like to avoid) would be to patch `registerSchemesAsPrivileged` when the Sentry library is imported (ie. a side effect) and display a warning if it gets called by SDK consumers.

**Comment by Wonder233** [comment]
I encountered the same problem：
![image](https://github.com/getsentry/sentry-electron/assets/8199240/48c00230-0c2d-462c-967f-a27cab4059ec)

I need to register my own custom protocol
![image](https://github.com/getsentry/sentry-electron/assets/8199240/db4119cd-2c5d-4e0d-ac88-7ea62487c763)

**Comment by Wonder233** [comment]
And when I use IPCMode.classic, I found that sentry initialized in the rendering process is still fetch "sentry-ipc:" protocol
![image](https://github.com/getsentry/sentry-electron/assets/8199240/f506f0a5-f90f-4fff-b079-0253da1df318)

**Comment by timfish** [comment]
@Wonder233 have you tried using the above workaround at the bottom of the original post?
