### ISSUE TITLE
HTML 5 Notifications not working in built artifact unless removing Sentry initialization from main process

### ISSUE THREAD

**Issue by rankill** [getsentry/sentry-electron#672]
### Is there an existing issue for this?

- [X] I have checked for existing issues https://github.com/getsentry/sentry-javascript/issues
- [X] I have reviewed the documentation https://docs.sentry.io/
- [X] I am using the latest SDK release https://github.com/getsentry/sentry-javascript/releases

### How do you use Sentry?

Sentry Saas (sentry.io)

### Electron SDK Version

4.4.0

### Electron Version

22.0.0

### What platform are you using?

MacOS

### Steps to Reproduce

1. Initialize Sentry in both renderer and main processes
2. Create a notification using HTML 5 Notifications API in renderer process
3. Build electron APP
4. Open built artifact.

**main initialization**
``` 
init({
  dsn: 'DNS',
  beforeSend: (event) => {
    if (process.env.WEBPACK_DEV_SERVER_URL) {
      return null;
    }
    return event;
  },
});
```

**renderer initialization**
``` 
init(
  {
    // Ignore to avoid sentry quota
    // Ref: https://stackoverflow.com/a/66260608/4460391
    // Ref:https://stackoverflow.com/questions/49384120/resizeobserver-loop-limit-exceeded
    ignoreErrors: ['ResizeObserver loop limit exceeded'],
    dsn: 'DSN',
    tracesSampleRate: 1.0,
    beforeSend: (event) => {
      if (window.location.hostname === 'localhost') {
        return null;
      }
      return event;
    },
  },
  vueInit
);
```

### Expected Result

Notification to show up properly as localhost version does (Request permission banner shows)

### Actual Result

Nothing happens, no permission banner nor notification

**Comment by timfish** [comment]
I tested a basic Electron Forge webpack app and HTML notifications appear to be working on macOS regardless of whether Sentry is initialised. 

I did initially see some strange issues with notifications though. For example, event without Sentry, I couldn't get them display in development mode and just got the chime. When I tried a production build, notifications didn't work at all. I did get it working though by resetting notifications In macOS permissions settings by right clicking on the Electron apps and clicking "Reset Notifications":

<img width="348" alt="image" src="https://user-images.githubusercontent.com/1150298/235876508-110eb7a8-c515-4641-b538-40a58165a3b4.png">


If you can provide a minimal reproduction of the issue I'd be happy to look into it further!

**Comment by rankill** [comment]
Hey, @timfish  thanks for the quick reply, I don't really have a way to share a reproduction of the issue, just tried **resetting notifications** but had no luck, notification permission is always `denied` and there is no ask for permission badge

<img width="507" alt="image" src="https://user-images.githubusercontent.com/6987914/235934176-32350fa0-9069-45b2-a0cd-2270d851150b.png">

https://user-images.githubusercontent.com/6987914/235935283-7e022684-c210-43ed-bb89-7abc2d5fadcb.mov

I'll try to build a reproducible repo ASAP, so I can share it with you, thanks!

**Comment by timfish** [comment]
I'm just tidying up the stale issues in this repository. Please do reopen if you have a reproduction for this.
