### ISSUE TITLE
Crash events are being sent with the wrong release version if being sent after the user upgrades the app

### ISSUE THREAD

**Issue by yuval-sentry** [getsentry/sentry-electron#679]
### Is there an existing issue for this?

- [X] I have checked for existing issues https://github.com/getsentry/sentry-javascript/issues
- [X] I have reviewed the documentation https://docs.sentry.io/
- [X] I am using the latest SDK release https://github.com/getsentry/sentry-javascript/releases

### How do you use Sentry?

Sentry Saas (sentry.io)

### Electron SDK Version

4.1.2

### Electron Version

19.1.9

### What platform are you using?

MacOS

### Steps to Reproduce

1. Trigger a crash for app version X
2. Upgrade your app to version X + 1
3. Reopen the app and let the event be sent to Sentry
	

### Expected Result

1. Check if the event is being reported in the right version
2. Check if the sourcemaps for the crash event are being pulled for version X

### Actual Result

A crash event that happened on version X shows to happen on version X+1 and the sourcemaps for that couldn't be found.

**Comment by timfish** [comment]
I'm not sure there's anything we can do to improve this.

Main process native crashes are reported on the next app start because they cause the app to exit. The only way we know that they've even occurred is that we find a minidump file on app start.

**Comment by timfish** [comment]
We already persist scope from the previous session so it wasn't complicated to also persist the release/environment too and override these before sending the event.

I've got a PR for this, I just need to work out what's causing some tests to start failing.

https://github.com/getsentry/sentry-electron/pull/683
