### ISSUE TITLE
Store App context with crash to send on next app start

### ISSUE THREAD

**Issue by rodolfoBee** [getsentry/sentry-electron#711]
### Problem Statement

Currently the app start time can be after when a crash happened as the app context is not saved see screenshots, where the start time matches the time the event was received (CEST = Z+2h).

![Screenshot 2023-07-31 at 10 55 23](https://github.com/getsentry/sentry-electron/assets/64906376/1c963446-002a-4272-9abe-d7bae4551c56)
![Screenshot 2023-07-31 at 10 55 03](https://github.com/getsentry/sentry-electron/assets/64906376/f0701ae8-24b0-4612-a8a6-16d4826a61d7)

### Solution Brainstorm

Having this information stored with the rest of the scope and minidump will keep information consistent. Somehow related to: https://github.com/getsentry/sentry-electron/issues/679

**Comment by timfish** [comment]
Is this a native crash in the main process?

**Comment by rodolfoBee** [comment]
Main crash, here is a simple repro: 
[electron.zip](https://github.com/getsentry/sentry-electron/files/12214691/electron.zip)

just add DSN in main.js, npm install and run.

**Comment by timfish** [comment]
Closed via #683

**Comment by Lonenso** [comment]
@timfish, thanks for the fix, I want to verify it to see if it still repros, but I tried `npm install git@github.com:getsentry/sentry-electron.git#85f82bc --save` with no luck. could you tell me how to do it? since sentry might not release 4.9.0 too soon. 

(I am this issue original reporter.

**Comment by timfish** [comment]
The SDK cannot be installed via git because it uses TypeScript and needs to be built first. I'll try and get it released on npm today!

**Comment by timfish** [comment]
When [this](https://github.com/getsentry/publish/issues/2579) issue closes, v4.9.0 will have been published to npm.
