### ISSUE TITLE
Stop sessions if app goes into background

### ISSUE THREAD

**Issue by AbhiPrasad** [getsentry/sentry-electron#712]
### Problem Statement

https://develop.sentry.dev/sdk/sessions/

In the mobile SDKs, we end a session if the app is backgrounded for > 30s, and start another one if the app is foregrounded after that.

We might want to explore adding this functionality for Electron sessions.

### Solution Brainstorm

We can perhaps add this as an option to the main session integration and have it be opt-in. This way people's dashboards will not dramatically change when bumping SDK versions, and we can re-evaluate what the default should be when we bump the major version.

**Comment by smeubank** [comment]
i'm afraid I am not so familiar with the release health sessions data model. This reminds me of issues with idle transactions in react-native and similar client side platforms. Where we need to basically have a span(s) which represents background time which can be subtracted from aggregate time and in UI when relevant to compress
