### ISSUE TITLE
SDK does not support ESM in main process

### ISSUE THREAD

**Issue by mahnunchik** [getsentry/sentry-electron#751]
### Is there an existing issue for this?

- [X] I have checked for existing issues https://github.com/getsentry/sentry-javascript/issues
- [X] I have reviewed the documentation https://docs.sentry.io/
- [X] I am using the latest SDK release https://github.com/getsentry/sentry-javascript/releases

### How do you use Sentry?

Sentry Saas (sentry.io)

### Electron SDK Version

4.11.0

### Electron Version

28

### What platform are you using?

MacOS

### Steps to Reproduce

Electron 28 with ESM support

### Expected Result

Named export is supported as it shown in the readme

```js
import { init } from '@sentry/electron';

init({
  dsn: '__DSN__',
  // ...
});
```

### Actual Result

SyntaxError: Named export 'init' not found. The requested module '@sentry/electron' is a CommonJS module, which may not support all module.exports as named exports.

**Comment by mahnunchik** [comment]
It seems `@sentry/electron` is completely broken when exported as ESM module in native ESM environment.

```js
import Sentry from '@sentry/electron';
```

```
node_modules/@sentry/electron/esm/main/index.js:1
import { ensureProcess } from '../common';
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at internalCompileFunction (node:internal/vm:73:18)
    at wrapSafe (node:internal/modules/cjs/loader:1185:20)
    at Module._compile (node:internal/modules/cjs/loader:1227:27)
    at Module._extensions..js (node:internal/modules/cjs/loader:1326:10)
    at Module.load (node:internal/modules/cjs/loader:1126:32)
    at Module._load (node:internal/modules/cjs/loader:967:12)
    at f._load (node:electron/js2c/asar_bundle:2:13542)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/translators:169:29)
    at ModuleJob.run (node:internal/modules/esm/module_job:194:25)
```

**Comment by mahnunchik** [comment]
@timfish I can not use sentry with Electron 28 in ESM environment. It is impossible to import cjs version due to `exports` field in package.json

Could it be fixed?

**Comment by timfish** [comment]
It was on the list to test but I wasn't aware of a release yet since v27 is still in beta.
https://github.com/getsentry/sentry-electron/issues/730

I see there's a nightly. Is that what you're using?

It should be relatively easy to fix and I need to add some integration tests too.

**Comment by mahnunchik** [comment]
Yes, I'm using nightly Electron 28 https://github.com/electron/electron/pull/37535#issuecomment-1705721459 to have ESM only code.

**Comment by timfish** [comment]
This should be working in 4.12.0 but it won't be fully tested until there's a beta release that we can run through the full test suite.

**Comment by thomasbadera** [comment]
this seems to be broken again in 4.17+

**Comment by timfish** [comment]
> this seems to be broken again in 4.17+

We test the latest versions of Electron with ESM in the main process. Can you open an issue with some reproduction steps?

**Comment by thomasbadera** [comment]
> > this seems to be broken again in 4.17+
> 
> We test the latest versions of Electron with ESM in the main process. Can you open an issue with some reproduction steps?

unfortunately it's not very consistent, I have two electron apps... one where it's working and one where I get

`App threw an error during load
SyntaxError: Cannot use import statement outside a module
  at ../../node_modules/@sentry-internal/tracing/esm/node/integrations/mysql.js`

both apps have identical tsconfigs, same sentry versions, same usage

**Comment by timfish** [comment]
Can you open a new issue with the full stack trace?
