### ISSUE TITLE
Session Replay in Electron not capturing network details

### ISSUE THREAD

**Issue by joshacheson** [getsentry/sentry-electron#765]
### Environment

self-hosted (https://develop.sentry.dev/self-hosted/)

### Steps to Reproduce

`@sentry/react` version: 7.70.0
`electron` version 22.0.0

1. Configure sentry session replay
2. Including configuration to capture more network information (in particular using `networkDetailAllowUrls`)
3. View replay on Sentry

Note that we've been considering porting to `@sentry/electron/renderer`, but even when including the react integration a la:

```
import * as Sentry from '@sentry/electron/renderer`;
import { init as reactInit } from '@sentry/react';

Sentry.init({...}, reactInit);
```

replays seem to stop capturing altogether, so we're sticking on `@sentry/react` for the renderer processes in our electron application for now.

### Expected Result

Can see body of network request as well as included custom headers when viewing a replay.

### Actual Result

Cannot see network request details when viewing a replay.

Including screenshot (avoiding much of the UI so nothing proprietary appears) of what the ui looks like when selecting a network request:

![image](https://github.com/getsentry/sentry/assets/1906888/34648fd7-0268-452e-8385-417e8a796813)

### Product Area

Replays

### Version

23.6.1

**Comment by timfish** [comment]
Can you give some more details over your setup as there are many variables that could be affecting this.

Are you using a bundler?

Do you have `nodeIntegration` enabled in the renderers?

**Comment by timfish** [comment]
I've tried to reproduce this but everything seems to be working as I'd expect.

I copied the Electron + React boilerplate [from our examples](https://github.com/getsentry/sentry-electron/tree/master/examples/electron-react-boilerplate), added Replay support like below and then added a `fetch` followed by throwing an Error:

```ts
import { render } from "react-dom";
import App from "./App";
import { init, Replay } from "@sentry/electron/renderer";
import { init as reactInit } from "@sentry/react";

init(
  {
    debug: true,
    integrations: [new Replay({ networkDetailAllowUrls: [""] })],
    replaysOnErrorSampleRate: 1,
  },
  reactInit
);

setTimeout(() => {
  fetch("https://httpbin.org/status/200").then((_) => {
    throw new Error("test");
  });
}, 10_000);

render(<App />, document.getElementById("root"));

```

The Replays appear in Sentry and have network details:
<img width="679" alt="image" src="https://github.com/getsentry/sentry-electron/assets/1150298/59e3a037-0c4b-4243-9c31-8026caa2eaec">

The full code I'm using is here:
https://github.com/timfish/electron-react-replay

I'm running:
```
yarn && yarn build && yarn start
```

Can you supply a reproduction where it doesn't work or am I misunderstanding the issue?

**Comment by timfish** [comment]
> Is 23.6.1 an adequate version of the self hosted service to offer this feature

Its worth testing against sentry.io to check if it's a self hosted issue.
