### ISSUE TITLE
Add `abnormal_mechanism` to sessions to track ANR rate

### ISSUE THREAD

**Issue by AbhiPrasad** [getsentry/sentry-electron#774]
ref https://github.com/getsentry/sentry-electron/issues/729

As per https://github.com/getsentry/develop/pull/931 we can add the `abnormal_mechanism` mechanism field to sessions to indicate to Sentry if a session was errored because of ANR. This allows the product to calculate ANR rate.

ref https://github.com/getsentry/sentry-java/pull/2475

Abnormal mechanism can be either one of `anr_foreground` or `anr_background as per https://github.com/getsentry/sentry/blob/bf6651cb323c6c45eab2b31d4078b21756dbdff6/src/sentry/sentry_metrics/indexer/strings.py#L139-L140

**Comment by timfish** [comment]
After the next Sentry JavaScript release I will update them and add some tests.

**Comment by AbhiPrasad** [comment]
`abnormal_mechanism` was added with https://github.com/getsentry/sentry-javascript/releases/tag/7.75.0
