### ISSUE TITLE
Browser Profiling

### ISSUE THREAD

**Issue by timfish** [getsentry/sentry-electron#792]
### Problem Statement

Newer versions of Chrome support the `BrowserProfilingIntegration` which captures CPU profiles. 

### Solution Brainstorm

Initial testing shows this does not work out-of-the-box.

**Comment by AbhiPrasad** [comment]
cc @JonasBa

**Comment by JonasBa** [comment]
@timfish can you explain a bit more about what breaks?

**Comment by JonasBa** [comment]
Or wait, do you mean newer versions of Electron right?

**Comment by timfish** [comment]
Just need to publish an SDK release and then I'll upload my demo app which is easier to debug. 

So far the log looks like this:
```
[App] [Renderer] Sentry Logger [log]: [Tracing] starting undefined transaction - Long work
[App] [Renderer] Sentry Logger [log]: [Profiling] started profiling transaction: Long work
[App] [Renderer] Sentry Logger [log]: [Tracing] Starting '< unknown op >' span on transaction 'Long work' (b49c1529ba22dcba).
/// snip extra
[App] [Renderer] Sentry Logger [log]: [Tracing] Finishing '< unknown op >' span on transaction 'Long work' (b49c1529ba22dcba).
[App] [Renderer] Sentry Logger [log]: [Profiling] stopped profiling of transaction: Long work
[App] [Renderer] Sentry Logger [log]: [Tracing] Finishing undefined transaction: Long work.
envelope
```
My best guess so far is that the `profile` context is not being added to the event as it's not hitting any of the debug logging when it should attempt to add the profile envelope.

**Comment by timfish** [comment]
Sorry for the delay. Here is the demo repo:
https://github.com/timfish/sentry-electron-renderer-profiling-test

`yarn && yarn start` to see the output.

It's worth noting that in the case of this basic app, and in many Electron apps, Node integration is enabled in the renderer processes which gives you full Node mixed into the browser context! This is not the recommended way to use Electron now, especially if you're loading remote content, but for many apps this is less of a concern. Historically this has caused issues with libraries that do any kind of Node detection but I don't think this is the case here.

**Comment by timfish** [comment]
There is nothing wrong with profiling, the issue is how we route envelopes through the apps main process!

**Comment by AbhiPrasad** [comment]
Ah, is it because the envelope lifecycle hook doesn't work properly with electron?

https://github.com/getsentry/sentry-javascript/blob/93bbeb782ae588aee2d021a7eba3cd6d946e69be/packages/browser/src/profiling/integration.ts#L63

**Comment by timfish** [comment]
No, that's all working in the renderer/browser process. 

The issue is that we intercept all events and transactions and capture them through the main/node process so they have the full content. At this point, the profiles are being stripped off:

https://github.com/getsentry/sentry-electron/blob/81cb70612fdd6bbbf467ed129134f7fb9bd6eb49/src/main/ipc.ts#L113-L125 

We want to maintain passing through the main process event pipeline so events from both processes have the same context. However, there's no way to pass the profiles (or envelope items other than attachment) through.

A couple of options:
- In the JavaScript repo, add something to `EventHint` that allows passing profiles or other envelope items through with captured events
- When we receive an event with a profile 
   - Remove and cache the profile 
   - Re-add the `profile` context  
   - Re-add the profile envelope when the event comes back through the main process event pipeline
