### ISSUE TITLE
Add sentry-electron cli command which uploads symbols for current electron dependency

### ISSUE THREAD

**Issue by timfish** [getsentry/sentry-electron#8]
You might want to add this to sentry-cli instead but it would be great to have a cli command somewhere which:

- Downloads all symbols for the version of electron referenced in package.json using [electron-download](https://www.npmjs.com/package/electron-download)
- Uploads these symbols to Sentry

**Comment by HazAT** [comment]
So we already have such command in sentry-cli we basically only have to integrate it in a script.
https://docs.sentry.io/learn/cli/dsym/

We were also thinking about adding support for https://github.com/getsentry/sentry-wizard and help with the setup process like adding the DSN to the package.json and add a script for uploading symbols etc.

**Comment by timfish** [comment]
Ok having this in the wizard could make more sense. 

I did see the sentry-cli commands to upload symbols but wanted something to automate the process, especially if I change the version of electron we're using. 

Currently I'd have to run:
```
electron-download --version=1.7.11 --dsym --platform=darwin
sentry-cli upload-dif -t dsym  C:\Users\tim\AppData\Local\electron\Cache\
electron-download --version=1.7.11 --symbols --platform=win32 --arch=ia32
electron-download --version=1.7.11 --symbols --platform=win32 --arch=x64
electron-download --version=1.7.11 --symbols --platform=linux --arch=x64
sentry-cli upload-dif -t breakpad C:\Users\tim\AppData\Local\electron\Cache\
```

Having said that, with symbol server support maybe none of the above is required.

**Comment by HazAT** [comment]
I will reopen this until we have that automated somehow.

**Comment by HazAT** [comment]
ref: https://github.com/getsentry/sentry-wizard/pull/4
