### ISSUE TITLE
Breadcrumbs are not saved in the event on a native crash

### ISSUE THREAD

**Issue by michalzaq12** [getsentry/sentry-electron#802]
### Is there an existing issue for this?

- [X] I have checked for existing issues https://github.com/getsentry/sentry-javascript/issues
- [X] I have reviewed the documentation https://docs.sentry.io/
- [X] I am using the latest SDK release https://github.com/getsentry/sentry-javascript/releases

### How do you use Sentry?

Sentry Saas (sentry.io)

### Electron SDK Version

4.15.1

### Electron Version

26.0.0

### What platform are you using?

Windows

### Steps to Reproduce

.

### Expected Result

The event breadcrumb context should be the same as when the error occurred.

### Actual Result

Breadcrumbs are not saved in the event on a native crash, which causes incorrect application context and makes debugging difficult.
<img width="367" alt="image" src="https://github.com/getsentry/sentry-electron/assets/28574933/e0094dda-f9c2-42f7-959a-ba18945cc3c8">
<img width="500" alt="image" src="https://github.com/getsentry/sentry-electron/assets/28574933/5f0aa248-67bc-4243-8807-5fa14c33772a">

**Comment by timfish** [comment]
What tags was this event sent with? 

The Electron SDK has offline support so that if sending of events fails, they are retried later which can give a time difference between occurrence and received.

**Comment by michalzaq12** [comment]
Tags:
![image](https://github.com/getsentry/sentry-electron/assets/28574933/5119b4ba-cdd6-4cd0-aebd-438f759b214f)

> The Electron SDK has offline support so that if sending of events fails, they are retried later which can give a time difference between occurrence and received.

I understand, but when you try to send the event again, the context (breadcrumbs) should not be overwritten.

**Comment by timfish** [comment]
`event.process: browser` suggests that this minidump was picked up at application startup. Crashes in the Electron main process (`browser`) cause the application to terminate so we send these on next app start using saved context if there is any.

It looks like the breadcrumbs there are from the subsequent app start. I'll need to look into this.

**Comment by timfish** [comment]
When updating the Electron SDK to use the latest Sentry JavaScript SDKs, I simplified how the scope is applied to events. 

I added some extra breadcrumbs to the native main tests (https://github.com/getsentry/sentry-electron/pull/812) and they appear to be as expected so the scope changes might have fixed this.
