### ISSUE TITLE
Sentry source map not match stack trace

### ISSUE THREAD

**Issue by T2J5** [getsentry/sentry-electron#820]
Hi!. I encountered a problem about source map not match stack trace on my self-hosted sentry instance.  I searched for many related issues, but still found nothing. when i use ip, anything is ok, but when i change `config.yml`  `system.url_prefix`  to domain(www.example.com) ,then error was happened.

 Can someone help? I struggled this for a few days.  Here is some information about my project.

`
"@sentry/electron": "^4.17.0",
"@sentry/webpack-plugin": "^2.10.2"
`

-----

<img width="1236" alt="lQLPJwHKO9lHAS_NBl7NCaiwxImswlCE67kFoFh6MUNHAA_2472_1630" src="https://github.com/getsentry/sentry-electron/assets/58797269/c2b65861-3655-4f33-b4c4-52ce4f0b45c7">

-----
<img width="1193" alt="lQLPJwjdCX4cHS_NB1DNCVKwd4lnvKCbFHQFoFhgCXNtAA_2386_1872" src="https://github.com/getsentry/sentry-electron/assets/58797269/37a97f3d-d8fd-416a-b657-0b87bac6661d">

-----
<img width="968" alt="lQLPKG-Ln2J5fo_NBBLNB5CwyW29-7myy6gFoFryudkPAA_1936_1042" src="https://github.com/getsentry/sentry-electron/assets/58797269/c012586f-03f3-42d7-ac26-65318df46d2d">

---- 
I also test my .map files, it's no problem.
<img width="832" alt="lQLPJw08n_6GBO_NAXrNBoCwJLO5u9Q88CgFoFjKeCBvAA_1664_378" src="https://github.com/getsentry/sentry-electron/assets/58797269/628e35a2-7dcb-4d2a-b4df-bae750ea4896">

**Comment by lforst** [comment]
Can you try upgrading your self hosted instance and checking the logs of your self hosted instance? Make sure the `symbolicator` service is running!

**Comment by T2J5** [comment]
Thanks u'r reply! 
this is my symbollicator service logs
![lQLPJwx70AERTa_NAZbNBSywSdj0VS80BQ8FopO3jpeNAA_1324_406](https://github.com/getsentry/sentry-electron/assets/58797269/61649072-08a7-4aab-ace3-1b302a512c1b)
