### ISSUE TITLE
Electron and React package are not compatible

### ISSUE THREAD

**Issue by elvince** [getsentry/sentry-electron#825]
### Is there an existing issue for this?

- [X] I have checked for existing issues https://github.com/getsentry/sentry-javascript/issues
- [X] I have reviewed the documentation https://docs.sentry.io/
- [X] I am using the latest SDK release https://github.com/getsentry/sentry-javascript/releases

### How do you use Sentry?

Sentry Saas (sentry.io)

### Which SDK are you using?

@sentry/react

### SDK Version

7.100.1

### Framework Version

7.100.1

### Steps to Reproduce

Import those 2 packages:

 "@sentry/electron": "^4.17.0",
 "@sentry/react": "^7.100.1",

### Expected Result

No issue

### Actual Result

There are some conflict issue as the dependency packages are not the same:
 "@sentry/core": "7.92.0",
 "@sentry/core": "7.100.1",
 Could you please update them?

**Comment by timfish** [comment]
The current release of the Electron SDK (v4.17.0) uses v7.98.0 of the JavaScript SDKs.
