### ISSUE TITLE
captureConsoleIntegration does not works in v4.18.0

### ISSUE THREAD

**Issue by panther7** [getsentry/sentry-electron#833]
### Is there an existing issue for this?

- [X] I have checked for existing issues https://github.com/getsentry/sentry-javascript/issues
- [X] I have reviewed the documentation https://docs.sentry.io/
- [X] I am using the latest SDK release https://github.com/getsentry/sentry-javascript/releases

### How do you use Sentry?

Self-hosted/on-premise

### Electron SDK Version

4.18.0

### Electron Version

28.2.3

### What platform are you using?

Windows

### Steps to Reproduce

Works properly in @sentry/electron@4.17.0

Sentry config (in main process):
```js
import * as Sentry from '@sentry/electron/main'; // v4.18.0
import { captureConsoleIntegration } from '@sentry/integrations'; // v7.102.0

Sentry.init({
    // ...
    ipcMode: Sentry.IPCMode.Protocol,
    integrations: [
        captureConsoleIntegration({ levels: ['error'] }),
        new Sentry.Integrations.MainProcessSession({ sendOnCreate: true }),
    ],
    // ...
}
```

### Expected Result

console.error('test'); // capture error

### Actual Result

console errors are not captured

**Comment by lforst** [comment]
Hm, sounds weird, can you try using the `7.101.0` version of the integrations package? That one aligns with the one the electron SDK is using. Thanks!

**Comment by lforst** [comment]
@panther7 Thanks for testing! I recommend reverting the integrations package back to 7.101.0. The electron package has a certain compatibility range with the other Sentry SDK packages and that one happens to only include 7.101.0 right now.
