### ISSUE TITLE
Test User Feedback with Electron SDK

### ISSUE THREAD

**Issue by AbhiPrasad** [getsentry/sentry-electron#834]
### Problem Statement

Sentry has user feedback functionality in alpha! https://docs.sentry.io/platforms/javascript/user-feedback/

### Solution Brainstorm

Let's test it out to see if it works with Electron.

If it works fine we can update in-app onboarding and docs to add electron support!

No rush on this task - lower prio compared to v8 stuff, but give it a try whenever you get cycles.

**Comment by AbhiPrasad** [comment]
We can only merge in https://github.com/getsentry/sentry-docs/pull/9213 after we cut a release of the Electron SDK with the changes from PR linked to this issue.

**Comment by timfish** [comment]
This has now been released:
https://github.com/getsentry/sentry-electron/releases/tag/4.20.0
