### ISSUE TITLE
MaxListenersExceededWarning due to Sentry.init calls on window refresh

### ISSUE THREAD

**Issue by Rafatcb** [getsentry/sentry-electron#847]
### Is there an existing issue for this?

- [X] I have checked for existing issues https://github.com/getsentry/sentry-javascript/issues
- [X] I have reviewed the documentation https://docs.sentry.io/
- [X] I am using the latest SDK release https://github.com/getsentry/sentry-javascript/releases

### How do you use Sentry?

Sentry Saas (sentry.io)

### Electron SDK Version

4.20.0

### Electron Version

22.3.27

### What platform are you using?

Windows

### Steps to Reproduce

1. Add a call to `Sentry.init` on renderer. (I'm using React, so this is called outside the `App` component)
2. Refresh the page a few times (probably 10~15 times).

### Expected Result

No warning.

### Actual Result

Warning:

```
(node:19700) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 message listeners added to [Worker]. Use emitter.setMaxListeners() to increase limit
```

If you add `process.on('warning', e => console.warn(e.stack))` on your main process you can see the stack trace:

```
MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 destroyed listeners added to [EventEmitter]. Use emitter.setMaxListeners() to increase limit
    at _addListener (node:events:587:17)
    at EventEmitter.addListener (node:events:605:10)
    at EventEmitter.once (node:events:649:8)
    at IpcMainImpl.<anonymous> (D:\repo\node_modules\@sentry\electron\src\src\main\ipc.ts:268:14)
    at IpcMainImpl.emit (node:events:513:28)
    at IpcMainImpl.emit (node:domain:489:12)
    at EventEmitter.<anonymous> (node:electron/js2c/browser_init:2:81099)
    at EventEmitter.emit (node:events:513:28)
    at EventEmitter.emit (node:domain:489:12)
```

Which points to this part of Sentry's code:

https://github.com/getsentry/sentry-electron/blob/02322af325a564f01fc58a8c07bc89d1fda8a69e/src/main/ipc.ts#L259-L272

I think it could be updated to:

```diff
if (!sender.isDestroyed()) { 
 // Keep track of renderers that are using IPC 
 KNOWN_RENDERERS = KNOWN_RENDERERS || new Set(); 

+ if (KNOWN_RENDERERS.has(id)) {
+   return;
+ }

 KNOWN_RENDERERS.add(id); 

 sender.once('destroyed', () => { 
   KNOWN_RENDERERS?.delete(id); 
 }); 
} 
```

**Comment by timfish** [comment]
Hi @Rafatcb, thanks for reporting this!

**Comment by Rafatcb** [comment]
@timfish thanks for the fix :smiley:
