### ISSUE TITLE
Log Breadcrumbs for App Restarts

### ISSUE THREAD

**Issue by jan-auer** [getsentry/sentry-electron#85]
The SDK should log breadcrumbs when the App restarts (but probably not for the first start) to make it easier to separate sessions from the user. Ideally, this would use a new breadcrumb type with distinct rendering in the issue details UI.

**Comment by AbhiPrasad** [comment]
@timfish should we ever take this on? 6+ years feels too long 😄

**Comment by timfish** [comment]
By this point there are plenty of other breadcrumbs and events the show app startup so this isn't required
