### ISSUE TITLE
Linking vue plugin

### ISSUE THREAD

**Issue by pmccarren** [getsentry/sentry-electron#87]
I'm using Vue inside Electron ([simulatedgreg/electron-vue](https://github.com/simulatedgreg/electron-vue)), and am trying to figure out how to link up the Raven Vue plugin with Sentry Electron? Perhaps the plugin/Raven is simply not applicable in this case..

I understand that `sentry/raven-js/browser` is the the 'NG Raven', and am curious if there is a best practice to have Sentry catch Vue errors. It would be straightforward to implement the [plugin](https://github.com/getsentry/raven-js/blob/master/packages/raven-js/plugins/vue.js) itself inside the app, subbing Raven context with Browser.

Any info / suggestions are welcome. If this issue should be moved to `sentry/raven-js`, let me know!

**Comment by HazAT** [comment]
Related: https://github.com/getsentry/sentry-electron/issues/74#issuecomment-405218414

**Comment by timfish** [comment]
Integrations should now all be working. If you're having issues with any particular integration and `@sentry/electron`, please open a new issue.
