### ISSUE TITLE
Sentry.captureMessage doesn't support passing additional data

### ISSUE THREAD

**Issue by brigaccess** [getsentry/sentry-electron#90]
Documentation for Raven at https://docs.sentry.io/clients/javascript/usage/#passing-additional-data states that it is possible to pass any desired additional data. However, this is not the case with sentry-electron. Is it intentional decision to drop support for passing additional data, or am I missing something?

**Comment by dimitarnestorov** [comment]
Temporary solution:

```js
setExtraContext({cause});
captureException(ex);
setTimeout(() => {
	setExtraContext({cause: null});
});
```

**Comment by brigaccess** [comment]
@dimitarnestorov, thanks for a workaround! However, I'm still curious about whether this feature is no longer supported or it's just not implemented yet and haven't been discontinued

**Comment by dimitarnestorov** [comment]
Not implemented. Check out #74.

**Comment by brigaccess** [comment]
Good to know, thanks again, @dimitarnestorov!

**Comment by HazAT** [comment]
Version `0.6.0` is on it's way.
You can achieve the same result with this:

```javascript
Sentry.getDefaultHub().withScope(() => {
      Sentry.getDefaultHub().configureScope(scope => {
        scope.setExtra('details', 'This is some extra information.');
        Sentry.captureMessage('This is a sample message');
      });
});
```

We are still working on the documentation for the new SDKs.
While this approach seems to be more complicated than before it's also more powerful.

Hope this helps.

**Comment by alxmiron** [comment]
Why does so simple thing need extra 5 lines of code? I expected it to be something like
```
Sentry.captureException(error, { extra: { detailName: 'Detail value' } });
```

**Comment by HazAT** [comment]
@alxmiron We changed the public API of our SDKs to make it more logical and less magical.
Before you were able to pass anything as a second arg, while this may seem convenient, many people were facing unexpected behavior since it was not clear what the limits are of what to pass.

We went with the approach I stated before which is more verbose but on the other hand, it's clear what's happening.

**Comment by aguynamedben** [comment]
This syntax crazy and optimizes for Sentry, not customers. The whole idea of Sentry is to scatter simple bits of code throughout your app to capture important errors and conditions. 6 lines of code each time I want to do something simple really adds up. 1 line of code could be used.

You could support the shorter syntax for simplicity (95% of what users will be doing) and manage the "more powerful", "more verbose" syntax for the 5% of people who care about it (and how things work under the hood).

You don't want to be telling customers "Sentry is easy to use, it's only 6 lines of JavaScript any time you want to send an `info` message to us!"

**Comment by aguynamedben** [comment]
An alternative idea...
```js
Sentry.captureMessage('This is a sample message').setExtras({
  details: 'This is some extra information.',
  level: 'info',
});
```

I think the main thing I have beef with is these parts:
```js
Sentry.getDefaultHub().withScope(() => {
      Sentry.getDefaultHub().configureScope(scope => {
```

That just seems like stuff that should be internal, not part of your API. It's fine to expose more powerful APIs but provide simple ones.

**Comment by MonsieurV** [comment]
Following the [latest doc](https://docs.sentry.io/learn/scopes/?platform=browser#local-scopes), would not the new syntax for that be:

```js
Sentry.withScope(scope => {
  scope.setExtra('details', 'This is some extra information.');
  scope.setLevel('info');
  Sentry.captureMessage('This is a sample message');
});
```

@HazAT ?

This seems much more reasonable, while still verbose.

**Comment by aguynamedben** [comment]
@MonsieurV That's correct.

See:
* https://github.com/getsentry/sentry-electron/issues/108#issuecomment-422291699
* https://github.com/getsentry/sentry-electron/issues/115

We're using version 0.10.1 (and therefore sentry-javascript 4.x.x) and the syntax you mention works now.

**Comment by shash7** [comment]
I had the same issue with the api but @MonsieurV has the right approach regarding syntax. To expand upon it, I made a simple helper function to log errors:
```
function errorHandler(title, data, level) {
	level = level || 'info';
	data  = data  || {};
	Sentry.withScope(scope => {
		Object.keys(data).forEach((key) => {
			scope.setExtra(key, data[key]);
		});
	  scope.setLevel(level);
	  Sentry.captureMessage(title);
	});
}
```
