### ISSUE TITLE
Crashes that occurred during the app upgrade process were counted in the new version

### ISSUE THREAD

**Issue by PayneFuRC** [getsentry/sentry-electron#903]
### Is there an existing issue for this?

- [X] I have checked for existing issues https://github.com/getsentry/sentry-javascript/issues
- [X] I have reviewed the documentation https://docs.sentry.io/
- [X] I am using the latest SDK release https://github.com/getsentry/sentry-javascript/releases

### How do you use Sentry?

Sentry Saas (sentry.io)

### Electron SDK Version

4.24.0

### Electron Version

30.0.1

### What platform are you using?

None

### Steps to Reproduce

1. mock a main process crash in old version
2. install the new version
3. upload the crash to the new version in sentry server.

### Expected Result

1. upload the crash to old version

### Actual Result

1. upload the crash to new version

**Comment by timfish** [comment]
We've fixed this bug previously and have an integration test that checks this:
https://github.com/getsentry/sentry-electron/blob/e909ab277481259e8755eeab67c8fd69d08fed94/test/e2e/test-apps/native-sentry/main-update/src/main.js

Which version of the SDK were you using before updating to 4.24.0?

**Comment by PayneFuRC** [comment]
Thanks. I will check it.

**Comment by PayneFuRC** [comment]
Thank you, this problem disappears after using the new version
