### ISSUE TITLE
Please cut a new release 

### ISSUE THREAD

**Issue by Stanzilla** [getsentry/sentry-electron#920]
### Problem Statement

Hey there, I would like to update my other Sentry packages but currently can't because sentry-electron uses the old SDK version, Would be nice if this can be coordinated in the future!

Thank you!

### Solution Brainstorm

- Release new sentry-electron version
- In the future, always release a new sentry-electron version when sentry-javascript releases a new version with a newer SDK

**Comment by AbhiPrasad** [comment]
Hey @Stanzilla, we'll get another release out with the latest sdk version.

> In the future, always release a new sentry-electron version when sentry-javascript releases a new version with a newer SDK

We can't guarantee immediate releases because of maintainer bandwidth, but we'll try our best to release in a timely manner. If you would like to help expedite, PRs are always welcome (usually with JS SDK bumps comes some small changes to internals or refactors to tests).

**Comment by Stanzilla** [comment]
> Hey @Stanzilla, we'll get another release out with the latest sdk version.
> 
> > In the future, always release a new sentry-electron version when sentry-javascript releases a new version with a newer SDK
> 
> We can't guarantee immediate releases because of maintainer bandwidth, but we'll try our best to release in a timely manner. If you would like to help expedite, PRs are always welcome (usually with JS SDK bumps comes some small changes to internals or refactors to tests).

Oh is that something you guys would accept? Just bumping the SDK version? Good to know!

**Comment by AbhiPrasad** [comment]
yes! example PR here: https://github.com/getsentry/sentry-electron/pull/912

**Comment by timfish** [comment]
Apologies! The JavaScript SDKs are updated, we just needed a release #924

**Comment by Stanzilla** [comment]
Thank you!

**Comment by timfish** [comment]
Once [this issue](https://github.com/getsentry/publish/issues/3962) closes, the new release will be published!

**Comment by AbhiPrasad** [comment]
Released! https://github.com/getsentry/sentry-electron/releases/tag/5.1.0

**Comment by Stanzilla** [comment]
Hey, me again, would love to get a new release that is compatible with the latest SDK. Always a bit of a pain if the two projects desync and you can't update Sentry because the Electron plugin will break otherwise
