### ISSUE TITLE
Limit JavaScript errors by allowing only a specific number of uploads per session.

### ISSUE THREAD

**Issue by PayneFuRC** [getsentry/sentry-electron#933]
### Problem Statement

https://jupiter-ct.sentry.io/issues/5458375266/events/?project=1430058&referrer=release-issue-stream

### Solution Brainstorm

limit javaScript errors

**Comment by timfish** [comment]
This is achievable using the `beforeSend` callback in the main process:

```ts
import * as Sentry from '@sentry/electron/main';

let sendCount = 0;

Sentry.init({
  dsn: '__DSN__',
  beforeSend: (event) => {
    sendCount++;
    return sendCount > 10 ? null : event
  }
});
```

**Comment by PayneFuRC** [comment]
Got it.  Thanks.
