### ISSUE TITLE
How to set User Scope Info in @sentry/electron

### ISSUE THREAD

**Issue by CurryYangxx** [getsentry/sentry-electron#936]
### Problem Statement

We use v3.0 before, and we use Sentry.configureScope to update user info.
 ```
Sentry.configureScope(async scope => {
    const id = await getAccountId();
    if (id) {
      scope.setUser({ id });
    } else {
      scope.setUser(null);
    }
  });
```
Now we are updating the sdk to v5.1. The configureScope is not exist.I have 2 questions.

1. How should I set user info in version 5.0?
2. Should I set it on main process or renderer process, Is there any difference between the two approaches？

### Solution Brainstorm

provide a new function instead configureScope

**Comment by timfish** [comment]
This is covered in [this section](https://github.com/getsentry/sentry-javascript/blob/develop/MIGRATION.md#removal-of-sentryconfigurescope-method) of the JavaScript migration docs:

```ts
// old
Sentry.configureScope(scope => {
  scope.setUser({ id });
});

// new
Sentry.getCurrentScope().setUser({ id });
```

**Comment by CurryYangxx** [comment]
@timfish  Is there any difference between setting user in renderer process  and main process?

**Comment by timfish** [comment]
All scope and events from any renderer are forwarded to the main process where they're combined and sent. This means you can set the user in any process and it will be included in events from either process.

**Comment by CurryYangxx** [comment]
Thanks for your help
