### ISSUE TITLE
Trace is not reported when start from a local file

### ISSUE THREAD

**Issue by CurryYangxx** [getsentry/sentry-electron#940]
### Is there an existing issue for this?

- [X] I have checked for existing issues https://github.com/getsentry/sentry-javascript/issues
- [X] I have reviewed the documentation https://docs.sentry.io/
- [X] I am using the latest SDK release https://github.com/getsentry/sentry-javascript/releases

### How do you use Sentry?

Sentry Saas (sentry.io)

### Electron SDK Version

5.1.0

### Electron Version

30.0.9

### What platform are you using?

MacOS

### Steps to Reproduce

1. after setting up tracing like this
```
  integrations: [new Sentry.browserTracingIntegration()],
  tracesSampleRate: 1.0,
```
In our electron app dev mode, we load HTML from localhost, and a trace will be reported.
But in prod mode, we load HTML from a local file(`file://xx`), and the trace will not be reported.

### Expected Result

Trace can be reported when start from a local file

### Actual Result

No trace report

**Comment by timfish** [comment]
We have a test with this working from a file path:
https://github.com/getsentry/sentry-electron/blob/master/test/e2e/test-apps/other/browser-tracing/src/main.js#L23

I haven't tried it yet but I guess a file URL might be breaking something!

**Comment by CurryYangxx** [comment]
Sorry. This is a problem caused by our project packaging, after we fix it, the trace can be reported successfully.

**Comment by timfish** [comment]
Perfect. Thank you for the update!
