### ISSUE TITLE
The crash count doesn't match

### ISSUE THREAD

**Issue by PayneFuRC** [getsentry/sentry-electron#941]
### Is there an existing issue for this?

- [X] I have checked for existing issues https://github.com/getsentry/sentry-javascript/issues
- [X] I have reviewed the documentation https://docs.sentry.io/
- [X] I am using the latest SDK release https://github.com/getsentry/sentry-javascript/releases

### How do you use Sentry?

Sentry Saas (sentry.io)

### Electron SDK Version

4.22.0

### Electron Version

27.2.20

### What platform are you using?

None

### Link to Sentry event

https://jupiter-ct.sentry.io/discover/homepage/?field=title&field=event.type&field=project&field=user.display&field=timestamp&name=All+Events&project=1430058&query=release%3Adesktop%4024.2.360%2BRCAppDesktop+error.mechanism%3Aminidump&queryDataset=discover&sort=-timestamp&statsPeriod=90d&yAxis=count%28%29

### Steps to Reproduce

1. from the release page, there are 100 crash events.
<img width="1528" alt="image" src="https://github.com/getsentry/sentry-electron/assets/150770050/99924891-98aa-45e5-b20e-c87fc74eea0f">

2. From the discover page, there are 151 crash events.
<img width="1501" alt="image" src="https://github.com/getsentry/sentry-electron/assets/150770050/2cdfac20-f4c8-42d3-9e46-7fde571f6d29">

### Expected Result

These two data should be equal.

### Actual Result

These two data are not equal.

**Comment by PayneFuRC** [comment]
From the sentry/electron code, Only render process and child process crashes update the session status to crashed. 

Main process crashes do not update the session status. Is this a problem? However, from the discovery page, the sum of render process and child process crashes is still less than 100. So currently, I want to understand how the 100 crash events on the release page are calculated. How can I filter out these 100 events on the discovery page?

<img width="1329" alt="image" src="https://github.com/getsentry/sentry-electron/assets/150770050/c75f752d-0771-4c7b-8240-2c6e298ea28c">

**Comment by lforst** [comment]
Hi, the discover page shows aggregations over all events (you're querying errors) and the releases page simply shows stats on sessions (different event type than errors). A crashed session may contain more than one error. That is likely what's happening here.

**Comment by timfish** [comment]
> From the sentry/electron code, Only render process and child process crashes update the session status to crashed.

All JavaScript errors go through `@sentry/core` which updates the session status.

> Main process crashes do not update the session status.

Main process native crashes take down the process and so they are not reported until the next session startup. At this point we find the minidump and report a crashed session. This occurs via [`checkPreviousSession`](https://github.com/getsentry/sentry-electron/blob/1e93c3f71d46805cf3d43cfb6354ff0fd4576d74/src/main/sessions.ts#L111) which marks the current sesison as crashed and then creates a new fresh session for this new process to continue with.

**Comment by PayneFuRC** [comment]
@timfish Are Javascript errors marked as crashed, or is it only minidump files that are marked as crashed?

**Comment by PayneFuRC** [comment]
@lforst How can I filter out all crash sessions displayed on the release page?

**Comment by lforst** [comment]
> How can I filter out all crash sessions displayed on the release page?

As of today you can't.

> Could you help explain these code?

When the SDK sends an error, the SDK also sends a session update that is either `crashed` when the error was unhandled, or `errored` when the error was handled.

**Comment by PayneFuRC** [comment]
> > How can I filter out all crash sessions displayed on the release page?
> 
> As of today you can't.
Is there a plan to support this?


> 
> > Could you help explain these code?
> 
> When the SDK sends an error, the SDK also sends a session update that is either `crashed` when the error was unhandled, or `errored` when the error was handled.

Every time I click on a crash from the release page, it redirects to unhandled events, but the numbers don't match up. I have to explain this to my boss each time.

**Comment by lforst** [comment]
> Is there a plan to support this?

As of now, no.

> Every time I click on a crash from the release page, it redirects to unhandled events, but the numbers don't match up. I have to explain this to my boss each time. https://github.com/getsentry/sentry/issues/70570

I mean, it's not wrong. A crashed session implies that there is one or more unhandled event. The numbers don't have to match up.

**Comment by PayneFuRC** [comment]
> Hi, the discover page shows aggregations over all events (you're querying errors) and the releases page simply shows stats on sessions (different event type than errors). A crashed session may contain more than one error. That is likely what's happening here.

Thank you for the detailed explanation. We are currently facing an issue. Recently, we resolved a top #1 crash, but the crash-free session rate has not improved. We have several questions that we need help with:

1. **Session Lifecycle**: How is a session's lifecycle defined? Is it from app start to app exit? If so, does that mean if multiple render process crashes occur, only one will be recorded in the crash free session rate? Our tests suggest otherwise. Could you help clarify this?
  
2. **Multiple Errors/Crashes in One Session**: If multiple errors or crashes occur in one session, is it only counted once? Is it possible to have multiple crashes in one session and have them only counted as one?

3. **Top #1 Crash Resolution**: It seems that the resolution of this top #1 crash hasn't been factored into the crash-free session rate. Could you help us understand why this might be?

These clarifications will help us better understand how to improve our crash-free session rate and assess the impact of our fixes more accurately.

**Comment by timfish** [comment]
> Session Lifecycle: How is a session's lifecycle defined? 

The default session lifecycle is main process start to main process exit. It's handled by the [`mainProcessSessionIntegration`](https://docs.sentry.io/platforms/javascript/guides/electron/configuration/integrations/mainprocesssession/). Alternatively you can use [`browserWindowSessionIntegration`](https://docs.sentry.io/platforms/javascript/guides/electron/configuration/integrations/browserwindowsession/) which captures sessions lined to app focus.

> If so, does that mean if multiple render process crashes occur, only one will be recorded in the crash free session rate?

Any renderer crash will result in that session being marked as crashed. There should still only be a single session so the number of crashes per session should not impact the crash rate.

> Our tests suggest otherwise.

Could you elaborate? 

> If multiple errors or crashes occur in one session, is it only counted once?  Is it possible to have multiple crashes in one session and have them only counted as one?

A session has a state (`'ok' | 'exited' | 'crashed' | 'abnormal'`) and an error count. Any crash or error will set the state and increment the error count. My understanding is that the error count does not impact the crash-free session percentages because it's considered a crashed session regardless of the error count.

**Comment by PayneFuRC** [comment]
@timfish Here's our test result. The main process never exited, it only mocked two render process crashes. The data shows it was counted as two sessions, and two crashes were recorded. This differs from what you said about the session lifecycle. In my case, the main process never exited, so it should only be counted once.
https://jupiter-ct.sentry.io/releases/desktop%4024.3.200%2B11513/?chart=sessionCount&issuesType=all&project=1428302


![Image](https://github.com/user-attachments/assets/e9f13fe1-3b31-43f9-83e8-925e1bc25760)

https://jupiter-ct.sentry.io/releases/?project=1428302&statsPeriod=90d


![Image](https://github.com/user-attachments/assets/79bc06eb-280d-4cef-9fa9-bd493a551fd7)

**Comment by timfish** [comment]
> This differs from what you said about the session lifecycle.

Thanks for the info. I went back and re-read the Sentry backend docs and it specifically says not to send any more updates after a session has crashed and the Electron SDK was not following this.

I've opened a PR that fixes this and adds a test to ensure this doesn't regress.

**Comment by timfish** [comment]
When [this issue](https://github.com/getsentry/publish/issues/4251) closes, 5.4.0 will be published to npm!
