### ISSUE TITLE
Docs still reference `set___Context` functions

### ISSUE THREAD

**Issue by aguynamedben** [getsentry/sentry-electron#95]
Not a big deal, but just trying to help. The Sentry Electron docs still mention the `set___Context` functions that were [removed in version 0.6.0](https://github.com/getsentry/sentry-electron/blob/master/CHANGELOG.md#v060).

https://docs.sentry.io/clients/electron/javascript/
DOCUMENTATION / SDKS / ELECTRON / JAVASCRIPT USAGE

I see:
`Sentry.setUserContext()` x 1
`setTagsContext()` x 2
`setExtraContext()` x 1

The code examples are updated, but not all the copy.

BTW the changelog for this repo is really helpful! So many packages don't have a good changelog. 👏

**Comment by HazAT** [comment]
Thanks for reporting this, our docs build/deploy system is very "fragile" I will check what's going on since it's changed in the files but just not deployed.
