### ISSUE TITLE
Tag values set in main process leak to renderer processes

### ISSUE THREAD

**Issue by aguynamedben** [getsentry/sentry-electron#96]
My app has 3 processes:
- 'main' - The Electron main process
- 'renderer' - The Electron renderer process
- 'backend' - A process for executing CPU-heavy tasks (i.e. don't freeze the UI). This is technically an additional renderer process.

Main process
```js
  // Sentry setup (Electron SDK)
  Sentry.init({
    dsn: process.env.SENTRY_DSN,
    release: `${process.env.SENTRY_PROJECT}-${app.getVersion()}`,
    onFatalError: () => {
      process.exit(1);
    },
  });
  Sentry.configureScope((scope) => {
    scope.setTag('tesla_process_name', 'main');
  });

  try {
    throw new Error(`Ben is testing main error at ${(new Date()).toISOString()}`);
  } catch (e) {
    log.warn(`capturing main error!`);
    Sentry.captureException(e);
  }
```

Renderer process
```js
  Sentry.init({
    dsn: process.env.SENTRY_DSN,
    release: `${process.env.SENTRY_PROJECT}-${remote.app.getVersion()}`,
  });
  Sentry.configureScope((scope) => {
    scope.setTag('tesla_process_name', 'renderer');
  });

  try {
    throw new Error(`Ben is testing renderer error at ${(new Date()).toISOString()}`);
  } catch (e) {
    log.warn(`capturing renderer error!`);
    Sentry.captureException(e);
  }
```

Backend process
```js
  Sentry.init({
    dsn: process.env.SENTRY_DSN,
    release: `${process.env.SENTRY_PROJECT}-${remote.app.getVersion()}`,
  });
  Sentry.configureScope((scope) => {
    scope.setTag('tesla_process_name', 'backend');
  });
try {
  throw new Error(`Ben is testing backend error at ${(new Date()).toISOString()}`);
} catch (e) {
  log.warn(`capturing backend error!`);
  Sentry.captureException(e);
}
```

When I run the code, 3 errors get sent as expected, but all of them have the `tesla_process_name` tag set to 'main'. How can I override the tag value for the renderer and backend processes?

I see in the README a commented out reference to `scope.clear()`, but it doesn't seem documented or in the source. Plus I don't want to clear the whole scope. I just want to update the value of a single tag.

**Comment by HazAT** [comment]
Thanks for the detailed report, this is very helpful 👍 
OK so first of all we set this for you in additional data:
<img width="318" alt="screenshot 2018-07-18 09 15 09" src="https://user-images.githubusercontent.com/363802/42865808-20145e7e-8a6b-11e8-8b99-68d3c5d9c61a.png">
while `crashed_process` is maybe not the ideal name in that case, but it should do the job.

Otherwise since we pipe everything through the main process we still need to figure out how to solve the problem you described.
What has to work is, if you are using different keys for setting the value.

**Comment by aguynamedben** [comment]
One more question related to this...

### Do I need to set tags in each process, or can I just set them in the main process?
I plan on setting a few more tags (i.e. `user_id`). Do I need to set it in both the `main` and `renderer` process, or just in the main? It seems like sentry-electron uses IPC to emit errors from the main process, so maybe I just need to set tags in the main process?

### What happens if I set tags from the renderer process?
Are tags set in renderer process(es) merged with the tags in the main process? Or does each process have it's own unique set of tags?

Thanks! Due to Electron+Node.js unique multi-process architecture, it might be worth noting some of this in https://docs.sentry.io/clients/electron/javascript/#tagging-events (unless I missed something).

**Comment by HazAT** [comment]
Thanks for your analysis and feedback, this is highly appreciated 👍 

Regarding your questions:

Yes, we use IPC to send everything through the main process, so it doesn't really matter where you set the tag it will always end up with your event. It doesn't really matter if it's on the main or renderer process expect one IPC call.

As of right now, there is only one "scope" which means all tags are merged.
