### ISSUE TITLE
Let me enable logging

### ISSUE THREAD

**Issue by pvditto** [getsentry/sentry-electron#970]
### Problem Statement

I have an issue where my app crashes but no report is generated by Sentry. I want to understand Sentry's behavior but by default no logs at all are emitted. The configuration has a `debug` option but it seems to only log at error or warning level. I am not able to understand what Sentry does or what the issue is that prevents my app's crash from being reported.

### Solution Brainstorm

Reading the `@sentry/utils` source code I was able to figure out that I can enable more verbose logging with 

```
const { logger } = require('@sentry/utils');
logger.enable();
```

but this does not seem to be documented anywhere. Can you offer an API or configuration option for this?

*side note: by enabling this, I found out that my app's crash is registered as an "abnormal" exit and not a "crash". I still don't know why that is but at least now I have some information to continue investigating.*

**Comment by timfish** [comment]
Setting `debug: true` in your main process `Sentry.init` should enable logging.

For main process native crashes or abnormal exits, the event is not sent until the next app startup since the process exits immediately.

**Comment by pvditto** [comment]
I took another look and maybe this could have been filed in another repo because the line that makes all the difference is this `if (enabled)` check [here](https://github.com/getsentry/sentry-javascript/blob/a8e5f593b3341f90cf9aafaaa1f6eb1e0da7545e/packages/utils/src/logger.ts#L84). `enabled` is not `true` if `debug: true` has been set for `Sentry.init()`.

But another thing surprised me in your answer: should I expect an event to be sent for abnormal exits? Because I don't see anything and assumed that was the reason and that events would only be sent for `crash` exits.

**Comment by timfish** [comment]
> enabled is not true if debug: true has been set for Sentry.init().

I have not seen this before. Do you have a minimal example that reproduces this? I've checked with the latest version and setting `debug: true` results in debug output.

> should I expect an event to be sent for abnormal exits?

Yes:

- if the main process does not exit cleanly, on the next app start:
  - If there is a minidump file on disk, the previous app session is classified as a main process `crash` 
  - If there is no minidump file, the previous app session is classified as an `abnormal` exit
