### ISSUE TITLE
Support Electron utility processes

### ISSUE THREAD

**Issue by tmm1** [getsentry/sentry-electron#987]
### Problem Statement

electron apps can have utility processes: https://github.com/electron/electron/blob/main/docs/tutorial/process-model.md#the-utility-process

it's not clear whether importing `@sentry/electron/main` or `@sentry/electron/renderer` is correct

### Solution Brainstorm

a new `@sentry/electron/utility` would be ideal from a user perspective

perhaps for now using `@sentry/node` makes the most sense?

**Comment by timfish** [comment]
#991 has been published as part of v5.6.0 of the Electron SDK. 

Let us know how it works for you!
